/**
 * Generated by `flowlet init` — wraps src/components/clients/meta.tsx for the Flowlet sandbox.
 * Review and edit freely; this file is yours. The wrapper body was LLM-authored:
 * it runs inside the egress-jailed sandbox iframe (F3a CSP), but REVIEW IT like
 * any other generated code before committing.
 */
import { Avatar } from "../../../src/components/clients/meta";
import { avatarSchema } from "./descriptor";

// Named AvatarWrapper (not Avatar) so it never collides with the host import.
export function AvatarWrapper(props: Record<string, unknown>) {
  const parsed = avatarSchema.safeParse(props);
  if (!parsed.success) {
    return <div data-testid="flowlet-invalid-props">Invalid component props</div>;
  }
  const p = parsed.data;
  return <Avatar initials={p.initials} className={p.className} />;
}
