/**
 * Generated by `vendo init` — review and edit freely; this file is yours.
 */
import { z } from "zod";
import type { RegisteredComponent, VendoSchema } from "@vendoai/core";

export const cadenceLogoSchema = z.object({
  tone: z.string().optional().describe("Color tone of the wordmark: 'dark' for dark text (default) or 'light' for white text on dark backgrounds."),
  className: z.string().optional().describe("Additional CSS classes to apply to the logo container."),
});

export const cadenceLogoDescriptor: RegisteredComponent = {
  name: "CadenceLogo",
  description: "Displays the Cadence brand lockup consisting of the geometric mark icon and the 'Cadence' wordmark. Use this to render the product logo in headers, splash screens, or marketing surfaces.",
  propsSchema: cadenceLogoSchema as VendoSchema<unknown>,
  source: "host",
};
