/**
 * Generated by `flowlet init` — wraps src/components/brand.tsx for the Flowlet sandbox.
 * Review and edit freely; this file is yours. The wrapper body was LLM-authored:
 * it runs inside the egress-jailed sandbox iframe (F3a CSP), but REVIEW IT like
 * any other generated code before committing.
 */
import { CadenceLogo } from "../../../src/components/brand";
import { cadenceLogoSchema } from "./descriptor";

// Named CadenceLogoWrapper (not CadenceLogo) so it never collides with the host import.
export function CadenceLogoWrapper(props: Record<string, unknown>) {
  const parsed = cadenceLogoSchema.safeParse(props);
  if (!parsed.success) {
    return <div data-testid="flowlet-invalid-props">Invalid component props</div>;
  }
  const p = parsed.data;
  return <CadenceLogo tone={p.tone} className={p.className} />;
}
