/**
 * Generated by `flowlet init` — review and edit freely; this file is yours.
 */
import { z } from "zod";
import type { RegisteredComponent, FlowletSchema } from "@flowlet/core";

export const progressBarSchema = z.object({
  value: z.number().describe("Current progress value."),
  max: z.number().describe("Maximum progress value used to calculate the fill percentage."),
  // Hand-fixed after extraction: the extracted schema exposed `className` —
  // Tailwind classes mean nothing inside the sandbox, so the prop was dropped.
});

export const progressBarDescriptor: RegisteredComponent = {
  name: "ProgressBar",
  description: "A thin horizontal progress bar that fills proportionally based on value and max. Turns green when complete (100%).",
  propsSchema: progressBarSchema as FlowletSchema<unknown>,
  source: "host",
};
