/**
 * 06-apps §4.3/§4.5 (ENG-290 M4, decided option B) — the in-sandbox fetch shim.
 *
 * App code inside the machine holds opaque secret handles, never values. This
 * shim rewrites outbound `fetch(externalUrl)` into `POST {VENDO_PROXY_URL}/egress`
 * authenticated by the run token, so ordinary app code stays unchanged within
 * the Node fetch path while substitution happens ONLY at the proxy, outside the
 * sandbox. Internal requests are never rewritten: relative URLs, non-http(s)
 * schemes, the proxy itself, and loopback (the app's own $PORT server) pass
 * through to native fetch untouched.
 *
 * Failure mode by construction: a request the proxy refuses (non-allowlisted
 * host, SSRF-blocked address) surfaces as an ordinary fetch TypeError — the
 * integration does not authenticate, and nothing can leak, because the sandbox
 * never had a secret value to lose. Clients outside the Node fetch path (raw
 * sockets, spawned binaries) skip the shim entirely and carry only handles.
 *
 * The source ships as a string: it is written to FETCH_SHIM_PATH inside every
 * machine and loaded via `NODE_OPTIONS="--require ..."` by the boot convention
 * (FETCH_SHIM_BOOT_PRELUDE) and the served-app scaffold's start.sh.
 */

/** Where the shim lives inside every machine. */
export const FETCH_SHIM_PATH = "/app/.vendo/fetch-shim.cjs";

/**
 * POSIX-sh prelude for every runtime-owned boot path (rung-2/3 boot, rung-4
 * graduation, Modal's create command, the scaffold's start.sh): when the shim
 * file exists, require it into every Node process the boot spawns. The guard
 * keeps old snapshots (captured before the shim shipped) booting unchanged.
 * NODE_OPTIONS propagates to child node processes, so an app-authored start.sh
 * that spawns node gets the shim too. Requiring twice is harmless — the shim
 * installs itself at most once.
 */
export const FETCH_SHIM_BOOT_PRELUDE =
  `if [ -f ${FETCH_SHIM_PATH} ]; then export NODE_OPTIONS="--require ${FETCH_SHIM_PATH}\${NODE_OPTIONS:+ \$NODE_OPTIONS}"; fi`;

export const FETCH_SHIM_SOURCE = `// Vendo egress fetch shim — 06-apps §4.3/§4.5 (option B). Generated by the
// apps runtime; do not edit. Rewrites outbound fetch(externalUrl) into
// POST {VENDO_PROXY_URL}/egress with the run token. Internal requests
// (relative URLs, the proxy itself, loopback) are never rewritten. The
// sandbox holds only opaque secret handles; substitution happens at the
// proxy, outside this machine.
"use strict";
(() => {
  const proxyUrl = process.env.VENDO_PROXY_URL;
  const runToken = process.env.VENDO_RUN_TOKEN;
  const nativeFetch = globalThis.fetch;
  if (!proxyUrl || !runToken || typeof nativeFetch !== "function") return;
  if (nativeFetch.__vendoEgressShim) return;

  let proxyOrigin;
  let egressEndpoint;
  try {
    const parsed = new URL(proxyUrl);
    proxyOrigin = parsed.origin;
    egressEndpoint = new URL(
      (parsed.pathname.replace(/\\/$/, "") || "") + "/egress",
      parsed,
    ).toString();
  } catch {
    return;
  }

  const isLoopbackHost = (hostname) => {
    const host = hostname.toLowerCase().replace(/^\\[|\\]$/g, "");
    return host === "localhost"
      || host.endsWith(".localhost")
      || host === "::1"
      || host === "0.0.0.0"
      || /^127\\./.test(host);
  };

  // Internal = never rewritten: non-http(s) schemes, the proxy itself, and
  // loopback (the app's own $PORT server, and the proxy when it is tunneled
  // in via localhost). Everything else is external and goes through /egress.
  const isInternal = (url) =>
    (url.protocol !== "http:" && url.protocol !== "https:")
    || url.origin === proxyOrigin
    || isLoopbackHost(url.hostname);

  const shimmedFetch = async (input, init) => {
    let request;
    try {
      request = new Request(input, init);
    } catch {
      // Relative URLs, exotic bodies (streams without duplex), or other
      // constructor failures: defer to native fetch so the app sees the
      // ordinary behavior/error. A direct send can only ever carry opaque
      // handles — the sandbox never holds secret values.
      return nativeFetch(input, init);
    }
    let url;
    try {
      url = new URL(request.url);
    } catch {
      return nativeFetch(request);
    }
    // Forward the CONSTRUCTED request, not the original input: constructing it
    // above already consumed a Request-object input's body, so the original
    // would arrive body-disturbed and throw.
    if (isInternal(url)) return nativeFetch(request);

    const headers = {};
    for (const [name, value] of request.headers) headers[name] = value;
    const method = request.method.toUpperCase();
    let body;
    if (method !== "GET" && method !== "HEAD") {
      body = await request.text();
      if (body === "") body = undefined;
    }

    const envelope = {
      url: url.toString(),
      method,
      ...(Object.keys(headers).length > 0 ? { headers } : {}),
      ...(body === undefined ? {} : { body }),
    };
    const proxied = await nativeFetch(egressEndpoint, {
      method: "POST",
      headers: {
        authorization: "Bearer " + runToken,
        "content-type": "application/json",
      },
      body: JSON.stringify(envelope),
      signal: request.signal, // always an AbortSignal per the fetch spec
    });

    let payload = null;
    try {
      payload = await proxied.json();
    } catch {
      payload = null;
    }
    if (!proxied.ok || payload === null || typeof payload.status !== "number") {
      const code = payload && payload.error && payload.error.code
        ? String(payload.error.code)
        : "egress-failed";
      const message = payload && payload.error && payload.error.message
        ? String(payload.error.message)
        : "egress proxy answered " + proxied.status;
      // Ordinary fetch failure semantics: the integration does not
      // authenticate; nothing to leak — this process never held a value.
      throw new TypeError("fetch failed: vendo egress " + code + ": " + message);
    }

    const responseHeaders = new Headers();
    for (const [name, value] of Object.entries(payload.headers ?? {})) {
      const lower = name.toLowerCase();
      // The proxy already decoded/limited the body; these no longer describe it.
      if (lower === "content-encoding" || lower === "content-length" || lower === "transfer-encoding") continue;
      try {
        responseHeaders.append(name, String(value));
      } catch {
        // Skip names/values Headers refuses; the body is authoritative.
      }
    }
    const status = payload.status;
    const nullBody = status === 204 || status === 205 || status === 304;
    try {
      return new Response(nullBody ? null : String(payload.body ?? ""), {
        status,
        headers: responseHeaders,
      });
    } catch {
      throw new TypeError("fetch failed: vendo egress returned an unrepresentable response (status " + status + ")");
    }
  };

  shimmedFetch.__vendoEgressShim = true;
  globalThis.fetch = shimmedFetch;
})();
`;
