/**
 * Generated by `flowlet init` — review and edit freely; this file is yours.
 */
import { z } from "zod";
import type { RegisteredComponent, FlowletSchema } from "@flowlet/core";

export const cardHeaderSchema = z.object({
  title: z.string().describe("The heading text displayed on the left side of the card header."),
  className: z.string().optional().describe("Additional CSS classes to apply to the header container."),
});

export const cardHeaderDescriptor: RegisteredComponent = {
  name: "CardHeader",
  description: "Renders a card header row with a bold title on the left. Use this to label sections or panels within a card layout.",
  propsSchema: cardHeaderSchema as FlowletSchema<unknown>,
  source: "host",
};
