/** PREBUILT ARTIFACT — generated by `packages/ui/scripts/build-mcp-app-shim.mjs`.
 *
 * The MCP Apps shim: one static HTML document bundling the tree renderer from
 * @vendoai/ui/tree plus the MCP Apps postMessage bridge. It is committed here
 * as a build artifact (never an import) so @vendoai/mcp keeps its core-only
 * dependency edge (docs/contracts/10-mcp.md "Layering"; the regeneration path
 * lives with ui, which owns the renderer source).
 *
 * Regenerate: pnpm --filter @vendoai/ui build:mcp-shim
 *
 * PLACEHOLDER: the wave-6 SHIM lane replaces this with the real bundle.
 */
export const SHIM_HTML: string = "<!doctype html><title>vendo tree shim placeholder</title>";
