/**
 * Generated by `flowlet init` — review and edit freely; this file is yours.
 */
import { z } from "zod";
import type { RegisteredComponent, FlowletSchema } from "@flowlet/core";

export const badgeSchema = z.object({
  text: z.string().describe("The label text displayed inside the badge."),
  // Hand-fixed after extraction: the host component's BadgeVariant is a closed
  // union — an open string let the model invent variants that render unstyled.
  variant: z.enum(["missing", "overdue", "review", "verified", "neutral"]).optional().describe("Color variant controlling the badge appearance. Defaults to 'neutral'."),
  dot: z.boolean().optional().describe("When true, renders a small colored dot before the label text."),
});

export const badgeDescriptor: RegisteredComponent = {
  name: "Badge",
  description: "Displays a small pill-shaped status label with semantic color variants (missing, overdue, review, verified, neutral). Use it to communicate document or item status at a glance.",
  propsSchema: badgeSchema as FlowletSchema<unknown>,
  source: "host",
};
