/**
 * Generated by `flowlet init`, then hand-rewritten: the extracted wrapper
 * imported the host Badge, whose Tailwind classes never load inside the
 * sandbox iframe (CSP blocks external stylesheets), so it rendered unstyled.
 * This version reproduces the host Badge's exact look with inline styles —
 * status tints copied from globals.css — so generated views stay pixel-true.
 */
import type { CSSProperties } from "react";
import { badgeSchema } from "./descriptor";

/** Mirrors BADGE_VARIANTS in src/components/ui/badge.tsx + globals.css tokens. */
const VARIANT_STYLES: Record<string, CSSProperties> = {
  missing: { background: "#fdf0df", color: "#b45309" },
  overdue: { background: "#fdeae8", color: "#b91c1c" },
  review: { background: "#e8eefc", color: "#1d4ed8" },
  verified: { background: "#e2f5ec", color: "#047857" },
  neutral: { background: "#f7f5f1", color: "#5c554b", border: "1px solid #e9e4db" },
};

// Named BadgeWrapper (not Badge) so it never collides with the host import.
export function BadgeWrapper(props: Record<string, unknown>) {
  const parsed = badgeSchema.safeParse(props);
  if (!parsed.success) {
    return <div data-testid="flowlet-invalid-props">Invalid component props</div>;
  }
  const p = parsed.data;
  const variant = p.variant ?? "neutral";
  return (
    <span
      style={{
        display: "inline-flex",
        alignItems: "center",
        gap: 6,
        borderRadius: 9999,
        padding: "2px 8px",
        fontSize: 11,
        fontWeight: 500,
        whiteSpace: "nowrap",
        fontFamily: "var(--flowlet-font, inherit)",
        ...VARIANT_STYLES[variant],
      }}
    >
      {p.dot && (
        <span
          aria-hidden
          style={{ width: 6, height: 6, borderRadius: 9999, background: "currentColor" }}
        />
      )}
      {p.text}
    </span>
  );
}
