/**
 * Generated by `flowlet init` — review and edit freely; this file is yours.
 */
import { z } from "zod";
import type { RegisteredComponent, FlowletSchema } from "@flowlet/core";

export const buttonSchema = z.object({
  label: z.string().describe("Text content displayed inside the button."),
  variant: z.string().optional().describe("Visual style of the button: 'primary' for filled evergreen or 'subtle' for bordered card style."),
  disabled: z.boolean().optional().describe("When true, the button is non-interactive and visually dimmed."),
});

export const buttonDescriptor: RegisteredComponent = {
  name: "Button",
  description: "A compact action button with primary or subtle styling. Use for checklist actions, form submissions, or any small inline action trigger.",
  propsSchema: buttonSchema as FlowletSchema<unknown>,
  source: "host",
};
