import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "vite";

// Builds the docs inline-embed IIFE (window.VendoDocsEmbed) that vendo-web
// serves as https://vendo.run/playground/embed.js and docs-site mounts from
// snippets/vendo-embed.jsx. Run it by hand when that asset needs regenerating
// and copy the output over — nothing in this repo imports the result, so this
// is deliberately NOT wired into build/test/typecheck.
//
// embed-entry.tsx is a thin browser bootstrap over the SAME surface module the
// package exports as `@vendoai/vendo/try-surface`
// (src/cli/playground/app/surface.tsx), which vendo-web's Next route imports
// directly. One source, two venues — no hand-copied blob.
const packageDir = resolve(dirname(fileURLToPath(import.meta.url)), "..");

const entry = resolve(packageDir, "src/cli/playground/app/embed-entry.tsx");
const output = resolve(packageDir, "src/cli/playground/embed-bundle.gen.ts");

const result = await build({
  configFile: false,
  root: packageDir,
  logLevel: "warn",
  define: { "process.env.NODE_ENV": JSON.stringify("production") },
  build: {
    write: false,
    minify: "esbuild",
    target: "es2020",
    lib: {
      entry,
      name: "VendoDocsEmbed",
      formats: ["iife"],
      fileName: () => "bundle.js",
    },
    rollupOptions: {
      output: { inlineDynamicImports: true },
      // "use client" directives in bundled deps are meaningless in an IIFE —
      // drop the warning wall so real warnings stay visible.
      onwarn: (warning, warn) => {
        if (warning.code !== "MODULE_LEVEL_DIRECTIVE") warn(warning);
      },
    },
  },
});

const outputs = Array.isArray(result) ? result.flatMap((entryResult) => entryResult.output) : result.output;
const chunk = outputs.find((item) => item.type === "chunk");
if (!chunk || chunk.type !== "chunk") throw new Error("Vite did not emit the embed bundle chunk");

await mkdir(dirname(output), { recursive: true });
await writeFile(
  output,
  `/** Generated by scripts/build-embed.mjs. Do not edit. */\nexport const EMBED_BUNDLE_SOURCE = ${JSON.stringify(chunk.code)};\n`,
  "utf8",
);
console.log(`[vendo] generated embed bundle (${chunk.code.length} bytes)`);
