import { useState } from "react";
import { z } from "zod";
import {
  VENDO_GENUI_VERSION,
  type VendoUIMessage,
  type GeneratedPayload,
  type UINode,
} from "@vendoai/core";
import { createStubAgent } from "@vendoai/core/testing";
import { VendoProvider, useVendoChat, VendoStage } from "@vendoai/react";
import { createExampleAgent } from "./realAgent";

// ---------------------------------------------------------------------------
// Shared setup
// ---------------------------------------------------------------------------

const agent = createStubAgent();
const realAgent = createExampleAgent();

const components = [
  {
    name: "DemoCard",
    description: "a demo card",
    propsSchema: z.object({ title: z.string() }),
    source: "prewired" as const,
  },
];

type VendoPart = VendoUIMessage["parts"][number];

// ---------------------------------------------------------------------------
// Stub-agent chat (F1 — requires manual approval)
// ---------------------------------------------------------------------------

function Chat() {
  const chat = useVendoChat();
  const parts = chat.messages.flatMap((m) => m.parts);
  // Native ai SDK tool part in the approval-requested state. Its `tool-${string}`
  // discriminant can't be Extract-narrowed to a literal, so cast the matched part.
  const approval = parts.find(
    (p) =>
      p.type === "tool-renderDemoCard" &&
      (p as { state?: string }).state === "approval-requested",
  ) as { approval: { id: string } } | undefined;
  // Our custom data-ui node, emitted by the approved tool's execution.
  const uiNode = parts.find(
    (p): p is Extract<VendoPart, { type: "data-ui" }> => p.type === "data-ui",
  );
  const text = parts
    .filter((p): p is Extract<VendoPart, { type: "text" }> => p.type === "text")
    .map((p) => p.text)
    .join("");

  return (
    <div style={{ fontFamily: "system-ui", maxWidth: 480, margin: "40px auto" }}>
      <button onClick={() => chat.sendMessage({ text: "show me a card" })}>Send</button>
      {text && <p>{text}</p>}
      {approval && (
        <button
          onClick={() =>
            chat.addToolApprovalResponse({ id: approval.approval.id, approved: true })
          }
        >
          Approve rendering the demo card
        </button>
      )}
      {uiNode && <VendoStage node={uiNode.data} />}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Real-agent chat (F2 — policy auto-allows the render_view tool, no prompt)
// ---------------------------------------------------------------------------

function RealChat() {
  const chat = useVendoChat();
  const parts = chat.messages.flatMap((m) => m.parts);
  const uiNode = parts.find(
    (p): p is Extract<VendoPart, { type: "data-ui" }> => p.type === "data-ui",
  );
  const text = parts
    .filter((p): p is Extract<VendoPart, { type: "text" }> => p.type === "text")
    .map((p) => p.text)
    .join("");

  return (
    <div style={{ fontFamily: "system-ui", maxWidth: 480, margin: "40px auto" }}>
      <button onClick={() => chat.sendMessage({ text: "show me a card" })}>Send</button>
      {text && <p>{text}</p>}
      {uiNode && <VendoStage node={uiNode.data} />}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Generated UI (F3: declarative payload + prop-level ui-delta)
// ---------------------------------------------------------------------------

function GeneratedDemo() {
  // The data model the generated tree binds to. Mutating only this drives a
  // prop-level ui-delta (in-place update), not a remount.
  const [data, setData] = useState({ title: "Welcome", body: "Generated by Vendo" });

  // A `generated` UINode built from built-in prewired primitives (no host
  // bundle required). Props bind to `data` via JSON Pointers.
  const payload: GeneratedPayload = {
    formatVersion: VENDO_GENUI_VERSION,
    root: "stack",
    nodes: [
      { id: "stack", component: "Stack", children: ["t", "b"] },
      { id: "t", component: "Text", props: { text: { $path: "/title" }, as: "h2" } },
      { id: "b", component: "Text", props: { text: { $path: "/body" } } },
    ],
    data,
  };
  const generatedNode: UINode = { id: "gen-root", kind: "generated", payload };

  return (
    <div style={{ fontFamily: "system-ui", maxWidth: 480, margin: "40px auto" }}>
      <button onClick={() => setData((d) => ({ ...d, title: "Updated " + Date.now() }))}>
        Update title
      </button>
      <VendoStage node={generatedNode} theme={{ "--brand-text": "#0a7" }} />
    </div>
  );
}

// ---------------------------------------------------------------------------
// Root
// ---------------------------------------------------------------------------

export function App() {
  return (
    <div>
      <h2 style={{ fontFamily: "system-ui", textAlign: "center" }}>Stub agent (F1)</h2>
      <VendoProvider agent={agent} components={components}>
        <Chat />
      </VendoProvider>

      <hr />

      <h2 style={{ fontFamily: "system-ui", textAlign: "center" }}>Real agent (offline)</h2>
      <VendoProvider agent={realAgent} components={components}>
        <RealChat />
      </VendoProvider>

      <hr />

      <h2 style={{ fontFamily: "system-ui", textAlign: "center" }}>Generated UI (F3)</h2>
      <GeneratedDemo />
    </div>
  );
}
