/**
 * Generated by `vendo init`, then hand-rewritten: the extracted wrapper
 * imported the host ProgressBar, whose Tailwind classes never load inside the
 * sandbox iframe (CSP blocks external stylesheets), so it rendered unstyled.
 * This version reproduces the host bar's exact look with inline styles —
 * track/fill colors copied from globals.css (line, evergreen-500,
 * status-verified) — so generated views stay pixel-true.
 */
import { progressBarSchema } from "./descriptor";

// Named ProgressBarWrapper (not ProgressBar) so it never collides with the host import.
export function ProgressBarWrapper(props: Record<string, unknown>) {
  const parsed = progressBarSchema.safeParse(props);
  if (!parsed.success) {
    return <div data-testid="vendo-invalid-props">Invalid component props</div>;
  }
  const p = parsed.data;
  const pct = p.max > 0 ? Math.min(100, Math.round((p.value / p.max) * 100)) : 0;
  return (
    <div
      role="progressbar"
      aria-valuenow={p.value}
      aria-valuemin={0}
      aria-valuemax={p.max}
      style={{
        height: 6,
        width: "100%",
        overflow: "hidden",
        borderRadius: 9999,
        background: "rgba(233, 228, 219, 0.8)",
      }}
    >
      <div
        style={{
          height: "100%",
          borderRadius: 9999,
          transition: "width 500ms",
          width: `${pct}%`,
          background: pct >= 100 ? "#047857" : "#34816a",
        }}
      />
    </div>
  );
}
