import path from "node:path";
import type { LanguageModel } from "ai";
import { detectTarget } from "./detect.js";
import { extractTheme } from "./theme/extract-theme.js";
import { extractTools } from "./tools/extract-tools.js";
import { extractComponents } from "./components/extract-components.js";
import { cliModel } from "./llm.js";
import { renderReport, type InitReport } from "./report.js";
import { writeGenerated } from "./fsx.js";

export interface InitOptions {
  targetDir: string;
  skipLlm: boolean;
  force: boolean;
  /** test seam — pass null to force LLM-off, a mock to avoid the network */
  model?: LanguageModel | null;
}

function readmeSource(report: InitReport): string {
  return `# .flowlet/ — generated by \`flowlet init\`

Everything in this directory is **yours to edit and commit**. \`flowlet init\` never
modifies existing code; re-running it refuses to overwrite these files unless you
pass \`--force\`.

- \`theme.json\` — BrandTokens consumed by the Flowlet sandbox theme injection.
  One mode per file today${report.theme?.hasDarkVariant ? " (dark-scoped variables were detected but not emitted — open schema question)" : ""}.
- \`tools.json\` — your API surface as tool descriptors. \`annotations\` uses MCP-style
  hints: \`readOnlyHint: false\` means mutating, \`destructiveHint: true\` means dangerous
  (approval-gated by the Flowlet policy layer). \`inputSchema\` convention: path/query
  params are top-level properties; a JSON request body is the \`body\` property.
  \`events\` declares host event types usable as automation triggers (empty until you add them).
- \`components/\` — descriptor + sandbox wrapper pairs around your components, plus an
  \`entry.ts\`/\`vite.config.mts\` that build them into a sandbox bundle with
  \`flowletHostPreset\`. Wrapper bodies are LLM-authored code: they execute only
  inside the egress-jailed sandbox iframe, but review them like any generated
  code before committing. Wiring the bundle into a running Flowlet host is
  separate (see ENG-186/ENG-202).

Safety defaults: route-scanned tools are ALL marked \`mutating: true\` (the scan
is LLM-read code and must not grant auto-allow); GETs with side-effect-shaped
names are marked mutating even from OpenAPI. Relax annotations here by hand
after review — this file is the reviewable source of truth.

\`flowlet publish\` uploads tools.json to the Flowlet registry — stubbed until the
registry ships (ENG-198). Embedded hosts read this directory from disk.
`;
}

export async function runInit(opts: InitOptions): Promise<number> {
  const targetDir = path.resolve(opts.targetDir);
  const info = await detectTarget(targetDir);
  const model = opts.skipLlm ? null : opts.model !== undefined ? opts.model : cliModel();

  const report: InitReport = { info, theme: null, tools: null, components: null, llmSkipped: model === null };
  try {
    report.theme = await extractTheme(targetDir, info, opts);
    report.tools = await extractTools(targetDir, info, model, opts);
    if (model) report.components = await extractComponents(targetDir, model, opts);
    await writeGenerated(path.join(targetDir, ".flowlet/README.md"), readmeSource(report), opts);
  } catch (err) {
    console.error(err instanceof Error ? err.message : String(err));
    return 1;
  }
  console.log(renderReport(report));
  return 0;
}
