/**
 * The Next.js (App Router) wiring codemod — the shadcn/next-auth-style half of
 * `flowlet init`. Writes the pieces a host app needs to run Flowlet:
 *
 *   1. `app/api/flowlet/[...path]/route.ts` — `createFlowletHandler()`
 *   2. `app/flowlet-root.tsx` — client wrapper importing `.flowlet/` JSON
 *   3. root layout edit — wraps `{children}` with the wrapper (idempotent)
 *   4. `.env.example` — the three capability-additive keys, documented
 *   5. `public/flowlet/` — sandbox runtime assets (React shim + catalog bundle)
 *   6. `package.json` — adds `@flowlet/next` to dependencies
 *
 * SAFETY CONTRACT: never break existing code. Every step that cannot proceed
 * with certainty (unrecognizable layout, ambiguous `{children}`, missing app
 * dir) is SKIPPED and reported with exact manual instructions instead of
 * guessing. All edits are plain files reviewable in one `git diff`.
 */
import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { FrameworkInfo } from "./detect.js";

export interface WiringSummary {
  /** Files created. */
  written: string[];
  /** Files edited in place. */
  edited: string[];
  /** Steps intentionally not performed, with why. */
  skipped: Array<{ step: string; reason: string }>;
  /** Manual follow-ups the developer must do (printed at the end). */
  manual: string[];
}

async function exists(p: string): Promise<boolean> {
  return fs.access(p).then(() => true, () => false);
}

async function readIf(p: string): Promise<string | null> {
  try {
    return await fs.readFile(p, "utf8");
  } catch {
    return null;
  }
}

/** Locate the App Router directory (`app/` or `src/app/`) with a root layout. */
export async function findAppDir(
  targetDir: string,
): Promise<{ appDir: string; layoutFile: string } | null> {
  for (const rel of ["app", "src/app"]) {
    const appDir = path.join(targetDir, rel);
    for (const name of ["layout.tsx", "layout.jsx", "layout.js"]) {
      const layoutFile = path.join(appDir, name);
      if (await exists(layoutFile)) return { appDir, layoutFile };
    }
  }
  return null;
}

/** Title-case the package.json name for a friendly default product name. */
export function productNameFrom(pkgName: unknown): string {
  if (typeof pkgName !== "string" || pkgName.length === 0) return "Assistant";
  const base = pkgName.split("/").pop() ?? pkgName;
  return base
    .split(/[-_.]+/)
    .filter(Boolean)
    .map((w) => (w[0]?.toUpperCase() ?? "") + w.slice(1))
    .join(" ");
}

const ROUTE_SOURCE = `/**
 * All Flowlet endpoints (chat, action, integrations, capabilities, tick) are
 * served by this one catch-all. Generated by \`flowlet init\` — safe to edit;
 * pass options to createFlowletHandler() to customize (model, policy, tools).
 */
import { createFlowletHandler } from "@flowlet/next";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export const { GET, POST } = createFlowletHandler();
`;

function rootSource(opts: { ts: boolean; flowletRel: string; productName: string }): string {
  const typeImport = opts.ts ? `import type { ReactNode } from "react";\n` : "";
  const propsSig = opts.ts ? `{ children }: { children: ReactNode }` : `{ children }`;
  return `"use client";

/**
 * The app's Flowlet provider, generated by \`flowlet init\`. Wraps the root
 * layout's children so every page gets the assistant overlay (Cmd/Ctrl+K or
 * the launcher pill). Theme and tools come from .flowlet/ — edit those files,
 * not this one, to change brand or API surface.
 */
import { FlowletRoot } from "@flowlet/next/client";
${typeImport}import theme from "${opts.flowletRel}/theme.json";
import tools from "${opts.flowletRel}/tools.json";

export function AppFlowletRoot(${propsSig}) {
  return (
    <FlowletRoot theme={theme} tools={tools} productName="${opts.productName}">
      {children}
    </FlowletRoot>
  );
}
`;
}

const ENV_EXAMPLE = `# Flowlet — capability-additive keys (add what you need, restart dev server)
#
# REQUIRED for chat + generated UI (the one-key minimum):
ANTHROPIC_API_KEY=

# OPTIONAL: unlocks integrations (Gmail, Slack, ...) via Composio OAuth.
# Without it the integrations UI stays hidden — nothing breaks.
COMPOSIO_API_KEY=

# OPTIONAL: reserved for voice (in design). Detected and exposed as a
# capability flag only — no voice UX ships yet.
OPENAI_API_KEY=
`;

/**
 * Wrap the single `{children}` expression of the root layout with the
 * generated provider. Returns the edited source, or null when the file cannot
 * be edited with certainty (caller falls back to manual instructions).
 *
 * Targets the standard layout shape (one JSX `{children}` in child position).
 * Known limitation: a `{children}` nested inside a JSX ATTRIBUTE expression
 * (e.g. `<Chrome slot={<b>{children}</b>}>...`) is indistinguishable from a
 * real child by this heuristic and would be wrapped in the wrong place — such
 * exotic layouts should be wired by hand (the whole edit is one reviewable
 * diff). create-next-app and typical provider layouts are handled correctly.
 */
/**
 * Return a copy of `source` with the CONTENTS of string/template literals and
 * comments blanked to spaces (quotes/delimiters kept, lengths and offsets
 * preserved). We locate `{children}` and detect idempotence against THIS
 * masked view so a `{children}` sitting inside a string (`"<b>{children}</b>"`)
 * or a comment (`// rename AppFlowletRoot`) can never be matched or mistaken
 * for existing wiring — then splice edits back into the ORIGINAL by offset.
 */
function maskLiterals(source: string): string {
  const out = source.split("");
  let i = 0;
  const n = source.length;
  const blank = (from: number, to: number) => {
    for (let k = from; k < to && k < n; k++) if (source[k] !== "\n") out[k] = " ";
  };
  while (i < n) {
    const c = source[i];
    const next = source[i + 1];
    if (c === "/" && next === "/") {
      let j = i + 2;
      while (j < n && source[j] !== "\n") j++;
      blank(i, j);
      i = j;
    } else if (c === "/" && next === "*") {
      let j = i + 2;
      while (j < n && !(source[j] === "*" && source[j + 1] === "/")) j++;
      blank(i, Math.min(j + 2, n));
      i = j + 2;
    } else if (c === '"' || c === "'" || c === "`") {
      const quote = c;
      let j = i + 1;
      while (j < n) {
        if (source[j] === "\\") { j += 2; continue; }
        if (source[j] === quote) break;
        j++;
      }
      blank(i + 1, j); // keep the delimiters, blank the interior
      i = j + 1;
    } else {
      i++;
    }
  }
  return out.join("");
}

export function wrapLayoutChildren(source: string, componentName = "AppFlowletRoot"): string | null {
  const masked = maskLiterals(source);
  // Idempotence: already wired (by us or by hand). Checked against the masked
  // view so an incidental mention in a comment/string doesn't false-positive.
  if (masked.includes('from "./flowlet-root"') || masked.includes(`<${componentName}>`)) {
    return source;
  }

  // Candidate `{children}` expressions in real code (not strings/comments),
  // filtered to JSX child position: the preceding non-whitespace char must be
  // `>` (end of an opening tag). This excludes destructured parameters
  // `({ children })` and type annotations.
  const matches = [...masked.matchAll(/\{\s*children\s*\}/g)].filter((m) => {
    const before = masked.slice(0, m.index).trimEnd();
    return before.endsWith(">");
  });
  if (matches.length !== 1) return null; // zero or ambiguous — do not guess

  const match = matches[0]!;
  const start = match.index;
  const original = source.slice(start, start + match[0].length); // exact orig text
  const wrapped =
    source.slice(0, start) +
    `<${componentName}>` +
    original +
    `</${componentName}>` +
    source.slice(start + match[0].length);

  // Insert the import at an ALWAYS-VALID position: immediately after a leading
  // "use client"/"use server" directive if present, else at the very top.
  // (Anchoring after "the last import" is unsafe — a Prettier-wrapped
  //  multi-line import would land the new line INSIDE the brace block.)
  //
  // A directive must remain the FIRST statement, but Next allows comments above
  // it — so skip leading comments/whitespace (found on the masked copy, which
  // has comment CONTENT blanked but delimiters/offsets intact) before checking.
  const importStmt = `import { ${componentName} } from "./flowlet-root";\n`;
  // maskLiterals blanks comment bodies AND their delimiters to spaces, so the
  // leading `\s*` on the masked copy skips whitespace and header comments in
  // one go. Detect the directive on the ORIGINAL at that offset, though — the
  // mask also blanks the "use client" string interior.
  const headerLen = maskLiterals(wrapped).match(/^\s*/)?.[0].length ?? 0;
  const directive = wrapped.slice(headerLen).match(/^(['"]use [a-z ]+['"];?[^\n]*\n)/);
  if (directive) {
    const end = headerLen + directive[0].length;
    return wrapped.slice(0, end) + importStmt + wrapped.slice(end);
  }
  return importStmt + wrapped;
}

/** Merge `@flowlet/next` into package.json dependencies (format-preserving-ish:
 *  2-space JSON, trailing newline — the npm convention). */
export function addDependency(pkgJson: string, name: string, version: string): string | null {
  let pkg: Record<string, unknown>;
  try {
    pkg = JSON.parse(pkgJson) as Record<string, unknown>;
  } catch {
    return null;
  }
  const deps = (pkg["dependencies"] ?? {}) as Record<string, string>;
  if (deps[name]) return pkgJson; // already present — leave the file alone
  pkg["dependencies"] = Object.fromEntries(
    Object.entries({ ...deps, [name]: version }).sort(([a], [b]) => a.localeCompare(b)),
  );
  return JSON.stringify(pkg, null, 2) + "\n";
}

/** Add `flowlet sync` to the app's `prebuild` script (create or extend),
 *  so every production build refreshes the capture + sandbox environment.
 *  Idempotent: never adds a second copy. */
export function addPrebuildSync(pkgJson: string): string | null {
  let pkg: Record<string, unknown>;
  try {
    pkg = JSON.parse(pkgJson) as Record<string, unknown>;
  } catch {
    return null;
  }
  const scripts = (pkg["scripts"] ?? {}) as Record<string, string>;
  const existing = scripts["prebuild"];
  if (existing?.includes("flowlet sync")) return pkgJson; // already wired
  scripts["prebuild"] = existing ? `${existing} && flowlet sync` : "flowlet sync";
  pkg["scripts"] = scripts;
  return JSON.stringify(pkg, null, 2) + "\n";
}

/** Sandbox assets bundled with the CLI at build time (see scripts/bundle-assets.mjs). */
function bundledAssetsDir(): string {
  return fileURLToPath(new URL("./assets/", import.meta.url));
}

const MANUAL_LAYOUT = (layoutFile: string) =>
  `wrap your root layout's {children} manually in ${layoutFile}:\n` +
  `    import { AppFlowletRoot } from "./flowlet-root";\n` +
  `    ...<AppFlowletRoot>{children}</AppFlowletRoot>...`;

export async function wireNextApp(
  targetDir: string,
  info: FrameworkInfo,
  opts: { force: boolean },
): Promise<WiringSummary | null> {
  if (info.framework !== "next") return null;
  const found = await findAppDir(targetDir);
  const summary: WiringSummary = { written: [], edited: [], skipped: [], manual: [] };
  if (!found) {
    summary.skipped.push({
      step: "next-wiring",
      reason:
        "no App Router root layout at app/layout.* or src/app/layout.*. " +
        "Pages Router and route-group-only roots (app/(group)/layout.*) aren't " +
        "auto-wired yet — add app/api/flowlet/[...path]/route.ts and wrap your " +
        "root layout with <AppFlowletRoot> by hand (see @flowlet/next).",
    });
    return summary;
  }
  const { appDir, layoutFile } = found;
  const ts = layoutFile.endsWith(".tsx") || (await exists(path.join(targetDir, "tsconfig.json")));
  const rel = (p: string) => path.relative(targetDir, p);

  // 0. Guarantee the .flowlet JSON artifacts the wrapper imports exist (the
  // extractor may have skipped them, and a missing JSON import breaks builds).
  const themePath = path.join(targetDir, ".flowlet/theme.json");
  if (!(await exists(themePath))) {
    await fs.mkdir(path.dirname(themePath), { recursive: true });
    await fs.writeFile(
      themePath,
      JSON.stringify(
        {
          version: 1,
          accent: "#0A7CFF",
          background: "#FFFFFF",
          surface: "#F5F7FA",
          text: "#111418",
          mutedText: "#5B6470",
          fontFamily: "system-ui, -apple-system, Segoe UI, Roboto, sans-serif",
          radius: 8,
          mode: "light",
        },
        null,
        2,
      ) + "\n",
    );
    summary.written.push(rel(themePath));
  }
  const toolsPath = path.join(targetDir, ".flowlet/tools.json");
  if (!(await exists(toolsPath))) {
    await fs.writeFile(toolsPath, JSON.stringify({ version: 1, tools: [], events: [] }, null, 2) + "\n");
    summary.written.push(rel(toolsPath));
  }

  // 1. The catch-all route.
  const routeFile = path.join(appDir, "api/flowlet/[...path]", ts ? "route.ts" : "route.js");
  if (await exists(routeFile)) {
    summary.skipped.push({ step: "route", reason: `${rel(routeFile)} already exists` });
  } else {
    await fs.mkdir(path.dirname(routeFile), { recursive: true });
    await fs.writeFile(routeFile, ROUTE_SOURCE);
    summary.written.push(rel(routeFile));
  }

  // 2. The client wrapper.
  const rootFile = path.join(appDir, ts ? "flowlet-root.tsx" : "flowlet-root.jsx");
  const flowletRel = path
    .relative(appDir, path.join(targetDir, ".flowlet"))
    .split(path.sep)
    .join("/");
  let productName = "Assistant";
  const pkgRaw = await readIf(path.join(targetDir, "package.json"));
  if (pkgRaw) {
    try {
      productName = productNameFrom((JSON.parse(pkgRaw) as { name?: string }).name);
    } catch {
      /* keep default */
    }
  }
  if (await exists(rootFile)) {
    summary.skipped.push({ step: "flowlet-root", reason: `${rel(rootFile)} already exists` });
  } else {
    await fs.writeFile(rootFile, rootSource({ ts, flowletRel, productName }));
    summary.written.push(rel(rootFile));
  }

  // 3. Layout wrap (never rewrites on uncertainty).
  const layoutSource = await readIf(layoutFile);
  if (layoutSource === null) {
    summary.skipped.push({ step: "layout", reason: `${rel(layoutFile)} unreadable` });
    summary.manual.push(MANUAL_LAYOUT(rel(layoutFile)));
  } else {
    const edited = wrapLayoutChildren(layoutSource);
    if (edited === null) {
      summary.skipped.push({
        step: "layout",
        reason: `could not find exactly one {children} in ${rel(layoutFile)} — left untouched`,
      });
      summary.manual.push(MANUAL_LAYOUT(rel(layoutFile)));
    } else if (edited !== layoutSource) {
      await fs.writeFile(layoutFile, edited);
      summary.edited.push(rel(layoutFile));
    } else {
      summary.skipped.push({ step: "layout", reason: "already wired" });
    }
  }

  // 4. .env.example — create, or append the Flowlet block once.
  const envFile = path.join(targetDir, ".env.example");
  const envExisting = await readIf(envFile);
  if (envExisting === null) {
    await fs.writeFile(envFile, ENV_EXAMPLE);
    summary.written.push(rel(envFile));
  } else if (!envExisting.includes("ANTHROPIC_API_KEY")) {
    await fs.writeFile(envFile, envExisting.replace(/\n?$/, "\n\n") + ENV_EXAMPLE);
    summary.edited.push(rel(envFile));
  } else {
    summary.skipped.push({ step: ".env.example", reason: "already documents ANTHROPIC_API_KEY" });
  }

  // 5. Sandbox assets into public/flowlet/.
  const assetsDir = bundledAssetsDir();
  const publicDir = path.join(targetDir, "public/flowlet");
  const assets: Array<[string, string]> = [
    ["flowlet-react-runtime.js", "react-runtime.js"],
    ["flowlet-components-sandbox.js", "components-sandbox.js"],
  ];
  for (const [from, to] of assets) {
    const src = path.join(assetsDir, from);
    const dest = path.join(publicDir, to);
    if (!(await exists(src))) {
      summary.skipped.push({ step: "sandbox-assets", reason: `bundled asset ${from} missing from CLI build` });
      summary.manual.push(
        "copy the sandbox assets by hand: react-runtime.js + components-sandbox.js into public/flowlet/ (see @flowlet/next docs)",
      );
      break;
    }
    if ((await exists(dest)) && !opts.force) {
      summary.skipped.push({ step: "sandbox-assets", reason: `${rel(dest)} already exists` });
      continue;
    }
    await fs.mkdir(publicDir, { recursive: true });
    await fs.copyFile(src, dest);
    summary.written.push(rel(dest));
  }

  // 6. package.json: @flowlet/next dependency + prebuild sync wiring.
  if (pkgRaw) {
    const withDep = addDependency(pkgRaw, "@flowlet/next", "latest");
    if (withDep === null) {
      summary.skipped.push({ step: "package.json", reason: "unparsable — add @flowlet/next yourself" });
      summary.manual.push('add "@flowlet/next" to package.json dependencies and install');
      summary.manual.push('add "flowlet sync" to your package.json "prebuild" script');
    } else {
      const withSync = addPrebuildSync(withDep) ?? withDep;
      if (withSync !== pkgRaw) {
        await fs.writeFile(path.join(targetDir, "package.json"), withSync);
        summary.edited.push("package.json");
        if (withDep !== pkgRaw) {
          summary.manual.push("run your package manager's install (npm/pnpm/yarn) to pull @flowlet/next");
        }
      } else {
        summary.skipped.push({ step: "package.json", reason: "@flowlet/next + prebuild sync already present" });
      }
    }
  }

  return summary;
}

export function renderWiring(w: WiringSummary | null): string {
  if (!w) return "";
  const lines: string[] = [];
  for (const f of w.written) lines.push(`  wrote  ${f}`);
  for (const f of w.edited) lines.push(`  edited ${f}`);
  for (const s of w.skipped) lines.push(`  skip   ${s.step}: ${s.reason}`);
  if (w.manual.length > 0) {
    lines.push("  TODO (manual):");
    for (const m of w.manual) lines.push(`   - ${m}`);
  }
  if (lines.length === 0) return "";
  return ["next wiring:", ...lines].join("\n");
}
