import { mkdtempSync } from "node:fs";
import { promises as fs } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { describe, expect, it } from "vitest";
import {
  addDependency,
  productNameFrom,
  wireNextApp,
  wrapLayoutChildren,
} from "./next-wiring.js";
import { detectTarget } from "./detect.js";

const CREATE_NEXT_APP_LAYOUT = `import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={\`\${geistSans.variable} antialiased\`}>
        {children}
      </body>
    </html>
  );
}
`;

describe("wrapLayoutChildren", () => {
  it("wraps the create-next-app layout and inserts a valid top-level import", () => {
    const out = wrapLayoutChildren(CREATE_NEXT_APP_LAYOUT);
    expect(out).not.toBeNull();
    // import is at the very top (no directive here) and syntactically valid
    expect(out!.startsWith('import { AppFlowletRoot } from "./flowlet-root";\n')).toBe(true);
    expect(out).toContain("<AppFlowletRoot>{children}</AppFlowletRoot>");
    // the app's own imports survive intact
    expect(out).toContain('import { Geist, Geist_Mono } from "next/font/google";');
    // destructured prop `children,` in the signature must NOT be touched
    expect(out).toContain("children,\n}: Readonly<{");
  });

  it("respects existing providers (wraps only the children expression)", () => {
    const layout = `import { ThemeProvider } from "./providers";
export default function RootLayout({ children }) {
  return (
    <html><body><ThemeProvider>{ children }</ThemeProvider></body></html>
  );
}
`;
    const out = wrapLayoutChildren(layout);
    expect(out).toContain("<ThemeProvider><AppFlowletRoot>{ children }</AppFlowletRoot></ThemeProvider>");
  });

  it("is idempotent on an already-wired layout", () => {
    const wired = wrapLayoutChildren(CREATE_NEXT_APP_LAYOUT)!;
    expect(wrapLayoutChildren(wired)).toBe(wired);
  });

  it("fails open when {children} is absent or ambiguous", () => {
    expect(wrapLayoutChildren("export default function L() { return null }")).toBeNull();
    const two = `export default function L({children}) { return <a><b>{children}</b><c>{children}</c></a> }`;
    expect(wrapLayoutChildren(two)).toBeNull();
  });

  it("does not corrupt a Prettier-wrapped multi-line last import (review P0)", () => {
    const layout = `import type { Metadata } from "next";
import {
  ThemeProvider,
  AnalyticsProvider,
} from "@/components/providers";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return <html><body><ThemeProvider>{children}</ThemeProvider></body></html>;
}
`;
    const out = wrapLayoutChildren(layout)!;
    // import lands on its own line at the top, never inside the brace block
    expect(out).toContain('import { AppFlowletRoot } from "./flowlet-root";\n');
    expect(out).not.toMatch(/import \{\nimport \{ AppFlowletRoot/);
    expect(out).toContain("<ThemeProvider><AppFlowletRoot>{children}</AppFlowletRoot></ThemeProvider>");
    // the original multi-line import survives intact
    expect(out).toContain("  ThemeProvider,\n  AnalyticsProvider,\n} from");
  });

  it("ignores a {children} that lives inside a string literal (review P1)", () => {
    const layout = `export default function RootLayout({ children }: { children: React.ReactNode }) {
  const example = "<body>{children}</body>";
  return <html><body>{props.notChildren}</body></html>;
}
`;
    // the only >{children} is inside a string → no real JSX child match → fail open
    expect(wrapLayoutChildren(layout)).toBeNull();
  });

  it("does not false-positive idempotence on a comment mentioning the component (review P2)", () => {
    const layout = `// TODO: rename AppFlowletRoot someday
export default function RootLayout({ children }) {
  return <html><body>{children}</body></html>;
}
`;
    const out = wrapLayoutChildren(layout);
    expect(out).not.toBeNull();
    expect(out).toContain("<AppFlowletRoot>{children}</AppFlowletRoot>");
  });

  it("places the import after a use-client directive when there are no imports", () => {
    const layout = `"use client";
export default function RootLayout({ children }) {
  return <html><body>{children}</body></html>;
}
`;
    const out = wrapLayoutChildren(layout)!;
    expect(out.startsWith(`"use client";\nimport { AppFlowletRoot } from "./flowlet-root";`)).toBe(true);
  });

  it("keeps the import BELOW a use-client directive that has a leading comment (review P1)", () => {
    const layout = `// Copyright 2026 Acme
"use client";
import { useState } from "react";
export default function RootLayout({ children }) {
  return <html><body>{children}</body></html>;
}
`;
    const out = wrapLayoutChildren(layout)!;
    // directive must remain the first STATEMENT (import inserted after it),
    // else Next demotes the file to a server component and hooks break.
    const dirIdx = out.indexOf('"use client";');
    const impIdx = out.indexOf('import { AppFlowletRoot }');
    expect(dirIdx).toBeGreaterThanOrEqual(0);
    expect(impIdx).toBeGreaterThan(dirIdx);
    // nothing but the comment + whitespace precedes the directive
    expect(out.slice(0, dirIdx).trim()).toBe("// Copyright 2026 Acme");
  });
});

describe("addDependency", () => {
  it("adds the dep sorted and leaves existing files alone on re-run", () => {
    const pkg = JSON.stringify({ name: "x", dependencies: { zod: "^3", next: "16.0.0" } }, null, 2);
    const out = addDependency(pkg, "@flowlet/next", "latest")!;
    const parsed = JSON.parse(out) as { dependencies: Record<string, string> };
    expect(Object.keys(parsed.dependencies)).toEqual(["@flowlet/next", "next", "zod"]);
    expect(addDependency(out, "@flowlet/next", "latest")).toBe(out);
  });

  it("returns null on unparsable package.json", () => {
    expect(addDependency("{nope", "@flowlet/next", "latest")).toBeNull();
  });
});

describe("productNameFrom", () => {
  it("title-cases package names", () => {
    expect(productNameFrom("my-cool-app")).toBe("My Cool App");
    expect(productNameFrom("@acme/dash_board")).toBe("Dash Board");
    expect(productNameFrom(undefined)).toBe("Assistant");
  });
});

async function scaffoldFreshApp(withSrcDir: boolean): Promise<string> {
  const dir = mkdtempSync(path.join(tmpdir(), "flowlet-wire-"));
  const appDir = path.join(dir, withSrcDir ? "src/app" : "app");
  await fs.mkdir(appDir, { recursive: true });
  await fs.writeFile(path.join(appDir, "layout.tsx"), CREATE_NEXT_APP_LAYOUT);
  await fs.writeFile(path.join(dir, "tsconfig.json"), "{}");
  await fs.writeFile(
    path.join(dir, "package.json"),
    JSON.stringify({ name: "fresh-app", dependencies: { next: "16.0.0" } }, null, 2),
  );
  return dir;
}

describe("wireNextApp", () => {
  it("wires a fresh TS app end-to-end (src/app layout)", async () => {
    const dir = await scaffoldFreshApp(true);
    const info = await detectTarget(dir);
    const summary = (await wireNextApp(dir, info, { force: false }))!;

    // route + wrapper + env + .flowlet backfill written
    const route = await fs.readFile(path.join(dir, "src/app/api/flowlet/[...path]/route.ts"), "utf8");
    expect(route).toContain("createFlowletHandler()");
    expect(route).toContain('runtime = "nodejs"');
    const root = await fs.readFile(path.join(dir, "src/app/flowlet-root.tsx"), "utf8");
    expect(root).toContain('from "../../.flowlet/theme.json"');
    expect(root).toContain('productName="Fresh App"');
    const layout = await fs.readFile(path.join(dir, "src/app/layout.tsx"), "utf8");
    expect(layout).toContain("<AppFlowletRoot>{children}</AppFlowletRoot>");
    expect(await fs.readFile(path.join(dir, ".env.example"), "utf8")).toContain("ANTHROPIC_API_KEY");
    expect(JSON.parse(await fs.readFile(path.join(dir, ".flowlet/tools.json"), "utf8")).tools).toEqual([]);
    const pkg = JSON.parse(await fs.readFile(path.join(dir, "package.json"), "utf8")) as {
      dependencies: Record<string, string>;
    };
    expect(pkg.dependencies["@flowlet/next"]).toBeDefined();

    // sandbox assets aren't bundled in the source tree — reported, not fatal
    expect(summary.skipped.some((s) => s.step === "sandbox-assets")).toBe(true);
  });

  it("is idempotent: a second run edits nothing", async () => {
    const dir = await scaffoldFreshApp(false);
    const info = await detectTarget(dir);
    await wireNextApp(dir, info, { force: false });
    const layoutAfterFirst = await fs.readFile(path.join(dir, "app/layout.tsx"), "utf8");
    const second = (await wireNextApp(dir, info, { force: false }))!;
    expect(second.edited).toEqual([]);
    expect(await fs.readFile(path.join(dir, "app/layout.tsx"), "utf8")).toBe(layoutAfterFirst);
  });

  it("fails open on an unrecognizable layout: files written, layout untouched, manual steps printed", async () => {
    const dir = await scaffoldFreshApp(false);
    const weird = "export default function L() { return <Slot /> }\n";
    await fs.writeFile(path.join(dir, "app/layout.tsx"), weird);
    const info = await detectTarget(dir);
    const summary = (await wireNextApp(dir, info, { force: false }))!;
    expect(await fs.readFile(path.join(dir, "app/layout.tsx"), "utf8")).toBe(weird);
    expect(summary.skipped.some((s) => s.step === "layout")).toBe(true);
    expect(summary.manual.some((m) => m.includes("AppFlowletRoot"))).toBe(true);
  });

  it("returns null for non-Next targets and skips gracefully without an app dir", async () => {
    const dir = mkdtempSync(path.join(tmpdir(), "flowlet-wire-"));
    await fs.writeFile(path.join(dir, "package.json"), JSON.stringify({ name: "not-next" }));
    expect(await wireNextApp(dir, await detectTarget(dir), { force: false })).toBeNull();

    await fs.writeFile(
      path.join(dir, "package.json"),
      JSON.stringify({ name: "pages-router", dependencies: { next: "16.0.0" } }),
    );
    const summary = (await wireNextApp(dir, await detectTarget(dir), { force: false }))!;
    expect(summary.skipped[0]?.reason).toContain("no App Router root layout");
  });
});
