/**
 * Generated by `vendo init` — review and edit freely; this file is yours.
 */
import { z } from "zod";
import type { RegisteredComponent, VendoSchema } from "@vendoai/core";

export const barsSchema = z.object({
  items: z.string().describe("JSON string of BarItem array: [{label, value, color?, max?}] where value is a number and color is an optional CSS color string."),
});

export const barsDescriptor: RegisteredComponent = {
  name: "Bars",
  description: "Renders a vertical list of horizontal progress bars with a label and USD-formatted value for each item. Use for visualizing category spend, budgets, or any ranked numeric data.",
  propsSchema: barsSchema as VendoSchema<unknown>,
  source: "host",
};
