/**
 * Generated by `flowlet init`. Sandbox host bundle entry: exposes wrapped host
 * components to the Flowlet stage runtime (window.__FLOWLET_HOST__ contract —
 * see packages/flowlet-components/bundle/entry.ts for the reference bundle).
 * NOTE: merging these with the prewired bundle is host wiring (ENG-186/ENG-202).
 */
import React from "react";
import { createRoot } from "react-dom/client";
import { BadgeWrapper } from "./Badge/impl";
import { ButtonWrapper } from "./Button/impl";
import { HostCardWrapper } from "./HostCard/impl";
import { MapleMarkWrapper } from "./MapleMark/impl";
import { SkeletonTextWrapper } from "./SkeletonText/impl";
import { BarsWrapper } from "./Bars/impl";

declare global {
  interface Window {
    __React: typeof React;
    __createRoot: typeof createRoot;
    __FLOWLET_HOST__: Record<string, unknown>;
  }
}

window.__React = React;
window.__createRoot = createRoot;
window.__FLOWLET_HOST__ = { Badge: BadgeWrapper, Button: ButtonWrapper, HostCard: HostCardWrapper, MapleMark: MapleMarkWrapper, SkeletonText: SkeletonTextWrapper, Bars: BarsWrapper };
