/** Generated by `flowlet init`. Builds the host-component sandbox bundle. */
import path from "node:path";
import { fileURLToPath } from "node:url";
import { flowletHostPreset } from "@flowlet/stage/build";

const here = path.dirname(fileURLToPath(import.meta.url));
const base = flowletHostPreset({ entry: "entry.ts", version: "0.0.1" });

const config = {
  ...base,
  // Host tsconfig path aliases, re-rooted relative to this directory.
  resolve: { alias: { "@": path.resolve(here, "../../src") } },
};

export default config;
