/**
 * Generated by `vendo init` — review and edit freely; this file is yours.
 */
import { z } from "zod";
import type { RegisteredComponent, VendoSchema } from "@vendoai/core";

export const hostCardSchema = z.object({
  title: z.string().optional().describe("Label displayed in the card header in small uppercase muted text."),
  content: z.string().describe("Main body text rendered inside the card content area."),
  hover: z.boolean().optional().describe("When true, adds a subtle drop shadow on hover to indicate interactivity."),
});

export const hostCardDescriptor: RegisteredComponent = {
  name: "HostCard",
  description: "A styled surface container with an optional header title and content area. Use it to group related information into a visually distinct card panel.",
  propsSchema: hostCardSchema as VendoSchema<unknown>,
  source: "host",
};
