/**
 * Generated by `vendo init`. Sandbox host bundle entry: exposes wrapped host
 * components to the Vendo stage runtime (window.__VENDO_HOST__ contract —
 * see packages/vendo-components/bundle/entry.ts for the reference bundle).
 * NOTE: merging these with the prewired bundle is host wiring (ENG-186/ENG-202).
 */
import React from "react";
import { createRoot } from "react-dom/client";
import { BadgeWrapper } from "./Badge/impl";
import { ButtonWrapper } from "./Button/impl";
import { CardHeaderWrapper } from "./CardHeader/impl";
import { ErrorStateWrapper } from "./ErrorState/impl";
import { ProgressBarWrapper } from "./ProgressBar/impl";
import { SkeletonWrapper } from "./Skeleton/impl";
import { CadenceLogoWrapper } from "./CadenceLogo/impl";
import { AvatarWrapper } from "./Avatar/impl";

declare global {
  interface Window {
    __React: typeof React;
    __createRoot: typeof createRoot;
    __VENDO_HOST__: Record<string, unknown>;
  }
}

window.__React = React;
window.__createRoot = createRoot;
window.__VENDO_HOST__ = { Badge: BadgeWrapper, Button: ButtonWrapper, CardHeader: CardHeaderWrapper, ErrorState: ErrorStateWrapper, ProgressBar: ProgressBarWrapper, Skeleton: SkeletonWrapper, CadenceLogo: CadenceLogoWrapper, Avatar: AvatarWrapper };
