/**
 * Generated by `flowlet init` — review and edit freely; this file is yours.
 */
import { z } from "zod";
import type { RegisteredComponent, FlowletSchema } from "@flowlet/core";

export const skeletonSchema = z.object({
  className: z.string().optional().describe("Additional Tailwind CSS classes to control the size and shape of the skeleton placeholder (e.g. 'h-4 w-32')."),
});

export const skeletonDescriptor: RegisteredComponent = {
  name: "Skeleton",
  description: "Displays an animated pulsing placeholder block to indicate loading state. Use it to represent content that is being fetched or processed.",
  propsSchema: skeletonSchema as FlowletSchema<unknown>,
  source: "host",
};
