/**
 * Generated by `vendo init` — review and edit freely; this file is yours.
 */
import { z } from "zod";
import type { RegisteredComponent, VendoSchema } from "@vendoai/core";

export const skeletonSchema = z.object({
  className: z.string().optional().describe("Additional Tailwind CSS classes to control the size and shape of the skeleton placeholder (e.g. 'h-4 w-32')."),
});

export const skeletonDescriptor: RegisteredComponent = {
  name: "Skeleton",
  description: "Displays an animated pulsing placeholder block to indicate loading state. Use it to represent content that is being fetched or processed.",
  propsSchema: skeletonSchema as VendoSchema<unknown>,
  source: "host",
};
