/**
 * Generated by `vendo init` — wraps src/components/ui/skeleton.tsx for the Vendo sandbox.
 * Review and edit freely; this file is yours. The wrapper body was LLM-authored:
 * it runs inside the egress-jailed sandbox iframe (F3a CSP), but REVIEW IT like
 * any other generated code before committing.
 */
import { Skeleton } from "../../../src/components/ui/skeleton";
import { skeletonSchema } from "./descriptor";

// Named SkeletonWrapper (not Skeleton) so it never collides with the host import.
export function SkeletonWrapper(props: Record<string, unknown>) {
  const parsed = skeletonSchema.safeParse(props);
  if (!parsed.success) {
    return <div data-testid="vendo-invalid-props">Invalid component props</div>;
  }
  const p = parsed.data;
  return <Skeleton className={p.className} />;
}
