/**
 * Generated by `flowlet init`, then hand-wired for the Cadence integration.
 *
 * Sandbox host bundle entry: this is the ONE bundle the Flowlet stage loads
 * (window.__FLOWLET_HOST__ contract), so it must carry the prewired catalog
 * AND Cadence's registered host components — the stage has no second slot.
 * Mirrors packages/flowlet-components/bundle/entry.ts (OpenUI CSS inlined,
 * theme-wrap hook) and merges in the two Cadence components this integration
 * registers: Badge and ProgressBar (wrappers hand-rewritten for sandbox
 * styling — see the fidelity report). The other six extracted wrappers stay
 * unwired until they get the same treatment: their impls import Tailwind-
 * styled host components, which render unstyled inside the sandbox.
 *
 * NOTE: once the ENG-184 brand-tier branch lands, this hand merge should be
 * replaced by its installFlowletHost() helper (docs/host-components.md there).
 */
import React from "react";
import { createRoot } from "react-dom/client";
import { ThemeProvider } from "@openuidev/react-ui";
import { prewiredImpls } from "@flowlet/components";
import { BadgeWrapper } from "./Badge/impl";
import { ProgressBarWrapper } from "./ProgressBar/impl";
// OpenUI's base stylesheet, inlined as a string (?inline) and injected at
// module eval: the sandbox iframe cannot load external stylesheets (CSP
// default-src 'none'), so the CSS must travel inside the JS artifact.
import openuiCss from "@openuidev/react-ui/index.css?inline";

const openuiStyle = document.createElement("style");
openuiStyle.setAttribute("data-flowlet-openui", "");
openuiStyle.textContent = openuiCss;
document.head.appendChild(openuiStyle);

declare global {
  interface Window {
    __React: typeof React;
    __createRoot: typeof createRoot;
    __FLOWLET_HOST__: Record<string, unknown>;
    __FLOWLET_THEME_WRAP__?: (blob: { mode?: "light" | "dark"; theme?: unknown }, children: unknown) => unknown;
  }
}

window.__React = React;
window.__createRoot = createRoot;
window.__FLOWLET_HOST__ = {
  ...prewiredImpls,
  Badge: BadgeWrapper,
  ProgressBar: ProgressBarWrapper,
};

// Opaque-to-the-stage theme wrapper: the generic runtime mounts this around the
// rendered tree when an init payload carries `componentTheme`. Only this bundle
// knows the OpenUI ThemeProvider shape.
window.__FLOWLET_THEME_WRAP__ = (blob, children) =>
  React.createElement(
    ThemeProvider as never,
    { mode: blob?.mode ?? "light", lightTheme: blob?.theme, darkTheme: blob?.theme } as never,
    children as never,
  );
