/** Generated by `flowlet init`. Builds the host-component sandbox bundle. */
import path from "node:path";
import { fileURLToPath } from "node:url";
import { flowletHostPreset } from "@flowlet/stage/build";

const here = path.dirname(fileURLToPath(import.meta.url));
// Absolute entry: the build must work from any cwd (e.g. the host repo root).
const base = flowletHostPreset({ entry: path.resolve(here, "entry.ts"), version: "0.0.1" });

const config = {
  ...base,
  // This build produces only the sandbox bundle — never copy the host's public/.
  publicDir: false,
  // Host tsconfig path aliases, re-rooted relative to this directory.
  resolve: { alias: { "@": path.resolve(here, "../../src") } },
  // Hand-fixed after extraction: the generated config re-rooted only the entry,
  // not outDir — built from the app root, the bundle landed in the app's dist/.
  build: { ...base.build, outDir: path.resolve(here, "dist") },
};

export default config;
