/**
 * Generated by `flowlet init` — review and edit freely; this file is yours.
 */
import { z } from "zod";
import type { RegisteredComponent, FlowletSchema } from "@flowlet/core";

export const badgeSchema = z.object({
  text: z.string().describe("The text content displayed inside the badge."),
  tone: z.string().optional().describe("Visual tone of the badge: 'neutral', 'positive', or 'negative'."),
});

export const badgeDescriptor: RegisteredComponent = {
  name: "Badge",
  description: "A small pill-shaped label used to highlight status, categories, or counts with semantic tone styling (neutral, positive, or negative). Use it to draw attention to metadata like tags, states, or counts inline with text.",
  propsSchema: badgeSchema as FlowletSchema<unknown>,
  source: "host",
};
