/**
 * Generated by `flowlet init` — wraps src/components/ui/badge.tsx for the Flowlet sandbox.
 * Review and edit freely; this file is yours.
 */
import { Badge } from "../../../src/components/ui/badge";
import { badgeSchema } from "./descriptor";

// Named BadgeWrapper (not Badge) so it never collides with the host import.
export function BadgeWrapper(props: Record<string, unknown>) {
  const parsed = badgeSchema.safeParse(props);
  if (!parsed.success) {
    return <div data-testid="flowlet-invalid-props">Invalid component props</div>;
  }
  const p = parsed.data;
  return <Badge tone={p.tone}>{p.text}</Badge>;
}
