/**
 * Generated by `flowlet init` — wraps src/components/ui/skeleton.tsx for the Flowlet sandbox.
 * Review and edit freely; this file is yours. The wrapper body was LLM-authored:
 * it runs inside the egress-jailed sandbox iframe (F3a CSP), but REVIEW IT like
 * any other generated code before committing.
 */
import { SkeletonText } from "../../../src/components/ui/skeleton";
import { skeletonTextSchema } from "./descriptor";

// Named SkeletonTextWrapper (not SkeletonText) so it never collides with the host import.
export function SkeletonTextWrapper(props: Record<string, unknown>) {
  const parsed = skeletonTextSchema.safeParse(props);
  if (!parsed.success) {
    return <div data-testid="flowlet-invalid-props">Invalid component props</div>;
  }
  const p = parsed.data;
  return <SkeletonText lines={p.lines} className={p.className} />;
}
