import { promises as fs } from "node:fs";
import path from "node:path";
import type { LanguageModel } from "ai";
import { initTelemetry, type Telemetry } from "@vendoai/telemetry";
import { detectTarget } from "./detect.js";
import { extractTheme } from "./theme/extract-theme.js";
import { extractTools } from "./tools/extract-tools.js";
import { extractComponents } from "./components/extract-components.js";
import type { ResolveModelDeps } from "@vendoai/server/model";
import { resolveCliModel } from "./llm.js";
import {
  appendProviderKey,
  detectProvider,
  validateKey,
  PROVIDER_ENV_VAR,
  type ValidateKeyDeps,
} from "./keys.js";
import { createInteractor, type Interactor } from "./interact.js";
import { isInteractive } from "./ui.js";
import { renderReport, type InitReport } from "./report.js";
import { writeGenerated } from "./fsx.js";
import { inspectVendoState, type VendoState } from "./state.js";
import { wireNextApp, renderWiring } from "./next-wiring.js";
import { installLocalVendoPackages, type LocalVendoInstallSummary } from "./local-pack.js";
import { CLI_VERSION } from "./version.js";

export interface InitOptions {
  targetDir: string;
  skipLlm: boolean;
  force: boolean;
  /**
   * Skip every interactive prompt (today: the provider-key prompt). Forces
   * non-interactive key resolution — env / `.env.local` only, never a prompt.
   */
  yes?: boolean;
  /** Pack local Vendo workspace packages into the host app's vendor/ dir. */
  localVendoDir?: string;
  /**
   * Which command drives this pipeline. `"refresh"` — and, implicitly, a plain
   * `init` re-run on an already-wired app — runs in *catch-up* mode for
   * presentation and deterministic gap-filling, but keeps an existing component
   * catalog stable. Use `vendo refresh` when you want to discover additional
   * component candidates after the app has grown. Defaults to `"init"`.
   * `vendo refresh` sets it to `"refresh"`.
   */
  mode?: "init" | "refresh";

  // ---- test seams below this line ------------------------------------------
  // Everything above maps 1:1 to a CLI flag/argument; everything below exists
  // so tests can inject fakes (models, prompts, network, telemetry) and is
  // omitted in production. Keep new options on the right side of this line.

  /** test seam — pass null to force LLM-off, a mock to avoid the network */
  model?: LanguageModel | null;
  /**
   * Whether the run may open interactive prompts. Defaults to `ui.ts`'s
   * `isInteractive()` (TTY && !CI); `--yes` forces it off regardless. Tests
   * set it explicitly to drive (or suppress) the key-prompt path.
   */
  interactive?: boolean;
  /** test seam — the masked-input prompt seam (a fake avoids a real terminal). */
  interactor?: Interactor;
  /** test seam — `validateKey` deps: inject a model/import to skip the network. */
  keyValidateDeps?: ValidateKeyDeps;
  /** test seam — model-resolution deps (optional-peer import) for `cliModel`. */
  modelResolveDeps?: ResolveModelDeps;
  /** test seam — telemetry wiring overrides; omit in production for real env/key */
  telemetry?: {
    home?: string;
    posthogKey?: string;
    env?: Record<string, string | undefined>;
    fetchImpl?: typeof fetch;
  };
}

type InitFailedStep = "theme" | "tools" | "components" | "wiring";

function localPackageResolutionField(summary: LocalVendoInstallSummary): string {
  if (summary.packageManager === "pnpm") return "pnpm.overrides";
  if (summary.packageManager === "npm") return "overrides";
  return "resolutions";
}

function noopTelemetry(): Telemetry {
  return {
    async track() {},
  };
}

function initRunTelemetry(opts: InitOptions): Telemetry {
  try {
    return initTelemetry({
      version: CLI_VERSION,
      runtime: false,
      home: opts.telemetry?.home,
      posthogKey: opts.telemetry?.posthogKey ?? process.env.VENDO_POSTHOG_KEY,
      env: opts.telemetry?.env ?? process.env,
      fetchImpl: opts.telemetry?.fetchImpl,
    });
  } catch {
    return noopTelemetry();
  }
}

function readmeSource(report: InitReport): string {
  return `# .vendo/ — generated by \`vendo init\`

Everything in this directory is **yours to edit and commit**. \`vendo init\` never
modifies existing code; re-running it only fills gaps and never overwrites these
files unless you pass \`--force\`. (One exception: \`components/entry.ts\` is a
generated index and is regenerated whenever a new wrapper is added — hand-edit
the wrapper files, not it.)

- \`theme.json\` — BrandTokens consumed by the Vendo sandbox theme injection.
  One mode per file today${report.theme?.hasDarkVariant ? " (dark-scoped variables were detected but not emitted — open schema question)" : ""}.
- \`tools.json\` — your API surface as tool descriptors. \`annotations\` uses MCP-style
  hints: \`readOnlyHint: false\` means mutating, \`destructiveHint: true\` means dangerous
  (approval-gated by the Vendo policy layer). \`inputSchema\` convention: path/query
  params are top-level properties; a JSON request body is the \`body\` property.
  \`events\` declares host event types usable as automation triggers (empty until you add them).
- \`components/\` — descriptor + sandbox wrapper pairs around your components, plus an
  \`entry.ts\`/\`vite.config.mts\` that build them into a sandbox bundle with
  \`vendoHostPreset\`. Wrapper bodies are LLM-authored code: they execute only
  inside the egress-jailed sandbox iframe, but review them like any generated
  code before committing. Wiring the bundle into a running Vendo host is
  separate (see ENG-186/ENG-202).

Safety defaults: route-scanned tools are ALL marked \`mutating: true\` (the scan
is LLM-read code and must not grant auto-allow); GETs with side-effect-shaped
names are marked mutating even from OpenAPI. Relax annotations here by hand
after review — this file is the reviewable source of truth.

## Events

Events are named payload contracts that automations can use as triggers. Add
them to the \`events\` array in \`tools.json\`:

\`\`\`json
{
  "version": 1,
  "tools": [],
  "events": [
    {
      "name": "charge.posted",
      "description": "A card charge posted to an account.",
      "payloadSchema": {
        "type": "object",
        "required": ["chargeId", "accountId", "amountCents"],
        "properties": {
          "chargeId": { "type": "string" },
          "accountId": { "type": "string" },
          "amountCents": { "type": "integer" },
          "postedAt": { "type": "string", "format": "date-time" }
        }
      }
    }
  ]
}
\`\`\`

Ingest events with \`ingestVendoEvent()\` or \`POST /api/vendo/events/ingest\`.
Producers can push at the source, relay webhooks, or poll upstream systems; all
three feed the same Vendo ingest path.

\`vendo publish\` uploads tools.json to the Vendo registry — stubbed until the
registry ships (ENG-198). Embedded hosts read this directory from disk.
`;
}

function errorMessage(err: unknown): string {
  return err instanceof Error ? err.message : String(err);
}

/** The `--force` warning: list every existing generated file about to be overwritten. */
async function forceOverwriteWarning(targetDir: string, state: VendoState): Promise<string | null> {
  const overwrites: string[] = [];
  if (state.theme.exists) overwrites.push(".vendo/theme.json");
  if (state.tools.exists) overwrites.push(".vendo/tools.json");
  for (const name of state.components) overwrites.push(`.vendo/components/${name}/`);
  for (const rel of [".vendo/components/entry.ts", ".vendo/components/vite.config.mts", ".vendo/README.md"]) {
    const present = await fs.access(path.join(targetDir, rel)).then(() => true, () => false);
    if (present) overwrites.push(rel);
  }
  if (overwrites.length === 0) return null;
  return [
    "--force: regenerating .vendo/ — these existing files will be OVERWRITTEN (hand-edits will be lost):",
    ...overwrites.map((f) => `  ${f}`),
  ].join("\n");
}

const COACHING_LINE = [
  "",
  "No provider API key found, so the LLM steps were skipped (route scan, component discovery).",
  "Add ANTHROPIC_API_KEY, OPENAI_API_KEY, or GOOGLE_GENERATIVE_AI_API_KEY and re-run `vendo init` —",
  "re-running only fills gaps; it never overwrites your edits.",
].join("\n");

const KEY_PROMPT_MESSAGE =
  "Paste a provider API key to enable the LLM steps (Anthropic sk-ant-…, OpenAI sk-…, or Google AIza…) — or press Enter to skip";

/** Telemetry outcome of the key-prompt step. `not-shown`: never prompted
 *  (key already present, `--yes`, non-interactive, or `--skip-llm`). */
type KeyPromptOutcome = "provided" | "skipped" | "invalid" | "not-shown";

interface KeyPromptResult {
  /** The usable model built from a saved+validated key, else null (deterministic). */
  model: LanguageModel | null;
  outcome: KeyPromptOutcome;
  /** A key was written to `.env.local` (valid, or shape-detected-but-unverifiable). */
  saved: boolean;
}

/**
 * The interactive provider-key prompt. Loops on paste: a valid key is saved to
 * `.env.local` and resolved into a usable model; a rejected or unrecognized key
 * re-prompts; an unreachable provider warns and drops to deterministic mode
 * (key NOT saved — say nothing about the key's validity); a missing optional
 * peer saves the shape-detected key anyway (it can't be verified without the
 * package) and prints the install hint. Enter or Ctrl-C at any point skips into
 * deterministic mode. Never logs or echoes the pasted key.
 *
 * Termination: the `for (;;)` relies on the interactor eventually yielding an
 * empty/null answer — the real clack prompt always can (Enter or Ctrl-C), but a
 * test fake that keeps replaying a rejected key would loop forever, so fakes
 * must end their scripts with "" or null.
 */
async function promptForKey(
  targetDir: string,
  interactor: Interactor,
  opts: InitOptions,
): Promise<KeyPromptResult> {
  let sawRejection = false;
  const skip = (): KeyPromptResult => ({
    model: null,
    outcome: sawRejection ? "invalid" : "skipped",
    saved: false,
  });

  for (;;) {
    const raw = await interactor.maskedInput({ message: KEY_PROMPT_MESSAGE });
    const key = raw?.trim() ?? "";
    // Enter (empty) or Ctrl-C (null) → skip into deterministic mode.
    if (key === "") return skip();

    const provider = detectProvider(key);
    if (!provider) {
      sawRejection = true;
      console.error(
        "That doesn't look like a supported key. Expected an Anthropic (sk-ant-…), OpenAI (sk-…), or Google (AIza…) key. Try again, or press Enter to skip.",
      );
      continue;
    }

    const validation = await validateKey(provider, key, opts.keyValidateDeps);
    if (validation.status === "valid") {
      await appendProviderKey(targetDir, provider, key);
      const model = await resolveCliModel(targetDir, opts.modelResolveDeps);
      console.log(`✓ ${PROVIDER_ENV_VAR[provider]} saved to .env.local and verified.`);
      return { model, outcome: "provided", saved: true };
    }
    if (validation.status === "invalid") {
      sawRejection = true;
      console.error(`That key was rejected (${validation.reason}). Try again, or press Enter to skip.`);
      continue;
    }
    if (validation.status === "unavailable") {
      // Can't validate without the optional peer, but the shape is recognized —
      // save it so a re-run (after installing the package) picks it up.
      await appendProviderKey(targetDir, provider, key);
      const pkg = validation.reason.replace(/^install\s+/, "");
      console.log(
        `${PROVIDER_ENV_VAR[provider]} saved to .env.local, but it couldn't be verified: ${pkg} isn't installed. Run \`pnpm add ${pkg}\`, then re-run \`vendo init\`.`,
      );
      return { model: null, outcome: "provided", saved: true };
    }
    // unreachable: do NOT save; the failure says nothing about the key.
    console.error(`Couldn't verify the key: ${validation.reason}. Re-run \`vendo init\` when back online.`);
    return skip();
  }
}

export async function runInit(opts: InitOptions): Promise<number> {
  const startedAt = Date.now();
  const targetDir = path.resolve(opts.targetDir);
  // May this run open interactive prompts (key paste, catalog picker)? A real
  // TTY that isn't CI, unless `--yes` forces non-interactive. Tests set
  // `opts.interactive` explicitly.
  const interactive = (opts.interactive ?? isInteractive()) && !opts.yes;
  const info = await detectTarget(targetDir);
  const t = initRunTelemetry(opts);
  const framework = info.framework;
  await t.track("init_started", { framework });

  // What already exists drives every skip/extract decision below: re-runs are
  // additive (fill gaps, never clobber); --force regenerates but warns first.
  const state = await inspectVendoState(targetDir);

  // Catch-up mode: an explicit `vendo refresh`, OR a plain `init` re-run on an
  // already-wired app. The presentation is the same either way: first-run
  // onboarding text is noise for an app already set up, so the "Next steps:"
  // block is suppressed and idempotent wiring is verified silently rather than
  // re-explained. Component discovery is deliberately stricter for plain init:
  // once a catalog exists, re-running init leaves it byte-stable; refresh is the
  // command that offers newly discovered wrappers.
  //
  // NOTE: `state.wired.wired` is read from PRE-wiring state (before wireNextApp
  // below actually installs the route/root). This is deliberate — it must stay
  // computed here so a genuine first run (unwired at this point) still onboards.
  // Do not move this after wireNextApp: that would flip every first run to
  // catch-up and silently suppress the onboarding block.
  const catchUp = opts.mode === "refresh" || state.wired.wired;
  const keepExistingComponentCatalog =
    catchUp && (opts.mode ?? "init") === "init" && state.components.length > 0 && !opts.force;
  const stableInitRerun =
    keepExistingComponentCatalog && state.theme.status === "real" && state.tools.status === "real";

  let model: LanguageModel | null;
  let keyPrompt: KeyPromptOutcome = "not-shown";
  let keySaved = false;
  try {
    if (stableInitRerun) {
      model = null;
    } else if (opts.skipLlm) {
      model = null;
    } else if (opts.model !== undefined) {
      // Test seam: an explicit model (or explicit null) bypasses self-resolution
      // and the prompt entirely — the caller has already decided.
      model = opts.model;
    } else {
      // Resolve from env + <targetDir>/.env.local (a hand-added key there is
      // picked up without exporting it into the shell).
      model = await resolveCliModel(targetDir, opts.modelResolveDeps);
      // No key found: when we can prompt (interactive, not --yes), offer to
      // paste one; otherwise fall through to deterministic mode + coaching.
      if (model === null && interactive) {
        const result = await promptForKey(targetDir, opts.interactor ?? createInteractor(), opts);
        model = result.model;
        keyPrompt = result.outcome;
        keySaved = result.saved;
      }
    }
  } catch (err) {
    // A provider was explicitly configured (a key or VENDO_MODEL/
    // VENDO_CLI_MODEL) but resolution failed (unknown provider prefix, or a
    // configured provider's optional peer package isn't installed) — surface
    // the actionable error instead of an unhandled rejection or a silent
    // fallback to deterministic mode.
    console.error(err instanceof Error ? err.message : String(err));
    await t.track("init_failed", { framework, failedStep: "tools" });
    return 1;
  }

  // A run without a usable provider key still succeeds in deterministic mode; it
  // ends with a coaching line (add a key, re-run — init only fills gaps). A key
  // the prompt saved but couldn't verify (missing optional peer) prints its own
  // install hint instead, so the generic coaching line is suppressed there.
  const noProviderKey = model === null && !opts.skipLlm && !keySaved && !stableInitRerun;
  if (opts.force) {
    const warning = await forceOverwriteWarning(targetDir, state);
    if (warning) console.log(warning);
  }

  const report: InitReport = {
    info,
    theme: null,
    tools: null,
    components: null,
    llmSkipped: model === null,
    llmSkippedReason: model === null
      ? (
        stableInitRerun
          ? "already initialized"
          : opts.skipLlm ? "--skip-llm" : "no ANTHROPIC_API_KEY/OPENAI_API_KEY/GOOGLE_GENERATIVE_AI_API_KEY"
      )
      : undefined,
  };
  let failedStep: InitFailedStep = "theme";
  try {
    failedStep = "theme";
    if (state.theme.status === "real" && !opts.force) {
      report.keptTheme = true;
    } else {
      // The wiring-written default-brand stub carries no developer content —
      // extraction may replace it in place (mirrors the tools fallback rule).
      report.theme = await extractTheme(targetDir, info, {
        force: opts.force || state.theme.status === "default-stub",
      });
    }
    failedStep = "tools";
    if (state.tools.status === "real" && !opts.force) {
      report.keptTools = true;
    } else {
      // The wiring-written empty fallback ({version:1, tools:[], events:[]})
      // carries no developer content — extraction may replace it in place.
      const toolOpts = { force: opts.force || state.tools.status === "empty-fallback" };
      try {
        report.tools = await extractTools(targetDir, info, model, toolOpts);
      } catch (err) {
        // LLM route scanning is optional. If the provider rejects, warns via an
        // exception, or otherwise fails, keep the deterministic init path moving
        // so Next wiring still happens and the developer gets a reviewable diff.
        // Deterministic OpenAPI conversion errors still fail init normally.
        if (!model || info.openapiPath) throw err;
        const message = errorMessage(err);
        console.error(`LLM-assisted route scan failed; continuing without LLM: ${message}`);
        model = null;
        report.llmSkipped = true;
        report.llmSkippedReason = "LLM-assisted route scan failed; continuing without LLM";
        report.tools = await extractTools(targetDir, info, null, toolOpts);
        report.tools.errors.unshift(`LLM-assisted route scan failed (${message}) — continuing without LLM`);
      }
    }
    if (keepExistingComponentCatalog) {
      report.keptComponents = true;
    } else if (model) {
      failedStep = "components";
      try {
        // Only unwrapped candidates are analyzed/proposed; existing wrapper
        // dirs are untouched (unless --force regenerates everything). The
        // interactive catalog picker (a single batch proposal + checkbox
        // select) runs only when this run may prompt; otherwise every
        // candidate is generated.
        report.components = await extractComponents(
          targetDir,
          model,
          {
            force: opts.force,
            interactive,
            interactor: interactive ? opts.interactor ?? createInteractor() : undefined,
          },
          state.components,
        );
      } catch (err) {
        const message = errorMessage(err);
        console.error(`LLM-assisted component discovery failed; continuing without generated components: ${message}`);
        report.components = {
          candidates: 0,
          offered: 0,
          written: [],
          excluded: [],
          failed: [{ file: "(component discovery)", error: message }],
        };
      }
    }
    // The README is generated documentation, kept when present (it tells the
    // developer the directory is theirs to edit).
    await writeGenerated(path.join(targetDir, ".vendo/README.md"), readmeSource(report), {
      force: opts.force,
      ifExists: "skip",
    });
  } catch (err) {
    console.error(errorMessage(err));
    await t.track("init_failed", { framework, failedStep });
    return 1;
  }
  console.log(renderReport(report));
  // The install codemod (Next.js App Router): route handler, provider wrap,
  // .env.example, sandbox assets, dependency. Fail-open by design — anything
  // uncertain is skipped and reported, never guessed.
  let wiringInstalled = false;
  let localInstall: LocalVendoInstallSummary | null = null;
  try {
    failedStep = "wiring";
    // wireNextApp is idempotent — on a catch-up run it verifies/repairs the
    // existing wiring. It's the mechanism that keeps wiring intact, so it always
    // runs; only how we report it changes.
    const wiring = await wireNextApp(targetDir, info, { force: opts.force });
    wiringInstalled = wiring !== null;
    if (catchUp) {
      // Catch-up: don't re-explain wiring. Surface only genuine follow-ups
      // (manual TODOs) or actual repairs (files written/edited); the "already
      // exists / already wired" skips a re-run produces are noise here. Clean
      // wiring gets a single verified line instead of the full skip dump.
      const changed = wiring !== null
        && (wiring.written.length > 0 || wiring.edited.length > 0 || wiring.manual.length > 0);
      if (changed) {
        // Drop the idempotent "already exists" skips; show only the genuine
        // repair/TODO lines. `changed` guarantees at least one such line.
        const rendered = renderWiring(wiring, { omitSkips: true });
        if (rendered) console.log(rendered);
      } else if (wiring !== null) {
        console.log("wiring: verified");
      }
    } else {
      const rendered = renderWiring(wiring);
      if (rendered) console.log(rendered);
    }
    if (opts.localVendoDir) {
      localInstall = await installLocalVendoPackages(targetDir, opts.localVendoDir);
      console.log(
        [
          "local packages:",
          `  wrote  ${localInstall.packages.length} local vendo tarballs + fluidkit into ${path.relative(targetDir, localInstall.vendorDir)}`,
          `  edited package.json with file:vendor/* dependencies and ${localPackageResolutionField(localInstall)}`,
          `  next  run ${localInstall.installCommand}`,
        ].join("\n"),
      );
    }
  } catch (err) {
    console.error(`init wiring failed (review \`git diff\` — writes are individually atomic): ${err instanceof Error ? err.message : String(err)}`);
    await t.track("init_failed", { framework, failedStep });
    return 1;
  }
  // First-run onboarding only. Suppressed in catch-up mode (refresh, or an init
  // re-run on an already-wired app): the app is already set up, so "install
  // deps / cp .env.example / npm run dev" is noise.
  if (wiringInstalled && !catchUp) {
    console.log(
      [
        "",
        "Next steps:",
        `  1. ${localInstall ? `run ${localInstall.installCommand}` : "install deps (npm install / pnpm install / yarn install)"}`,
        "  2. cp .env.example .env.local  and paste one provider API key (see comments)",
        "  3. npm run dev — then hit the launcher (or Cmd/Ctrl+K) and ask for a view",
      ].join("\n"),
    );
  }
  if (noProviderKey) console.log(COACHING_LINE);
  await t.track("init_completed", {
    framework,
    provider: model === null ? "none" : "configured",
    llmSkipped: model === null,
    // The key-prompt outcome (never the key/provider-var value): provided /
    // skipped / invalid / not-shown.
    keyPrompt,
    // Which command drove the pipeline — `refresh` delegates to runInit, so
    // both commands emit init_completed; this is how they're distinguished.
    command: opts.mode ?? "init",
    // Catalog picker: offered = the FILTERED set shown to the picker (unwrapped
    // -only on re-runs, all under --force), accepted = componentCount (written
    // wrappers). Deterministic (no-model) runs never run the picker → 0.
    componentsOffered: report.components?.offered ?? 0,
    componentCount: report.components?.written.length ?? 0,
    toolCount: report.tools?.toolCount ?? 0,
    durationMs: Date.now() - startedAt,
  });
  return 0;
}
