import path from "node:path";
import type { LanguageModel } from "ai";
import { initTelemetry, type Telemetry } from "@vendoai/telemetry";
import { detectTarget } from "./detect.js";
import { extractTheme } from "./theme/extract-theme.js";
import { extractTools } from "./tools/extract-tools.js";
import { extractComponents } from "./components/extract-components.js";
import { cliModel } from "./llm.js";
import { renderReport, type InitReport } from "./report.js";
import { writeGenerated } from "./fsx.js";
import { wireNextApp, renderWiring } from "./next-wiring.js";
import { installLocalVendoPackages, type LocalVendoInstallSummary } from "./local-pack.js";

export interface InitOptions {
  targetDir: string;
  skipLlm: boolean;
  force: boolean;
  /** Pack local Vendo workspace packages into the host app's vendor/ dir. */
  localVendoDir?: string;
  /** test seam — pass null to force LLM-off, a mock to avoid the network */
  model?: LanguageModel | null;
  /** test seam — telemetry wiring overrides; omit in production for real env/key */
  telemetry?: {
    home?: string;
    posthogKey?: string;
    env?: Record<string, string | undefined>;
    fetchImpl?: typeof fetch;
  };
}

type InitFailedStep = "theme" | "tools" | "components" | "wiring";

function noopTelemetry(): Telemetry {
  return {
    async track() {},
  };
}

function initRunTelemetry(opts: InitOptions): Telemetry {
  try {
    return initTelemetry({
      version: "0.0.0",
      runtime: false,
      home: opts.telemetry?.home,
      posthogKey: opts.telemetry?.posthogKey ?? process.env.VENDO_POSTHOG_KEY,
      env: opts.telemetry?.env ?? process.env,
      fetchImpl: opts.telemetry?.fetchImpl,
    });
  } catch {
    return noopTelemetry();
  }
}

function readmeSource(report: InitReport): string {
  return `# .vendo/ — generated by \`vendo init\`

Everything in this directory is **yours to edit and commit**. \`vendo init\` never
modifies existing code; re-running it refuses to overwrite these files unless you
pass \`--force\`.

- \`theme.json\` — BrandTokens consumed by the Vendo sandbox theme injection.
  One mode per file today${report.theme?.hasDarkVariant ? " (dark-scoped variables were detected but not emitted — open schema question)" : ""}.
- \`tools.json\` — your API surface as tool descriptors. \`annotations\` uses MCP-style
  hints: \`readOnlyHint: false\` means mutating, \`destructiveHint: true\` means dangerous
  (approval-gated by the Vendo policy layer). \`inputSchema\` convention: path/query
  params are top-level properties; a JSON request body is the \`body\` property.
  \`events\` declares host event types usable as automation triggers (empty until you add them).
- \`components/\` — descriptor + sandbox wrapper pairs around your components, plus an
  \`entry.ts\`/\`vite.config.mts\` that build them into a sandbox bundle with
  \`vendoHostPreset\`. Wrapper bodies are LLM-authored code: they execute only
  inside the egress-jailed sandbox iframe, but review them like any generated
  code before committing. Wiring the bundle into a running Vendo host is
  separate (see ENG-186/ENG-202).

Safety defaults: route-scanned tools are ALL marked \`mutating: true\` (the scan
is LLM-read code and must not grant auto-allow); GETs with side-effect-shaped
names are marked mutating even from OpenAPI. Relax annotations here by hand
after review — this file is the reviewable source of truth.

## Events

Events are named payload contracts that automations can use as triggers. Add
them to \`tools.json\` beside your tools:

\`\`\`json
{
  "name": "charge.posted",
  "description": "A card charge posted to an account.",
  "payloadSchema": {
    "type": "object",
    "required": ["chargeId", "accountId", "amountCents"],
    "properties": {
      "chargeId": { "type": "string" },
      "accountId": { "type": "string" },
      "amountCents": { "type": "integer" },
      "postedAt": { "type": "string", "format": "date-time" }
    }
  }
}
\`\`\`

Producers can push at the source, relay webhooks, or poll upstream systems; all
three feed the same Vendo ingest path.

\`vendo publish\` uploads tools.json to the Vendo registry — stubbed until the
registry ships (ENG-198). Embedded hosts read this directory from disk.
`;
}

export async function runInit(opts: InitOptions): Promise<number> {
  const startedAt = Date.now();
  const targetDir = path.resolve(opts.targetDir);
  const info = await detectTarget(targetDir);
  const t = initRunTelemetry(opts);
  const framework = info.framework;
  await t.track("init_started", { framework });

  let model: LanguageModel | null;
  try {
    model = opts.skipLlm ? null : opts.model !== undefined ? opts.model : await cliModel();
  } catch (err) {
    // A provider was explicitly configured (a key or VENDO_MODEL/
    // VENDO_CLI_MODEL) but resolution failed (unknown provider prefix, or a
    // configured provider's optional peer package isn't installed) — surface
    // the actionable error instead of an unhandled rejection or a silent
    // fallback to deterministic mode.
    console.error(err instanceof Error ? err.message : String(err));
    await t.track("init_failed", { framework, failedStep: "tools" });
    return 1;
  }

  const report: InitReport = { info, theme: null, tools: null, components: null, llmSkipped: model === null };
  let failedStep: InitFailedStep = "theme";
  try {
    failedStep = "theme";
    report.theme = await extractTheme(targetDir, info, opts);
    failedStep = "tools";
    report.tools = await extractTools(targetDir, info, model, opts);
    if (model) {
      failedStep = "components";
      report.components = await extractComponents(targetDir, model, opts);
    }
    await writeGenerated(path.join(targetDir, ".vendo/README.md"), readmeSource(report), opts);
  } catch (err) {
    console.error(err instanceof Error ? err.message : String(err));
    await t.track("init_failed", { framework, failedStep });
    return 1;
  }
  console.log(renderReport(report));

  // The install codemod (Next.js App Router): route handler, provider wrap,
  // .env.example, sandbox assets, dependency. Fail-open by design — anything
  // uncertain is skipped and reported, never guessed.
  let wiringInstalled = false;
  let localInstall: LocalVendoInstallSummary | null = null;
  try {
    failedStep = "wiring";
    const wiring = await wireNextApp(targetDir, info, { force: opts.force });
    const rendered = renderWiring(wiring);
    if (rendered) console.log(rendered);
    wiringInstalled = wiring !== null;
    if (opts.localVendoDir) {
      localInstall = await installLocalVendoPackages(targetDir, opts.localVendoDir);
      console.log(
        [
          "local packages:",
          `  wrote  ${localInstall.packages.length} @vendoai tarballs + fluidkit into ${path.relative(targetDir, localInstall.vendorDir)}`,
          `  edited package.json with file:vendor/* dependencies and ${localInstall.packageManager === "pnpm" ? "pnpm.overrides" : "overrides"}`,
          `  next  run ${localInstall.installCommand}`,
        ].join("\n"),
      );
    }
  } catch (err) {
    console.error(`init wiring failed (review \`git diff\` — writes are individually atomic): ${err instanceof Error ? err.message : String(err)}`);
    await t.track("init_failed", { framework, failedStep });
    return 1;
  }
  if (wiringInstalled) {
    console.log(
      [
        "",
        "Next steps:",
        `  1. ${localInstall ? `run ${localInstall.installCommand}` : "install deps (npm install / pnpm install)"}`,
        "  2. cp .env.example .env.local  and paste one provider API key (see comments)",
        "  3. npm run dev — then hit the launcher (or Cmd/Ctrl+K) and ask for a view",
      ].join("\n"),
    );
  }
  await t.track("init_completed", {
    framework,
    provider: model === null ? "none" : "configured",
    llmSkipped: model === null,
    componentCount: report.components?.written.length ?? 0,
    toolCount: report.tools?.toolCount ?? 0,
    durationMs: Date.now() - startedAt,
  });
  return 0;
}
