/**
 * The Next.js (App Router) wiring codemod — the shadcn/next-auth-style half of
 * `vendo init`. Writes the pieces a host app needs to run Vendo:
 *
 *   1. `app/api/vendo/[...path]/route.ts` — `createVendoHandler()`
 *   2. `app/vendo-root.tsx` — client wrapper importing `.vendo/` JSON
 *   3. root layout edit — wraps `{children}` with the wrapper (idempotent)
 *   4. `instrumentation.ts` (or `src/instrumentation.ts`) — boots the
 *      automation scheduler via `startVendoScheduler()` in the Node.js
 *      runtime
 *   5. `.env.example` — capability-additive keys + storage/scheduler docs
 *   6. `public/vendo/` — sandbox runtime assets (React shim + catalog bundle)
 *   7. `package.json` — adds `@vendoai/next` to dependencies
 *
 * SAFETY CONTRACT: never break existing code. Every step that cannot proceed
 * with certainty (unrecognizable layout, ambiguous `{children}`, missing app
 * dir) is SKIPPED and reported with exact manual instructions instead of
 * guessing. All edits are plain files reviewable in one `git diff`.
 */
import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import ts from "typescript";
import type { FrameworkInfo } from "./detect.js";

export interface WiringSummary {
  /** Files created. */
  written: string[];
  /** Files edited in place. */
  edited: string[];
  /** Steps intentionally not performed, with why. */
  skipped: Array<{ step: string; reason: string }>;
  /** Manual follow-ups the developer must do (printed at the end). */
  manual: string[];
}

async function exists(p: string): Promise<boolean> {
  return fs.access(p).then(() => true, () => false);
}

async function readIf(p: string): Promise<string | null> {
  try {
    return await fs.readFile(p, "utf8");
  } catch {
    return null;
  }
}

export const VENDO_TRANSPILE_PACKAGES = [
  "@vendoai/next",
  "@vendoai/shell",
  "@vendoai/react",
  "@vendoai/components",
  "@vendoai/core",
  "@vendoai/runtime",
  "@vendoai/server",
  "@vendoai/store",
  "@vendoai/stage",
] as const;

const NEXT_SERVER_EXTERNAL_PACKAGES = ["@electric-sql/pglite"] as const;
const PGLITE_DEPENDENCY = "@electric-sql/pglite";
const PGLITE_VERSION = "^0.2.0";

/**
 * Default-brand theme stub written by wiring step 0 when extraction produced
 * no theme.json (the vendo-root wrapper imports it, so it must exist).
 * Exported as the single source of truth for state inspection: a theme.json
 * still deep-equal to this carries no developer content, so additive re-runs
 * may re-extract over it (see state.ts / init.ts).
 */
export const DEFAULT_THEME_STUB = {
  version: 1,
  accent: "#0A7CFF",
  background: "#FFFFFF",
  surface: "#F5F7FA",
  text: "#111418",
  mutedText: "#5B6470",
  fontFamily: "system-ui, -apple-system, Segoe UI, Roboto, sans-serif",
  radius: 8,
  mode: "light",
};

/** Locate the App Router directory (`app/` or `src/app/`) with a root layout. */
export async function findAppDir(
  targetDir: string,
): Promise<{ appDir: string; layoutFile: string } | null> {
  for (const rel of ["app", "src/app"]) {
    const appDir = path.join(targetDir, rel);
    for (const name of ["layout.tsx", "layout.jsx", "layout.js"]) {
      const layoutFile = path.join(appDir, name);
      if (await exists(layoutFile)) return { appDir, layoutFile };
    }
  }
  return null;
}

/** Title-case the package.json name for a friendly default product name. */
export function productNameFrom(pkgName: unknown): string {
  if (typeof pkgName !== "string" || pkgName.length === 0) return "Assistant";
  const base = pkgName.split("/").pop() ?? pkgName;
  return base
    .split(/[-_.]+/)
    .filter(Boolean)
    .map((w) => (w[0]?.toUpperCase() ?? "") + w.slice(1))
    .join(" ");
}

const ROUTE_SOURCE = `/**
 * All Vendo endpoints (chat, action, integrations, capabilities, tick) are
 * served by this one catch-all. Generated by \`vendo init\` — safe to edit;
 * pass options to createVendoHandler() to customize (model, policy, tools).
 */
import { createVendoHandler } from "@vendoai/next";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export const { GET, POST } = createVendoHandler();
`;

function rootSource(opts: { ts: boolean; vendoRel: string; productName: string }): string {
  const typeImport = opts.ts ? `import type { ReactNode } from "react";\n` : "";
  const propsSig = opts.ts ? `{ children }: { children: ReactNode }` : `{ children }`;
  return `"use client";

/**
 * The app's Vendo provider, generated by \`vendo init\`. Wraps the root
 * layout's children so every page gets the assistant overlay (Cmd/Ctrl+K or
 * the launcher pill). Theme and tools come from .vendo/ — edit those files,
 * not this one, to change brand or API surface.
 */
import { VendoRoot } from "@vendoai/next/client";
${typeImport}import theme from "${opts.vendoRel}/theme.json";
import tools from "${opts.vendoRel}/tools.json";

export function AppVendoRoot(${propsSig}) {
  return (
    <VendoRoot theme={theme} tools={tools} productName="${opts.productName}">
      {children}
    </VendoRoot>
  );
}
`;
}

const ENV_EXAMPLE = `# Vendo — capability-additive keys (add what you need, restart dev server)
#
# REQUIRED for chat + generated UI: set ONE of these three provider keys.
ANTHROPIC_API_KEY=
# OPENAI_API_KEY=
# GOOGLE_GENERATIVE_AI_API_KEY=

# OPTIONAL: unlocks integrations (Gmail, Slack, ...) via Composio OAuth.
# Without it the integrations UI stays hidden — nothing breaks.
COMPOSIO_API_KEY=

# OPTIONAL: OPENAI_API_KEY (above) additionally unlocks the voice capability
# flag — detected only, no voice UX ships yet.

# OPTIONAL: override the model Vendo uses. Accepts "provider/model" (e.g.
# "openai/gpt-5.5-mini") or a bare model id applied to whichever provider key
# is set above. VENDO_MODEL is the shared override; VENDO_CLI_MODEL (set
# only for \`vendo init\`) takes precedence over it.
# VENDO_MODEL=
`;

const STORAGE_ENV = `# Vendo — durable storage + automation scheduler (all optional; unset
# values fall back to zero-config embedded storage, see docs/persistence-and-deploy.md)
#
# OPTIONAL: Postgres connection string for threads/vendos/automations/decisions.
# Unset uses an embedded PGlite database — zero-config, good for local dev and
# single-instance deploys, not for serverless/multi-instance ones.
# DATABASE_URL=

# OPTIONAL: directory for the embedded PGlite database (default: .vendo/data).
# Ignored when DATABASE_URL is set.
# VENDO_DATA_DIR=

# OPTIONAL: bearer secret required on POST /api/vendo/tick when driving the
# scheduler from an external cron (see VENDO_SCHEDULER below).
# VENDO_TICK_SECRET=

# OPTIONAL: verifies Composio webhook signatures on POST /api/vendo/webhooks/composio.
# COMPOSIO_WEBHOOK_SECRET=

# OPTIONAL: scheduler mode. Unset (default) auto-starts an in-process timer
# from instrumentation.ts. Set to "external" to disable it and drive ticks
# from an external cron instead (see docs/persistence-and-deploy.md).
# VENDO_SCHEDULER=
`;

const INSTRUMENTATION_SOURCE = `/**
 * Boots the Vendo automation scheduler when the Next.js server starts in
 * the Node.js runtime. Generated by \`vendo init\` — safe to edit. Set
 * VENDO_SCHEDULER=external to disable the in-process timer and drive ticks
 * from an external cron instead (see docs/persistence-and-deploy.md).
 */
export async function register() {
  if (process.env.NEXT_RUNTIME === "nodejs") {
    const { startVendoScheduler } = await import("@vendoai/next");
    startVendoScheduler();
  }
}
`;

/**
 * Merge the scheduler-boot `register()` into an existing `instrumentation.ts`
 * non-destructively. Returns the merged source, the input unchanged when
 * already wired (idempotent), or `null` when the file already declares its
 * own `register()` — Next.js recognizes only one, so injecting into someone
 * else's function body would require guessing at its shape; the caller falls
 * back to `instrumentation.vendo-example.ts` + a manual step instead.
 */
export function mergeInstrumentation(source: string): string | null {
  const masked = maskLiterals(source);
  if (masked.includes("startVendoScheduler")) return source; // already wired
  if (/\bfunction\s+register\s*\(|\bconst\s+register\s*=/.test(masked)) return null;
  return source.replace(/\n?$/, "\n\n") + INSTRUMENTATION_SOURCE;
}

/**
 * Wrap the single `{children}` expression of the root layout with the
 * generated provider. Returns the edited source, or null when the file cannot
 * be edited with certainty (caller falls back to manual instructions).
 *
 * Targets the standard layout shape (one JSX `{children}` in child position).
 * Known limitation: a `{children}` nested inside a JSX ATTRIBUTE expression
 * (e.g. `<Chrome slot={<b>{children}</b>}>...`) is indistinguishable from a
 * real child by this heuristic and would be wrapped in the wrong place — such
 * exotic layouts should be wired by hand (the whole edit is one reviewable
 * diff). create-next-app and typical provider layouts are handled correctly.
 */
/**
 * Return a copy of `source` with the CONTENTS of string/template literals and
 * comments blanked to spaces (quotes/delimiters kept, lengths and offsets
 * preserved). We locate `{children}` and detect idempotence against THIS
 * masked view so a `{children}` sitting inside a string (`"<b>{children}</b>"`)
 * or a comment (`// rename AppVendoRoot`) can never be matched or mistaken
 * for existing wiring — then splice edits back into the ORIGINAL by offset.
 */
export function maskLiterals(source: string): string {
  const out = source.split("");
  let i = 0;
  const n = source.length;
  const blank = (from: number, to: number) => {
    for (let k = from; k < to && k < n; k++) if (source[k] !== "\n") out[k] = " ";
  };
  while (i < n) {
    const c = source[i];
    const next = source[i + 1];
    if (c === "/" && next === "/") {
      let j = i + 2;
      while (j < n && source[j] !== "\n") j++;
      blank(i, j);
      i = j;
    } else if (c === "/" && next === "*") {
      let j = i + 2;
      while (j < n && !(source[j] === "*" && source[j + 1] === "/")) j++;
      blank(i, Math.min(j + 2, n));
      i = j + 2;
    } else if (c === '"' || c === "'" || c === "`") {
      const quote = c;
      let j = i + 1;
      while (j < n) {
        if (source[j] === "\\") { j += 2; continue; }
        if (source[j] === quote) break;
        j++;
      }
      blank(i + 1, j); // keep the delimiters, blank the interior
      i = j + 1;
    } else {
      i++;
    }
  }
  return out.join("");
}

/**
 * Insert `importStmt` at an ALWAYS-VALID position: immediately after a leading
 * "use client"/"use server" directive if present, else at the very top.
 * (Anchoring after "the last import" is unsafe — a Prettier-wrapped multi-line
 *  import would land the new line INSIDE the brace block.)
 *
 * A directive must remain the FIRST statement, but Next allows comments above
 * it — so skip leading comments/whitespace (found on the masked copy, which has
 * comment CONTENT blanked but delimiters/offsets intact) before checking, then
 * detect the directive on the ORIGINAL at that offset (the mask also blanks the
 * "use client" string interior). Shared by wrapLayoutChildren and the remix
 * anchor splice so both call sites agree byte-for-byte.
 */
export function insertImportAfterDirectives(source: string, importStmt: string): string {
  const headerLen = maskLiterals(source).match(/^\s*/)?.[0].length ?? 0;
  const directive = source.slice(headerLen).match(/^(['"]use [a-z ]+['"];?[^\n]*\n)/);
  if (directive) {
    const end = headerLen + directive[0].length;
    return source.slice(0, end) + importStmt + source.slice(end);
  }
  return importStmt + source;
}

export function wrapLayoutChildren(source: string, componentName = "AppVendoRoot"): string | null {
  const masked = maskLiterals(source);
  // Idempotence: already wired (by us or by hand). Checked against the masked
  // view so an incidental mention in a comment/string doesn't false-positive.
  if (masked.includes('from "./vendo-root"') || masked.includes(`<${componentName}>`)) {
    return source;
  }

  // Candidate `{children}` expressions in real code (not strings/comments),
  // filtered to JSX child position: the preceding non-whitespace char must be
  // `>` (end of an opening tag). This excludes destructured parameters
  // `({ children })` and type annotations.
  const matches = [...masked.matchAll(/\{\s*children\s*\}/g)].filter((m) => {
    const before = masked.slice(0, m.index).trimEnd();
    return before.endsWith(">");
  });
  if (matches.length !== 1) return null; // zero or ambiguous — do not guess

  const match = matches[0]!;
  const start = match.index;
  const original = source.slice(start, start + match[0].length); // exact orig text
  const wrapped =
    source.slice(0, start) +
    `<${componentName}>` +
    original +
    `</${componentName}>` +
    source.slice(start + match[0].length);

  const importStmt = `import { ${componentName} } from "./vendo-root";\n`;
  return insertImportAfterDirectives(wrapped, importStmt);
}

/** Merge `@vendoai/next` into package.json dependencies (format-preserving-ish:
 *  2-space JSON, trailing newline — the npm convention). */
export function addDependency(pkgJson: string, name: string, version: string): string | null {
  let pkg: Record<string, unknown>;
  try {
    pkg = JSON.parse(pkgJson) as Record<string, unknown>;
  } catch {
    return null;
  }
  const deps = (pkg["dependencies"] ?? {}) as Record<string, string>;
  if (deps[name]) return pkgJson; // already present — leave the file alone
  pkg["dependencies"] = Object.fromEntries(
    Object.entries({ ...deps, [name]: version }).sort(([a], [b]) => a.localeCompare(b)),
  );
  return JSON.stringify(pkg, null, 2) + "\n";
}

/** Add `vendo sync` to the app's `prebuild` script (create or extend),
 *  so every production build refreshes the capture + sandbox environment.
 *  Idempotent: never adds a second copy. */
export function addPrebuildSync(pkgJson: string): string | null {
  let pkg: Record<string, unknown>;
  try {
    pkg = JSON.parse(pkgJson) as Record<string, unknown>;
  } catch {
    return null;
  }
  const scripts = (pkg["scripts"] ?? {}) as Record<string, string>;
  const existing = scripts["prebuild"];
  if (existing?.includes("vendo sync")) return pkgJson; // already wired
  scripts["prebuild"] = existing ? `${existing} && vendo sync` : "vendo sync";
  pkg["scripts"] = scripts;
  return JSON.stringify(pkg, null, 2) + "\n";
}

export type NextConfigMergeResult =
  | { kind: "updated"; source: string }
  | { kind: "unchanged"; source: string }
  | { kind: "skipped"; reason: string };

function nextConfigScriptKind(fileName: string): ts.ScriptKind {
  if (fileName.endsWith(".ts")) return ts.ScriptKind.TS;
  if (fileName.endsWith(".tsx")) return ts.ScriptKind.TSX;
  if (fileName.endsWith(".jsx")) return ts.ScriptKind.JSX;
  return ts.ScriptKind.JS;
}

function unwrapConfigExpression(expr: ts.Expression): ts.Expression {
  let cur = expr;
  while (
    ts.isParenthesizedExpression(cur) ||
    ts.isAsExpression(cur) ||
    ts.isSatisfiesExpression(cur) ||
    ts.isTypeAssertionExpression(cur) ||
    ts.isNonNullExpression(cur)
  ) {
    if (ts.isParenthesizedExpression(cur) || ts.isNonNullExpression(cur)) cur = cur.expression;
    else cur = cur.expression;
  }
  return cur;
}

function isModuleExports(expr: ts.Expression): boolean {
  return (
    ts.isPropertyAccessExpression(expr) &&
    expr.name.text === "exports" &&
    ts.isIdentifier(expr.expression) &&
    expr.expression.text === "module"
  );
}

function propertyNameText(name: ts.PropertyName): string | null {
  if (ts.isIdentifier(name) || ts.isStringLiteral(name) || ts.isNumericLiteral(name)) return name.text;
  return null;
}

function lineLeadingIndent(source: string, pos: number): string {
  const lineStart = source.lastIndexOf("\n", Math.max(0, pos - 1)) + 1;
  const m = source.slice(lineStart, pos).match(/^[ \t]*/);
  return m?.[0] ?? "";
}

function visualIndentAt(sf: ts.SourceFile, pos: number): string {
  return " ".repeat(sf.getLineAndCharacterOfPosition(pos).character);
}

function findConfigObject(
  source: string,
  fileName: string,
): { object: ts.ObjectLiteralExpression; sf: ts.SourceFile } | { reason: string } {
  const sf = ts.createSourceFile(
    fileName,
    source,
    ts.ScriptTarget.Latest,
    true,
    nextConfigScriptKind(fileName),
  );
  const objectVars = new Map<string, ts.ObjectLiteralExpression>();
  for (const stmt of sf.statements) {
    if (!ts.isVariableStatement(stmt)) continue;
    for (const decl of stmt.declarationList.declarations) {
      if (!ts.isIdentifier(decl.name) || !decl.initializer) continue;
      const init = unwrapConfigExpression(decl.initializer);
      if (ts.isObjectLiteralExpression(init)) objectVars.set(decl.name.text, init);
    }
  }

  const candidates: ts.ObjectLiteralExpression[] = [];
  let sawConfigExport = false;
  const resolve = (expr: ts.Expression): ts.ObjectLiteralExpression | null => {
    const unwrapped = unwrapConfigExpression(expr);
    if (ts.isObjectLiteralExpression(unwrapped)) return unwrapped;
    if (ts.isIdentifier(unwrapped)) return objectVars.get(unwrapped.text) ?? null;
    return null;
  };

  for (const stmt of sf.statements) {
    if (ts.isExportAssignment(stmt)) {
      sawConfigExport = true;
      const object = resolve(stmt.expression);
      if (object) candidates.push(object);
      continue;
    }
    if (!ts.isExpressionStatement(stmt) || !ts.isBinaryExpression(stmt.expression)) continue;
    const expr = stmt.expression;
    if (expr.operatorToken.kind !== ts.SyntaxKind.EqualsToken || !isModuleExports(expr.left)) continue;
    sawConfigExport = true;
    const object = resolve(expr.right);
    if (object) candidates.push(object);
  }

  if (candidates.length === 1) return { object: candidates[0]!, sf };
  if (candidates.length > 1) return { reason: "multiple plain object config exports found" };
  return {
    reason: sawConfigExport
      ? "config export is not a plain object literal"
      : "no export default or module.exports config object found",
  };
}

type StringArrayProperty =
  | { kind: "present"; property: ts.PropertyAssignment; array: ts.ArrayLiteralExpression; values: string[] }
  | { kind: "absent" }
  | { kind: "skipped"; reason: string };

function inspectStringArrayProperty(
  object: ts.ObjectLiteralExpression,
  propName: string,
): StringArrayProperty {
  let found: ts.ObjectLiteralElementLike | null = null;
  for (const prop of object.properties) {
    if (ts.isSpreadAssignment(prop)) {
      return { kind: "skipped", reason: "config object uses object spread (...)" };
    }
    const name = prop.name ? propertyNameText(prop.name) : null;
    if (prop.name && name === null) {
      return { kind: "skipped", reason: "config object has computed property names" };
    }
    if (name !== propName) continue;
    if (found) return { kind: "skipped", reason: `${propName} is declared more than once` };
    found = prop;
  }
  if (!found) return { kind: "absent" };
  if (!ts.isPropertyAssignment(found)) {
    return { kind: "skipped", reason: `${propName} is not a property assignment` };
  }
  const init = unwrapConfigExpression(found.initializer);
  if (!ts.isArrayLiteralExpression(init)) {
    return { kind: "skipped", reason: `${propName} is not a string array literal` };
  }
  const values: string[] = [];
  for (const element of init.elements) {
    const item = unwrapConfigExpression(element as ts.Expression);
    if (ts.isStringLiteral(item) || ts.isNoSubstitutionTemplateLiteral(item)) {
      values.push(item.text);
      continue;
    }
    return { kind: "skipped", reason: `${propName} contains non-string entries` };
  }
  return { kind: "present", property: found, array: init, values };
}

function mergeValues(existing: readonly string[], required: readonly string[]): string[] {
  const present = new Set(existing);
  return [...existing, ...required.filter((value) => !present.has(value))];
}

function hasEveryValue(existing: readonly string[], required: readonly string[]): boolean {
  const present = new Set(existing);
  return required.every((value) => present.has(value));
}

function renderStringArray(values: readonly string[], propertyIndent: string): string {
  return `[\n${values.map((value) => `${propertyIndent}  ${JSON.stringify(value)},`).join("\n")}\n${propertyIndent}]`;
}

function renderConfigProperty(name: string, values: readonly string[], propertyIndent: string): string {
  return `${propertyIndent}${name}: ${renderStringArray(values, propertyIndent)},`;
}

export function mergeNextConfig(source: string, fileName = "next.config.ts"): NextConfigMergeResult {
  const found = findConfigObject(source, fileName);
  if ("reason" in found) return { kind: "skipped", reason: found.reason };
  const { object, sf } = found;
  const transpile = inspectStringArrayProperty(object, "transpilePackages");
  if (transpile.kind === "skipped") return { kind: "skipped", reason: transpile.reason };
  const external = inspectStringArrayProperty(object, "serverExternalPackages");
  if (external.kind === "skipped") return { kind: "skipped", reason: external.reason };

  const replacements: Array<{ start: number; end: number; text: string }> = [];
  const addedProps: string[] = [];
  const propertyIndent =
    object.properties.length > 0
      ? visualIndentAt(sf, object.properties[0]!.getStart(sf))
      : lineLeadingIndent(source, object.getStart(sf)) + "  ";
  const closeIndent = lineLeadingIndent(source, object.getStart(sf));

  if (transpile.kind === "present") {
    if (!hasEveryValue(transpile.values, VENDO_TRANSPILE_PACKAGES)) {
      replacements.push({
        start: transpile.array.getStart(sf),
        end: transpile.array.getEnd(),
        text: renderStringArray(mergeValues(transpile.values, VENDO_TRANSPILE_PACKAGES), propertyIndent),
      });
    }
  } else {
    addedProps.push(renderConfigProperty("transpilePackages", VENDO_TRANSPILE_PACKAGES, propertyIndent));
  }

  if (external.kind === "present") {
    if (!hasEveryValue(external.values, NEXT_SERVER_EXTERNAL_PACKAGES)) {
      replacements.push({
        start: external.array.getStart(sf),
        end: external.array.getEnd(),
        text: renderStringArray(mergeValues(external.values, NEXT_SERVER_EXTERNAL_PACKAGES), propertyIndent),
      });
    }
  } else {
    addedProps.push(renderConfigProperty("serverExternalPackages", NEXT_SERVER_EXTERNAL_PACKAGES, propertyIndent));
  }

  if (addedProps.length > 0) {
    const closeBrace = object.getEnd() - 1;
    const lastProp = object.properties[object.properties.length - 1];
    let prefix = "\n";
    if (lastProp) {
      const betweenLastPropAndClose = source.slice(lastProp.getEnd(), closeBrace);
      prefix = betweenLastPropAndClose.trimStart().startsWith(",") ? "\n" : ",\n";
    }
    replacements.push({
      start: closeBrace,
      end: closeBrace,
      text: `${prefix}${addedProps.join("\n")}\n${closeIndent}`,
    });
  }

  if (replacements.length === 0) return { kind: "unchanged", source };
  let next = source;
  for (const r of replacements.sort((a, b) => b.start - a.start)) {
    next = next.slice(0, r.start) + r.text + next.slice(r.end);
  }
  return { kind: next === source ? "unchanged" : "updated", source: next };
}

function minimalNextConfigSource(tsConfig: boolean): string {
  const body = [
    "  transpilePackages: [",
    ...VENDO_TRANSPILE_PACKAGES.map((pkg) => `    ${JSON.stringify(pkg)},`),
    "  ],",
    "  serverExternalPackages: [",
    ...NEXT_SERVER_EXTERNAL_PACKAGES.map((pkg) => `    ${JSON.stringify(pkg)},`),
    "  ],",
  ].join("\n");
  if (tsConfig) {
    return `import type { NextConfig } from "next";\n\nconst nextConfig: NextConfig = {\n${body}\n};\n\nexport default nextConfig;\n`;
  }
  return `/** @type {import("next").NextConfig} */\nconst nextConfig = {\n${body}\n};\n\nexport default nextConfig;\n`;
}

/** Sandbox assets bundled with the CLI at build time (see scripts/bundle-assets.mjs). */
function bundledAssetsDir(): string {
  return fileURLToPath(new URL("./assets/", import.meta.url));
}

const MANUAL_LAYOUT = (layoutFile: string) =>
  `wrap your root layout's {children} manually in ${layoutFile}:\n` +
  `    import { AppVendoRoot } from "./vendo-root";\n` +
  `    ...<AppVendoRoot>{children}</AppVendoRoot>...`;

const MANUAL_INSTRUMENTATION = (exampleFile: string, instrumentationFile: string) =>
  `merge the scheduler boot from ${exampleFile} into your existing ${instrumentationFile}'s register() (see @vendoai/next)`;

const MANUAL_NEXT_CONFIG = (configFile: string) =>
  `merge Vendo's Next.js settings into ${configFile}: add missing entries to ` +
  `transpilePackages (${VENDO_TRANSPILE_PACKAGES.join(", ")}) and add ` +
  `serverExternalPackages: ["${NEXT_SERVER_EXTERNAL_PACKAGES.join('", "')}"]`;

export async function wireNextApp(
  targetDir: string,
  info: FrameworkInfo,
  opts: { force: boolean },
): Promise<WiringSummary | null> {
  if (info.framework !== "next") return null;
  const found = await findAppDir(targetDir);
  const summary: WiringSummary = { written: [], edited: [], skipped: [], manual: [] };
  if (!found) {
    summary.skipped.push({
      step: "next-wiring",
      reason:
        "no App Router root layout at app/layout.* or src/app/layout.*. " +
        "Pages Router and route-group-only roots (app/(group)/layout.*) aren't " +
        "auto-wired yet — add app/api/vendo/[...path]/route.ts and wrap your " +
        "root layout with <AppVendoRoot> by hand (see @vendoai/next).",
    });
    return summary;
  }
  const { appDir, layoutFile } = found;
  const ts = layoutFile.endsWith(".tsx") || (await exists(path.join(targetDir, "tsconfig.json")));
  const rel = (p: string) => path.relative(targetDir, p);

  // 0. Guarantee the .vendo JSON artifacts the wrapper imports exist (the
  // extractor may have skipped them, and a missing JSON import breaks builds).
  const themePath = path.join(targetDir, ".vendo/theme.json");
  if (!(await exists(themePath))) {
    await fs.mkdir(path.dirname(themePath), { recursive: true });
    await fs.writeFile(themePath, JSON.stringify(DEFAULT_THEME_STUB, null, 2) + "\n");
    summary.written.push(rel(themePath));
  }
  const toolsPath = path.join(targetDir, ".vendo/tools.json");
  if (!(await exists(toolsPath))) {
    await fs.writeFile(toolsPath, JSON.stringify({ version: 1, tools: [], events: [] }, null, 2) + "\n");
    summary.written.push(rel(toolsPath));
  }

  // 1. The catch-all route.
  const routeFile = path.join(appDir, "api/vendo/[...path]", ts ? "route.ts" : "route.js");
  if (await exists(routeFile)) {
    summary.skipped.push({ step: "route", reason: `${rel(routeFile)} already exists` });
  } else {
    await fs.mkdir(path.dirname(routeFile), { recursive: true });
    await fs.writeFile(routeFile, ROUTE_SOURCE);
    summary.written.push(rel(routeFile));
  }

  // 2. The client wrapper.
  const rootFile = path.join(appDir, ts ? "vendo-root.tsx" : "vendo-root.jsx");
  const vendoRel = path
    .relative(appDir, path.join(targetDir, ".vendo"))
    .split(path.sep)
    .join("/");
  let productName = "Assistant";
  const pkgRaw = await readIf(path.join(targetDir, "package.json"));
  if (pkgRaw) {
    try {
      productName = productNameFrom((JSON.parse(pkgRaw) as { name?: string }).name);
    } catch {
      /* keep default */
    }
  }
  if (await exists(rootFile)) {
    summary.skipped.push({ step: "vendo-root", reason: `${rel(rootFile)} already exists` });
  } else {
    await fs.writeFile(rootFile, rootSource({ ts, vendoRel, productName }));
    summary.written.push(rel(rootFile));
  }

  // 3. Layout wrap (never rewrites on uncertainty).
  const layoutSource = await readIf(layoutFile);
  if (layoutSource === null) {
    summary.skipped.push({ step: "layout", reason: `${rel(layoutFile)} unreadable` });
    summary.manual.push(MANUAL_LAYOUT(rel(layoutFile)));
  } else {
    const edited = wrapLayoutChildren(layoutSource);
    if (edited === null) {
      summary.skipped.push({
        step: "layout",
        reason: `could not find exactly one {children} in ${rel(layoutFile)} — left untouched`,
      });
      summary.manual.push(MANUAL_LAYOUT(rel(layoutFile)));
    } else if (edited !== layoutSource) {
      await fs.writeFile(layoutFile, edited);
      summary.edited.push(rel(layoutFile));
    } else {
      summary.skipped.push({ step: "layout", reason: "already wired" });
    }
  }

  // 4. instrumentation.ts — boots the automation scheduler in the Node.js
  // runtime. Lives at the project root, or under src/ when the app itself
  // lives under src/app (Next.js instrumentation-file convention).
  const instrumentationDir = path.relative(targetDir, appDir) === "app" ? targetDir : path.join(targetDir, "src");
  const instrumentationFile = path.join(instrumentationDir, ts ? "instrumentation.ts" : "instrumentation.js");
  const instrumentationExisting = await readIf(instrumentationFile);
  if (instrumentationExisting === null) {
    await fs.mkdir(instrumentationDir, { recursive: true });
    await fs.writeFile(instrumentationFile, INSTRUMENTATION_SOURCE);
    summary.written.push(rel(instrumentationFile));
  } else {
    const merged = mergeInstrumentation(instrumentationExisting);
    if (merged === null) {
      const exampleFile = path.join(
        instrumentationDir,
        ts ? "instrumentation.vendo-example.ts" : "instrumentation.vendo-example.js",
      );
      if (await exists(exampleFile)) {
        summary.skipped.push({ step: "instrumentation", reason: `${rel(exampleFile)} already exists` });
      } else {
        await fs.writeFile(exampleFile, INSTRUMENTATION_SOURCE);
        summary.written.push(rel(exampleFile));
      }
      summary.manual.push(MANUAL_INSTRUMENTATION(rel(exampleFile), rel(instrumentationFile)));
    } else if (merged !== instrumentationExisting) {
      await fs.writeFile(instrumentationFile, merged);
      summary.edited.push(rel(instrumentationFile));
    } else {
      summary.skipped.push({ step: "instrumentation", reason: "already wired" });
    }
  }

  // 5. .env.example — create, or append each Vendo block once. Independent
  // sentinels (ANTHROPIC_API_KEY / DATABASE_URL) so a project wired by an
  // older codemod version gains the newer capability-additive block on re-run.
  const envFile = path.join(targetDir, ".env.example");
  const envExisting = await readIf(envFile);
  if (envExisting === null) {
    await fs.writeFile(envFile, ENV_EXAMPLE + "\n" + STORAGE_ENV);
    summary.written.push(rel(envFile));
  } else {
    let nextEnv = envExisting;
    if (!nextEnv.includes("Vendo — capability-additive keys")) {
      nextEnv = nextEnv.replace(/\n?$/, "\n\n") + ENV_EXAMPLE;
    }
    if (!nextEnv.includes("DATABASE_URL")) nextEnv = nextEnv.replace(/\n?$/, "\n\n") + STORAGE_ENV;
    if (nextEnv !== envExisting) {
      await fs.writeFile(envFile, nextEnv);
      summary.edited.push(rel(envFile));
    } else {
      summary.skipped.push({ step: ".env.example", reason: "already documents Vendo's provider keys and DATABASE_URL" });
    }
  }

  // 6. next.config.* — Vendo's published packages need transpilation in host
  // apps, and PGlite must stay external so its import.meta.url wasm loading
  // survives Next's server bundling.
  const configFiles = ["next.config.ts", "next.config.mjs", "next.config.js"]
    .map((name) => path.join(targetDir, name));
  const existingConfigFiles: string[] = [];
  for (const configFile of configFiles) {
    if (await exists(configFile)) existingConfigFiles.push(configFile);
  }
  if (existingConfigFiles.length === 0) {
    const configFile = path.join(targetDir, ts ? "next.config.ts" : "next.config.mjs");
    await fs.writeFile(configFile, minimalNextConfigSource(ts));
    summary.written.push(rel(configFile));
  } else if (existingConfigFiles.length > 1) {
    const names = existingConfigFiles.map((file) => rel(file)).join(", ");
    summary.skipped.push({ step: "next.config", reason: `multiple Next config files found (${names})` });
    summary.manual.push(MANUAL_NEXT_CONFIG(names));
  } else {
    const configFile = existingConfigFiles[0]!;
    const configSource = await readIf(configFile);
    if (configSource === null) {
      summary.skipped.push({ step: "next.config", reason: `${rel(configFile)} unreadable` });
      summary.manual.push(MANUAL_NEXT_CONFIG(rel(configFile)));
    } else {
      const merged = mergeNextConfig(configSource, rel(configFile));
      if (merged.kind === "skipped") {
        summary.skipped.push({ step: "next.config", reason: `${rel(configFile)}: ${merged.reason}` });
        summary.manual.push(MANUAL_NEXT_CONFIG(rel(configFile)));
      } else if (merged.kind === "updated") {
        await fs.writeFile(configFile, merged.source);
        summary.edited.push(rel(configFile));
      } else {
        summary.skipped.push({
          step: "next.config",
          reason: "already includes Vendo package transpilation and PGlite externalization",
        });
      }
    }
  }

  // 7. Sandbox assets into public/vendo/.
  const assetsDir = bundledAssetsDir();
  const publicDir = path.join(targetDir, "public/vendo");
  const assets: Array<[string, string]> = [
    ["vendo-react-runtime.js", "react-runtime.js"],
    ["vendo-components-sandbox.js", "components-sandbox.js"],
  ];
  for (const [from, to] of assets) {
    const src = path.join(assetsDir, from);
    const dest = path.join(publicDir, to);
    if (!(await exists(src))) {
      summary.skipped.push({ step: "sandbox-assets", reason: `bundled asset ${from} missing from CLI build` });
      summary.manual.push(
        "copy the sandbox assets by hand: react-runtime.js + components-sandbox.js into public/vendo/ (see @vendoai/next docs)",
      );
      break;
    }
    if ((await exists(dest)) && !opts.force) {
      summary.skipped.push({ step: "sandbox-assets", reason: `${rel(dest)} already exists` });
      continue;
    }
    await fs.mkdir(publicDir, { recursive: true });
    await fs.copyFile(src, dest);
    summary.written.push(rel(dest));
  }

  // 8. package.json: @vendoai/next + PGlite dependencies + prebuild sync
  // wiring. PGlite is also server-externalized in next.config, but pnpm's
  // strict node_modules still requires it to be resolvable from the app root.
  if (pkgRaw) {
    const withDep = addDependency(pkgRaw, "@vendoai/next", "latest");
    if (withDep === null) {
      summary.skipped.push({ step: "package.json", reason: "unparsable — add @vendoai/next and @electric-sql/pglite yourself" });
      summary.manual.push('add "@vendoai/next" to package.json dependencies and install');
      summary.manual.push('add "@electric-sql/pglite" to package.json dependencies and install');
      summary.manual.push('add "vendo sync" to your package.json "prebuild" script');
    } else {
      const withPglite = addDependency(withDep, PGLITE_DEPENDENCY, PGLITE_VERSION) ?? withDep;
      const withSync = addPrebuildSync(withPglite) ?? withPglite;
      if (withSync !== pkgRaw) {
        await fs.writeFile(path.join(targetDir, "package.json"), withSync);
        summary.edited.push("package.json");
        if (withPglite !== pkgRaw) {
          summary.manual.push("run your package manager's install (npm/pnpm/yarn) to pull @vendoai/next and @electric-sql/pglite");
        }
      } else {
        summary.skipped.push({ step: "package.json", reason: "@vendoai/next + @electric-sql/pglite + prebuild sync already present" });
      }
    }
  }

  return summary;
}

export function renderWiring(w: WiringSummary | null): string {
  if (!w) return "";
  const lines: string[] = [];
  for (const f of w.written) lines.push(`  wrote  ${f}`);
  for (const f of w.edited) lines.push(`  edited ${f}`);
  for (const s of w.skipped) lines.push(`  skip   ${s.step}: ${s.reason}`);
  if (w.manual.length > 0) {
    lines.push("  TODO (manual):");
    for (const m of w.manual) lines.push(`   - ${m}`);
  }
  if (lines.length === 0) return "";
  return ["next wiring:", ...lines].join("\n");
}
