import { mkdtempSync } from "node:fs";
import { promises as fs } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { describe, expect, it } from "vitest";
import {
  addDependency,
  addPrebuildSync,
  mergeInstrumentation,
  mergeNextConfig,
  productNameFrom,
  wireNextApp,
  wrapLayoutChildren,
} from "./next-wiring.js";
import { detectTarget } from "./detect.js";

async function exists(p: string): Promise<boolean> {
  return fs.access(p).then(() => true, () => false);
}

const CREATE_NEXT_APP_LAYOUT = `import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={\`\${geistSans.variable} antialiased\`}>
        {children}
      </body>
    </html>
  );
}
`;

describe("wrapLayoutChildren", () => {
  it("wraps the create-next-app layout and inserts a valid top-level import", () => {
    const out = wrapLayoutChildren(CREATE_NEXT_APP_LAYOUT);
    expect(out).not.toBeNull();
    // import is at the very top (no directive here) and syntactically valid
    expect(out!.startsWith('import { AppVendoRoot } from "./vendo-root";\n')).toBe(true);
    expect(out).toContain("<AppVendoRoot>{children}</AppVendoRoot>");
    // the app's own imports survive intact
    expect(out).toContain('import { Geist, Geist_Mono } from "next/font/google";');
    // destructured prop `children,` in the signature must NOT be touched
    expect(out).toContain("children,\n}: Readonly<{");
  });

  it("respects existing providers (wraps only the children expression)", () => {
    const layout = `import { ThemeProvider } from "./providers";
export default function RootLayout({ children }) {
  return (
    <html><body><ThemeProvider>{ children }</ThemeProvider></body></html>
  );
}
`;
    const out = wrapLayoutChildren(layout);
    expect(out).toContain("<ThemeProvider><AppVendoRoot>{ children }</AppVendoRoot></ThemeProvider>");
  });

  it("is idempotent on an already-wired layout", () => {
    const wired = wrapLayoutChildren(CREATE_NEXT_APP_LAYOUT)!;
    expect(wrapLayoutChildren(wired)).toBe(wired);
  });

  it("fails open when {children} is absent or ambiguous", () => {
    expect(wrapLayoutChildren("export default function L() { return null }")).toBeNull();
    const two = `export default function L({children}) { return <a><b>{children}</b><c>{children}</c></a> }`;
    expect(wrapLayoutChildren(two)).toBeNull();
  });

  it("does not corrupt a Prettier-wrapped multi-line last import (review P0)", () => {
    const layout = `import type { Metadata } from "next";
import {
  ThemeProvider,
  AnalyticsProvider,
} from "@/components/providers";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return <html><body><ThemeProvider>{children}</ThemeProvider></body></html>;
}
`;
    const out = wrapLayoutChildren(layout)!;
    // import lands on its own line at the top, never inside the brace block
    expect(out).toContain('import { AppVendoRoot } from "./vendo-root";\n');
    expect(out).not.toMatch(/import \{\nimport \{ AppVendoRoot/);
    expect(out).toContain("<ThemeProvider><AppVendoRoot>{children}</AppVendoRoot></ThemeProvider>");
    // the original multi-line import survives intact
    expect(out).toContain("  ThemeProvider,\n  AnalyticsProvider,\n} from");
  });

  it("ignores a {children} that lives inside a string literal (review P1)", () => {
    const layout = `export default function RootLayout({ children }: { children: React.ReactNode }) {
  const example = "<body>{children}</body>";
  return <html><body>{props.notChildren}</body></html>;
}
`;
    // the only >{children} is inside a string → no real JSX child match → fail open
    expect(wrapLayoutChildren(layout)).toBeNull();
  });

  it("does not false-positive idempotence on a comment mentioning the component (review P2)", () => {
    const layout = `// TODO: rename AppVendoRoot someday
export default function RootLayout({ children }) {
  return <html><body>{children}</body></html>;
}
`;
    const out = wrapLayoutChildren(layout);
    expect(out).not.toBeNull();
    expect(out).toContain("<AppVendoRoot>{children}</AppVendoRoot>");
  });

  it("places the import after a use-client directive when there are no imports", () => {
    const layout = `"use client";
export default function RootLayout({ children }) {
  return <html><body>{children}</body></html>;
}
`;
    const out = wrapLayoutChildren(layout)!;
    expect(out.startsWith(`"use client";\nimport { AppVendoRoot } from "./vendo-root";`)).toBe(true);
  });

  it("keeps the import BELOW a use-client directive that has a leading comment (review P1)", () => {
    const layout = `// Copyright 2026 Acme
"use client";
import { useState } from "react";
export default function RootLayout({ children }) {
  return <html><body>{children}</body></html>;
}
`;
    const out = wrapLayoutChildren(layout)!;
    // directive must remain the first STATEMENT (import inserted after it),
    // else Next demotes the file to a server component and hooks break.
    const dirIdx = out.indexOf('"use client";');
    const impIdx = out.indexOf('import { AppVendoRoot }');
    expect(dirIdx).toBeGreaterThanOrEqual(0);
    expect(impIdx).toBeGreaterThan(dirIdx);
    // nothing but the comment + whitespace precedes the directive
    expect(out.slice(0, dirIdx).trim()).toBe("// Copyright 2026 Acme");
  });
});

describe("addDependency", () => {
  it("adds the dep sorted and leaves existing files alone on re-run", () => {
    const pkg = JSON.stringify({ name: "x", dependencies: { zod: "^3", next: "16.0.0" } }, null, 2);
    const out = addDependency(pkg, "@vendoai/next", "latest")!;
    const parsed = JSON.parse(out) as { dependencies: Record<string, string> };
    expect(Object.keys(parsed.dependencies)).toEqual(["@vendoai/next", "next", "zod"]);
    expect(addDependency(out, "@vendoai/next", "latest")).toBe(out);
  });

  it("returns null on unparsable package.json", () => {
    expect(addDependency("{nope", "@vendoai/next", "latest")).toBeNull();
  });
});

describe("addPrebuildSync", () => {
  it("creates a prebuild script, extends an existing one, and is idempotent", () => {
    const created = addPrebuildSync(JSON.stringify({ name: "x" }))!;
    expect(JSON.parse(created).scripts.prebuild).toBe("vendo sync");

    const extended = addPrebuildSync(
      JSON.stringify({ name: "x", scripts: { prebuild: "generate-types" } }),
    )!;
    expect(JSON.parse(extended).scripts.prebuild).toBe("generate-types && vendo sync");

    // Re-run leaves it alone.
    expect(addPrebuildSync(extended)).toBe(extended);
  });

  it("returns null on unparsable package.json", () => {
    expect(addPrebuildSync("{nope")).toBeNull();
  });
});

describe("productNameFrom", () => {
  it("title-cases package names", () => {
    expect(productNameFrom("my-cool-app")).toBe("My Cool App");
    expect(productNameFrom("@acme/dash_board")).toBe("Dash Board");
    expect(productNameFrom(undefined)).toBe("Assistant");
  });
});

describe("mergeInstrumentation", () => {
  it("appends the scheduler boot to a file with no existing register()", () => {
    const existing = `export function onRequestError() {\n  console.log("boom");\n}\n`;
    const out = mergeInstrumentation(existing)!;
    expect(out).not.toBeNull();
    expect(out).toContain('console.log("boom")'); // original content survives
    expect(out).toContain("export async function register()");
    expect(out).toContain('await import("@vendoai/next")');
    expect(out).toContain("startVendoScheduler()");
  });

  it("is idempotent once merged", () => {
    const existing = `export function onRequestError() {}\n`;
    const merged = mergeInstrumentation(existing)!;
    expect(mergeInstrumentation(merged)).toBe(merged);
  });

  it("is idempotent on a hand-wired file (already imports @vendoai/next)", () => {
    const handWired = `export async function register() {\n  if (process.env.NEXT_RUNTIME === "nodejs") {\n    const { startVendoScheduler } = await import("@vendoai/next");\n    startVendoScheduler();\n  }\n}\n`;
    expect(mergeInstrumentation(handWired)).toBe(handWired);
  });

  it("fails open (returns null) when the file already declares its own register()", () => {
    const existing = `export async function register() {\n  await setupSentry();\n}\n`;
    expect(mergeInstrumentation(existing)).toBeNull();
  });

  it("does not false-positive on a comment merely mentioning register()", () => {
    const existing = `// TODO: add a register() hook later\nexport function onRequestError() {}\n`;
    const out = mergeInstrumentation(existing);
    expect(out).not.toBeNull();
    expect(out).toContain("export async function register()");
  });
});

describe("mergeNextConfig", () => {
  it("merges Vendo settings into a simple object-literal config", () => {
    const source = `const nextConfig = {
  reactStrictMode: true,
  transpilePackages: ["next-mdx-remote"],
  serverExternalPackages: ["sharp"],
};

export default nextConfig;
`;
    const out = mergeNextConfig(source, "next.config.mjs");
    expect(out.kind).toBe("updated");
    if (out.kind !== "updated") throw new Error("expected next.config update");
    expect(out.source).toContain('"next-mdx-remote"');
    expect(out.source).toContain('"@vendoai/next"');
    expect(out.source).toContain('"@vendoai/stage"');
    expect(out.source).toContain('"sharp"');
    expect(out.source).toContain('"@electric-sql/pglite"');
  });

  it("skips ambiguous configs instead of guessing", () => {
    const source = `import analyzer from "@next/bundle-analyzer";
const withAnalyzer = analyzer();

export default withAnalyzer({});
`;
    const out = mergeNextConfig(source, "next.config.mjs");
    expect(out.kind).toBe("skipped");
    if (out.kind !== "skipped") throw new Error("expected next.config skip");
    expect(out.reason).toContain("plain object literal");
  });
});

async function scaffoldFreshApp(withSrcDir: boolean): Promise<string> {
  const dir = mkdtempSync(path.join(tmpdir(), "vendo-wire-"));
  const appDir = path.join(dir, withSrcDir ? "src/app" : "app");
  await fs.mkdir(appDir, { recursive: true });
  await fs.writeFile(path.join(appDir, "layout.tsx"), CREATE_NEXT_APP_LAYOUT);
  await fs.writeFile(path.join(dir, "tsconfig.json"), "{}");
  await fs.writeFile(
    path.join(dir, "package.json"),
    JSON.stringify({ name: "fresh-app", dependencies: { next: "16.0.0" } }, null, 2),
  );
  return dir;
}

describe("wireNextApp", () => {
  it("wires a fresh TS app end-to-end (src/app layout)", async () => {
    const dir = await scaffoldFreshApp(true);
    const info = await detectTarget(dir);
    const summary = (await wireNextApp(dir, info, { force: false }))!;

    // route + wrapper + env + .vendo backfill written
    const route = await fs.readFile(path.join(dir, "src/app/api/vendo/[...path]/route.ts"), "utf8");
    expect(route).toContain("createVendoHandler()");
    expect(route).toContain('runtime = "nodejs"');
    const root = await fs.readFile(path.join(dir, "src/app/vendo-root.tsx"), "utf8");
    expect(root).toContain('from "../../.vendo/theme.json"');
    expect(root).toContain('productName="Fresh App"');
    const layout = await fs.readFile(path.join(dir, "src/app/layout.tsx"), "utf8");
    expect(layout).toContain("<AppVendoRoot>{children}</AppVendoRoot>");
    const env = await fs.readFile(path.join(dir, ".env.example"), "utf8");
    expect(env).toContain("ANTHROPIC_API_KEY");
    expect(env).toContain("DATABASE_URL");
    expect(env).toContain("VENDO_DATA_DIR");
    expect(env).toContain("VENDO_TICK_SECRET");
    expect(env).toContain("COMPOSIO_WEBHOOK_SECRET");
    expect(env).toContain("VENDO_SCHEDULER");
    expect(JSON.parse(await fs.readFile(path.join(dir, ".vendo/tools.json"), "utf8")).tools).toEqual([]);
    const pkg = JSON.parse(await fs.readFile(path.join(dir, "package.json"), "utf8")) as {
      dependencies: Record<string, string>;
    };
    expect(pkg.dependencies["@vendoai/next"]).toBeDefined();
    const nextConfig = await fs.readFile(path.join(dir, "next.config.ts"), "utf8");
    expect(nextConfig).toContain('transpilePackages: [');
    expect(nextConfig).toContain('"@vendoai/next"');
    expect(nextConfig).toContain('"@vendoai/stage"');
    expect(nextConfig).toContain('serverExternalPackages: [');
    expect(nextConfig).toContain('"@electric-sql/pglite"');

    // src/app layout → instrumentation.ts lives under src/, matching Next's convention
    const instrumentation = await fs.readFile(path.join(dir, "src/instrumentation.ts"), "utf8");
    expect(instrumentation).toContain("export async function register()");
    expect(instrumentation).toContain('process.env.NEXT_RUNTIME === "nodejs"');
    expect(instrumentation).toContain('await import("@vendoai/next")');
    expect(instrumentation).toContain("startVendoScheduler()");
    expect(summary.written).toContain("src/instrumentation.ts");

    // sandbox assets aren't bundled in the source tree — reported, not fatal
    expect(summary.skipped.some((s) => s.step === "sandbox-assets")).toBe(true);
  });

  it("writes instrumentation.ts at the project root for an app/ (non-src) layout", async () => {
    const dir = await scaffoldFreshApp(false);
    const info = await detectTarget(dir);
    await wireNextApp(dir, info, { force: false });
    const instrumentation = await fs.readFile(path.join(dir, "instrumentation.ts"), "utf8");
    expect(instrumentation).toContain("startVendoScheduler()");
    expect(await exists(path.join(dir, "src/instrumentation.ts"))).toBe(false);
  });

  it("creates a minimal next.config.ts when the app has none", async () => {
    const dir = await scaffoldFreshApp(false);
    const info = await detectTarget(dir);
    const summary = (await wireNextApp(dir, info, { force: false }))!;
    const config = await fs.readFile(path.join(dir, "next.config.ts"), "utf8");
    expect(summary.written).toContain("next.config.ts");
    expect(config).toContain('import type { NextConfig } from "next"');
    expect(config).toContain('"@vendoai/next"');
    expect(config).toContain('"@electric-sql/pglite"');
  });

  it("edits a simple next.config object literal without removing existing entries", async () => {
    const dir = await scaffoldFreshApp(false);
    const configPath = path.join(dir, "next.config.mjs");
    await fs.writeFile(
      configPath,
      `const nextConfig = {
  transpilePackages: ["next-mdx-remote"],
  serverExternalPackages: ["sharp"],
};

export default nextConfig;
`,
    );
    const info = await detectTarget(dir);
    const summary = (await wireNextApp(dir, info, { force: false }))!;
    const config = await fs.readFile(configPath, "utf8");
    expect(summary.edited).toContain("next.config.mjs");
    expect(config).toContain('"next-mdx-remote"');
    expect(config).toContain('"@vendoai/shell"');
    expect(config).toContain('"sharp"');
    expect(config).toContain('"@electric-sql/pglite"');
  });

  it("skips ambiguous next.config files and reports exact manual instructions", async () => {
    const dir = await scaffoldFreshApp(false);
    const configPath = path.join(dir, "next.config.mjs");
    const source = `import analyzer from "@next/bundle-analyzer";
const withAnalyzer = analyzer();

export default withAnalyzer({});
`;
    await fs.writeFile(configPath, source);
    const info = await detectTarget(dir);
    const summary = (await wireNextApp(dir, info, { force: false }))!;
    expect(await fs.readFile(configPath, "utf8")).toBe(source);
    expect(summary.skipped.some((s) => s.step === "next.config")).toBe(true);
    expect(summary.manual.some((m) => m.includes("transpilePackages") && m.includes("@electric-sql/pglite"))).toBe(true);
  });

  it("merges into an existing instrumentation.ts non-destructively when it has no register()", async () => {
    const dir = await scaffoldFreshApp(false);
    await fs.writeFile(
      path.join(dir, "instrumentation.ts"),
      `export function onRequestError() {\n  console.log("existing hook");\n}\n`,
    );
    const info = await detectTarget(dir);
    const summary = (await wireNextApp(dir, info, { force: false }))!;
    const instrumentation = await fs.readFile(path.join(dir, "instrumentation.ts"), "utf8");
    expect(instrumentation).toContain('console.log("existing hook")'); // original survives
    expect(instrumentation).toContain("startVendoScheduler()");
    expect(summary.edited).toContain("instrumentation.ts");
    expect(await exists(path.join(dir, "instrumentation.vendo-example.ts"))).toBe(false);
  });

  it("falls open to instrumentation.vendo-example.ts + a manual step when an existing register() can't be merged safely", async () => {
    const dir = await scaffoldFreshApp(false);
    const existing = `export async function register() {\n  await setupSentry();\n}\n`;
    await fs.writeFile(path.join(dir, "instrumentation.ts"), existing);
    const info = await detectTarget(dir);
    const summary = (await wireNextApp(dir, info, { force: false }))!;
    expect(await fs.readFile(path.join(dir, "instrumentation.ts"), "utf8")).toBe(existing);
    const example = await fs.readFile(path.join(dir, "instrumentation.vendo-example.ts"), "utf8");
    expect(example).toContain("startVendoScheduler()");
    expect(summary.written).toContain("instrumentation.vendo-example.ts");
    expect(summary.manual.some((m) => m.includes("instrumentation.vendo-example.ts"))).toBe(true);

    // second run: example file already exists — reported as skipped, not rewritten
    const second = (await wireNextApp(dir, info, { force: false }))!;
    expect(second.skipped.some((s) => s.step === "instrumentation")).toBe(true);
    expect(second.written).not.toContain("instrumentation.vendo-example.ts");
  });

  it("is idempotent: a second run edits nothing", async () => {
    const dir = await scaffoldFreshApp(false);
    const info = await detectTarget(dir);
    await wireNextApp(dir, info, { force: false });
    const layoutAfterFirst = await fs.readFile(path.join(dir, "app/layout.tsx"), "utf8");
    const instrumentationAfterFirst = await fs.readFile(path.join(dir, "instrumentation.ts"), "utf8");
    const envAfterFirst = await fs.readFile(path.join(dir, ".env.example"), "utf8");
    const nextConfigAfterFirst = await fs.readFile(path.join(dir, "next.config.ts"), "utf8");
    const second = (await wireNextApp(dir, info, { force: false }))!;
    expect(second.edited).toEqual([]);
    expect(await fs.readFile(path.join(dir, "app/layout.tsx"), "utf8")).toBe(layoutAfterFirst);
    expect(await fs.readFile(path.join(dir, "instrumentation.ts"), "utf8")).toBe(instrumentationAfterFirst);
    expect(await fs.readFile(path.join(dir, ".env.example"), "utf8")).toBe(envAfterFirst);
    expect(await fs.readFile(path.join(dir, "next.config.ts"), "utf8")).toBe(nextConfigAfterFirst);
  });

  it("fails open on an unrecognizable layout: files written, layout untouched, manual steps printed", async () => {
    const dir = await scaffoldFreshApp(false);
    const weird = "export default function L() { return <Slot /> }\n";
    await fs.writeFile(path.join(dir, "app/layout.tsx"), weird);
    const info = await detectTarget(dir);
    const summary = (await wireNextApp(dir, info, { force: false }))!;
    expect(await fs.readFile(path.join(dir, "app/layout.tsx"), "utf8")).toBe(weird);
    expect(summary.skipped.some((s) => s.step === "layout")).toBe(true);
    expect(summary.manual.some((m) => m.includes("AppVendoRoot"))).toBe(true);
  });

  it("returns null for non-Next targets and skips gracefully without an app dir", async () => {
    const dir = mkdtempSync(path.join(tmpdir(), "vendo-wire-"));
    await fs.writeFile(path.join(dir, "package.json"), JSON.stringify({ name: "not-next" }));
    expect(await wireNextApp(dir, await detectTarget(dir), { force: false })).toBeNull();

    await fs.writeFile(
      path.join(dir, "package.json"),
      JSON.stringify({ name: "pages-router", dependencies: { next: "16.0.0" } }),
    );
    const summary = (await wireNextApp(dir, await detectTarget(dir), { force: false }))!;
    expect(summary.skipped[0]?.reason).toContain("no App Router root layout");
  });
});
