import { existsSync } from "node:fs";
import { mkdir, mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { describe, expect, it, vi } from "vitest";
import {
  buildDeployPlan,
  buildRegistryPayload,
  GENERATED_FILE_MARKER,
  parseDemoDeployArgs,
  parseRailwayDomain,
  pnpmVersionFromPackageManager,
  renderDockerfile,
  runDemoDeploy,
  shouldWriteGeneratedFile,
} from "./deploy.js";

describe("parseDemoDeployArgs", () => {
  it("parses a fully specified deploy", () => {
    expect(parseDemoDeployArgs([
      "--app", "apps/demo-linear",
      "--project", "other-project",
      "--router-url", "https://router.example",
      "--skip-registry",
      "--dry-run",
    ])).toEqual({
      app: "apps/demo-linear",
      project: "other-project",
      routerUrl: "https://router.example",
      skipRegistry: true,
      dryRun: true,
    });
  });

  it("defaults project, router url, and both flags", () => {
    expect(parseDemoDeployArgs(["--app", "apps/demo-linear"])).toEqual({
      app: "apps/demo-linear",
      project: "vendo-demos",
      routerUrl: "https://demos.vendo.run",
      skipRegistry: false,
      dryRun: false,
    });
  });

  it("accepts the literal separator forwarded by pnpm scripts", () => {
    expect(parseDemoDeployArgs(["--", "--app", "apps/demo-linear"])).toMatchObject({ app: "apps/demo-linear" });
  });

  it("requires --app and rejects unknown options and missing values", () => {
    expect(() => parseDemoDeployArgs([])).toThrow("--app is required");
    expect(() => parseDemoDeployArgs(["--app", "apps/x", "--nope"])).toThrow("Unknown option: --nope");
    expect(() => parseDemoDeployArgs(["--app"])).toThrow("--app requires a value");
    expect(() => parseDemoDeployArgs(["--app", "apps/x", "--router-url", "not a url"]))
      .toThrow("--router-url");
  });

  it("requires an https router URL, except for localhost development", () => {
    expect(() => parseDemoDeployArgs(["--app", "apps/x", "--router-url", "http://router.example"]))
      .toThrow(/--router-url must be https/);
    expect(parseDemoDeployArgs(["--app", "apps/x", "--router-url", "http://localhost:8080"]).routerUrl)
      .toBe("http://localhost:8080");
    expect(parseDemoDeployArgs(["--app", "apps/x", "--router-url", "http://127.0.0.1:8080"]).routerUrl)
      .toBe("http://127.0.0.1:8080");
  });

  it("normalizes a trailing slash off the router URL (admin paths append cleanly)", () => {
    expect(parseDemoDeployArgs(["--app", "apps/x", "--router-url", "https://router.example/"]).routerUrl)
      .toBe("https://router.example");
  });
});

describe("Dockerfile rendering", () => {
  it("parametrizes demo-bank's pattern: turbo filter, app WORKDIR, port 3000, marker", () => {
    const dockerfile = renderDockerfile({ packageName: "demo-linear", appPath: "apps/demo-linear", pnpmVersion: "11.10.0" });
    expect(dockerfile).toContain(GENERATED_FILE_MARKER);
    expect(dockerfile).toContain("FROM node:22-bookworm-slim");
    expect(dockerfile).toContain("pnpm@11.10.0");
    expect(dockerfile).toContain("pnpm exec turbo run build --filter=demo-linear");
    expect(dockerfile).toContain("WORKDIR /app/apps/demo-linear");
    expect(dockerfile).toContain("EXPOSE 3000");
    expect(dockerfile).toContain('CMD ["pnpm", "start"]');
  });

  it("derives the pnpm pin from the repo's packageManager field", () => {
    expect(pnpmVersionFromPackageManager("pnpm@11.10.0")).toBe("11.10.0");
    expect(pnpmVersionFromPackageManager(undefined)).toBe("11.10.0");
    expect(pnpmVersionFromPackageManager("pnpm@12.0.1+sha512.abc")).toBe("12.0.1");
  });

  it("shouldWriteGeneratedFile: absent or previously generated by us, never a hand-edited file", () => {
    expect(shouldWriteGeneratedFile(undefined)).toBe(true);
    expect(shouldWriteGeneratedFile(`# hello\n${GENERATED_FILE_MARKER}\nFROM x\n`)).toBe(true);
    expect(shouldWriteGeneratedFile("FROM node:22\n# hand-written\n")).toBe(false);
  });
});

describe("defaultExec cancellation", () => {
  it("SIGKILLs the spawned process group when the signal aborts — side effects cease", async () => {
    const { defaultExec } = await import("./deploy.js");
    const controller = new AbortController();
    const started = Date.now();
    const running = defaultExec(["sleep", "30"], { cwd: tmpdir(), signal: controller.signal });
    setTimeout(() => controller.abort(new Error("wall-clock cap fired")), 150);
    // The close event resolving IS the subprocess exiting: a live sleep(30)
    // would hold this promise for 30s.
    const result = await running;
    expect(Date.now() - started).toBeLessThan(5_000);
    expect(result.code).not.toBe(0);
  });

  it("refuses to start when the signal is already aborted", async () => {
    const { defaultExec } = await import("./deploy.js");
    const controller = new AbortController();
    controller.abort(new Error("cap already fired"));
    await expect(defaultExec(["sleep", "30"], { cwd: tmpdir(), signal: controller.signal }))
      .rejects.toThrow("cap already fired");
  });
});

describe("parseRailwayDomain", () => {
  // Samples are synthetic (probing `railway domain` live creates domains);
  // the parser is deliberately liberal: JSON first, then a domain regex.
  it("parses a --json object payload", () => {
    expect(parseRailwayDomain('{"domain":"demo-linear-production.up.railway.app"}'))
      .toBe("demo-linear-production.up.railway.app");
  });

  it("parses JSON embedded among log lines", () => {
    const output = 'Creating domain...\n{"domain":"https://demo-x.up.railway.app/"}\nDone\n';
    expect(parseRailwayDomain(output)).toBe("demo-x.up.railway.app");
  });

  it("falls back to finding a railway domain in plain text", () => {
    expect(parseRailwayDomain("Service Domain created:\n🚀 https://demo-linear-production.up.railway.app\n"))
      .toBe("demo-linear-production.up.railway.app");
  });

  it("returns undefined when no domain is present", () => {
    expect(parseRailwayDomain("no domains here")).toBeUndefined();
    expect(parseRailwayDomain("")).toBeUndefined();
  });
});

describe("buildRegistryPayload", () => {
  const config = {
    id: "linear",
    prospect: "Linear",
    ctaUrl: "https://cal.com/yousefhelal",
    beats: [],
    caps: { maxTurns: 20, maxSpendUsd: 5 },
    expiresAt: "2026-08-01T00:00:00Z",
  };

  it("builds the router admin row from the config and the railway domain", () => {
    expect(buildRegistryPayload(config, "demo-linear.up.railway.app")).toEqual({
      id: "linear",
      url: "https://demo-linear.up.railway.app",
      prospect: "Linear",
      expiresAt: "2026-08-01T00:00:00Z",
    });
  });

  it("carries permanent: true PLUS the compat expiry (2026-07-24 incident: a pre-permanent reaper treats a missing expiresAt as invalid-expiry and tears the demo down)", () => {
    const { expiresAt: _expiresAt, ...permanentConfig } = { ...config, permanent: true };
    expect(buildRegistryPayload(permanentConfig, "demo-maple.up.railway.app")).toEqual({
      id: "linear",
      url: "https://demo-maple.up.railway.app",
      prospect: "Linear",
      permanent: true,
      expiresAt: "2126-01-01T00:00:00.000Z",
    });
  });

  it("a permanent config's own expiresAt is superseded by the compat expiry (permanent wins)", () => {
    expect(buildRegistryPayload({ ...config, permanent: true }, "demo-maple.up.railway.app").expiresAt)
      .toBe("2126-01-01T00:00:00.000Z");
  });

  it("normalizes a domain that arrives with protocol or trailing slash", () => {
    expect(buildRegistryPayload(config, "https://demo-linear.up.railway.app/").url)
      .toBe("https://demo-linear.up.railway.app");
  });
});

describe("buildDeployPlan", () => {
  const plan = buildDeployPlan({
    serviceName: "demo-linear",
    project: "vendo-demos",
    dockerfilePath: "apps/demo-linear/Dockerfile",
    modelKeys: { ANTHROPIC_API_KEY: "sk-ant-SECRET" },
  });
  const finalizeSteps = plan.finalize("https://demo-linear-production.up.railway.app");

  it("prepares link/add/domain first — the domain must exist BEFORE variables are set", () => {
    expect(plan.prepare.map((step) => step.command.slice(0, 2).join(" "))).toEqual([
      "railway link",
      "railway add",
      "railway domain",
    ]);
    const [link, add, domain] = plan.prepare;
    expect(link?.command).toEqual(["railway", "link", "--project", "vendo-demos"]);
    expect(add?.command).toEqual(["railway", "add", "--service", "demo-linear", "--json"]);
    expect(domain?.command).toEqual(["railway", "domain", "--service", "demo-linear", "--json"]);
  });

  it("finalizes with variables (VENDO_BASE_URL from the domain, plus the host-bound autologin flag) then up", () => {
    expect(finalizeSteps.map((step) => step.command.slice(0, 2).join(" "))).toEqual([
      "railway variables",
      "railway up",
    ]);
    const [variables, up] = finalizeSteps;
    expect(variables?.command).toEqual([
      "railway", "variables",
      "--set", "ANTHROPIC_API_KEY=sk-ant-SECRET",
      "--set", "NODE_ENV=production",
      "--set", "RAILWAY_DOCKERFILE_PATH=apps/demo-linear/Dockerfile",
      "--set", "VENDO_BASE_URL=https://demo-linear-production.up.railway.app",
      // A sent-to-a-prospect demo opens straight into the product; the
      // middleware only honors this on VENDO_BASE_URL's own authority.
      "--set", "DEMO_AUTOLOGIN=1",
      "--service", "demo-linear",
      "--skip-deploys",
    ]);
    expect(up?.command).toEqual(["railway", "up", "--service", "demo-linear", "--detach"]);
  });

  it("NEVER exposes the anthropic key in the display rendering", () => {
    for (const step of [...plan.prepare, ...finalizeSteps]) {
      expect(step.display).not.toContain("sk-ant-SECRET");
    }
    expect(finalizeSteps[0]?.display).toContain("ANTHROPIC_API_KEY=<redacted>");
  });

  // The Cloud posture: one VENDO_API_KEY buys the hosted store, the
  // connections broker and the metered model gateway (apps/demo-template's
  // server.ts leaves those slots unset on purpose).
  it("sets VENDO_API_KEY when present, and redacts it too", () => {
    const cloudPlan = buildDeployPlan({
      serviceName: "demo-linear",
      project: "vendo-demos",
      dockerfilePath: "Dockerfile",
      modelKeys: { VENDO_API_KEY: "vk-SECRET" },
    });
    const [variables] = cloudPlan.finalize("https://demo-linear-production.up.railway.app");
    expect(variables?.command).toContain("VENDO_API_KEY=vk-SECRET");
    expect(variables?.command).not.toContain("ANTHROPIC_API_KEY=");
    expect(variables?.display).toContain("VENDO_API_KEY=<redacted>");
    expect(variables?.display).not.toContain("vk-SECRET");
  });

  // A scratch clone deploys ITSELF: the app dir is the upload context, so the
  // Dockerfile path is context-relative. `up` never names a directory — it
  // uploads its cwd, and the caller runs it inside the clone. Passing an
  // absolute path outside the cwd instead fails with "prefix not found"
  // (live: the first standalone deploy died exactly there).
  it("never passes an upload path to `railway up`", () => {
    const standalonePlan = buildDeployPlan({
      serviceName: "demo-linear",
      project: "vendo-demos",
      dockerfilePath: "Dockerfile",
      modelKeys: { VENDO_API_KEY: "vk-SECRET" },
    });
    const [variables, up] = standalonePlan.finalize("https://demo-linear-production.up.railway.app");
    expect(variables?.command).toContain("RAILWAY_DOCKERFILE_PATH=Dockerfile");
    expect(up?.command).toEqual(["railway", "up", "--service", "demo-linear", "--detach"]);
  });

  it("tolerates ONLY `railway add` failing (when the service already exists)", () => {
    expect(plan.prepare[1]?.allowFailure).toBe(true);
    expect([...plan.prepare, ...finalizeSteps].filter((step) => step.allowFailure !== true)).toHaveLength(4);
  });
});

describe("runDemoDeploy (dry run against a fixture app)", () => {
  const demoConfig = {
    id: "linear",
    prospect: "Linear",
    ctaUrl: "https://cal.com/yousefhelal",
    beats: [{ key: "generate-ui", prompt: "Show me", chip: "Show me" }],
    caps: { maxTurns: 20, maxSpendUsd: 5 },
    expiresAt: "2026-08-01T00:00:00Z",
  };

  async function writeFixture(): Promise<{ repoRoot: string; appDir: string }> {
    const repoRoot = await mkdtemp(path.join(tmpdir(), "vendo-demo-deploy-"));
    const appDir = path.join(repoRoot, "apps", "demo-linear");
    await mkdir(appDir, { recursive: true });
    await writeFile(path.join(appDir, "package.json"), `${JSON.stringify({ name: "demo-linear", private: true }, null, 2)}\n`);
    await writeFile(path.join(appDir, "demo.config.json"), `${JSON.stringify(demoConfig, null, 2)}\n`);
    return { repoRoot, appDir };
  }

  const args = {
    app: "apps/demo-linear",
    project: "vendo-demos",
    routerUrl: "https://demos.vendo.run",
    skipRegistry: false,
    dryRun: true,
  };

  it("validates the config, renders the Dockerfile, and prints the plan without executing", async () => {
    const { repoRoot, appDir } = await writeFixture();
    const exec = vi.fn();
    const fetchImpl = vi.fn();
    const lines: string[] = [];
    const result = await runDemoDeploy(args, {
      repoRoot,
      exec,
      fetchImpl: fetchImpl as unknown as typeof fetch,
      env: {},
      write: (line) => lines.push(line),
    });
    expect(result.dryRun).toBe(true);
    expect(result.serviceName).toBe("demo-linear");
    expect(exec).not.toHaveBeenCalled();
    expect(fetchImpl).not.toHaveBeenCalled();
    const dockerfile = await readFile(path.join(appDir, "Dockerfile"), "utf8");
    expect(dockerfile).toContain(GENERATED_FILE_MARKER);
    expect(dockerfile).toContain("--filter=demo-linear");
    // The upload-exclusion mechanism is the repo-root .dockerignore; a
    // per-app one would be inert (Docker only honors the context root's).
    expect(existsSync(path.join(appDir, ".dockerignore"))).toBe(false);
    const output = lines.join("\n");
    expect(output).toContain("railway up --service demo-linear --detach");
    // The dry run is honest about the not-yet-known domain.
    expect(output).toContain("VENDO_BASE_URL=<from railway domain>");
    expect(output).toContain("POST https://demos.vendo.run/admin/demos");
    expect(output).not.toContain("sk-ant");
  });

  it("keeps a hand-edited Dockerfile instead of clobbering it", async () => {
    const { repoRoot, appDir } = await writeFixture();
    await writeFile(path.join(appDir, "Dockerfile"), "FROM scratch\n# hand-tuned\n");
    await runDemoDeploy(args, { repoRoot, env: {}, write: () => {} });
    expect(await readFile(path.join(appDir, "Dockerfile"), "utf8")).toBe("FROM scratch\n# hand-tuned\n");
  });

  // The leak fix's other half: a scratch clone lives outside the repo, so it
  // deploys ITSELF (self-contained, published @vendoai/* pins) instead of
  // dragging the whole OSS tree into a prospect's image.
  it("deploys an app outside the repo root as a standalone upload", async () => {
    const { repoRoot } = await writeFixture();
    const scratchDir = await mkdtemp(path.join(tmpdir(), "vendo-demo-scratch-"));
    const appDir = path.join(scratchDir, "demo-linear");
    await mkdir(appDir, { recursive: true });
    await writeFile(path.join(appDir, "package.json"), `${JSON.stringify({ name: "demo-linear", private: true }, null, 2)}\n`);
    await writeFile(path.join(appDir, "demo.config.json"), `${JSON.stringify(demoConfig, null, 2)}\n`);
    const lines: string[] = [];
    const result = await runDemoDeploy({ ...args, app: appDir }, { repoRoot, env: {}, write: (line) => lines.push(line) });

    expect(result.appPath).toBe(appDir);
    const dockerfile = await readFile(path.join(appDir, "Dockerfile"), "utf8");
    // Standalone: no monorepo install, no turbo filter, no nested WORKDIR.
    expect(dockerfile).not.toContain("turbo");
    expect(dockerfile).toContain("RUN pnpm build");
    expect(dockerfile).not.toContain("WORKDIR /app/");
    const output = lines.join("\n");
    expect(output).toContain("railway up --service demo-linear --detach");
    expect(output).toContain("RAILWAY_DOCKERFILE_PATH=Dockerfile");
  });

  it("runs the railway CLI INSIDE a standalone clone, so `up` uploads the clone", async () => {
    const { repoRoot } = await writeFixture();
    const scratchDir = await mkdtemp(path.join(tmpdir(), "vendo-demo-scratch-"));
    const appDir = path.join(scratchDir, "demo-linear");
    await mkdir(appDir, { recursive: true });
    await writeFile(path.join(appDir, "package.json"), `${JSON.stringify({ name: "demo-linear", private: true }, null, 2)}\n`);
    await writeFile(path.join(appDir, "demo.config.json"), `${JSON.stringify(demoConfig, null, 2)}\n`);
    const exec = vi.fn().mockImplementation(async (command: string[]) => ({
      code: 0,
      stdout: command[1] === "domain" ? '{"domain":"demo-linear-production.up.railway.app"}' : "",
      stderr: "",
    }));
    await runDemoDeploy(
      { ...args, app: appDir, dryRun: false },
      {
        repoRoot,
        exec,
        fetchImpl: vi.fn().mockResolvedValue(new Response("{}", { status: 200 })) as unknown as typeof fetch,
        env: { ANTHROPIC_API_KEY: "sk-ant-SECRET", ROUTER_ADMIN_TOKEN: "token" },
        write: () => {},
      },
    );
    for (const [command, options] of exec.mock.calls as [string[], { cwd: string }][]) {
      expect(options.cwd, `${command.join(" ")} ran outside the clone`).toBe(appDir);
    }
  });

  it("refuses to run live with no inference key at all", async () => {
    const { repoRoot } = await writeFixture();
    await expect(runDemoDeploy({ ...args, dryRun: false }, { repoRoot, env: {}, write: () => {} }))
      .rejects.toThrow(/VENDO_API_KEY .* or ANTHROPIC_API_KEY/);
  });

  it("surfaces a broken demo.config.json loudly", async () => {
    const { repoRoot, appDir } = await writeFixture();
    await writeFile(path.join(appDir, "demo.config.json"), JSON.stringify({ ...demoConfig, id: "Not A Slug" }));
    await expect(runDemoDeploy(args, { repoRoot, env: {}, write: () => {} }))
      .rejects.toThrow(/id: must be lowercase alphanumeric with hyphens/);
  });

  describe("live path (mock exec)", () => {
    const env = { ANTHROPIC_API_KEY: "sk-ant-SECRET", ROUTER_ADMIN_TOKEN: "token" };
    const liveArgs = { ...args, dryRun: false };

    function happyExec() {
      return vi.fn().mockImplementation(async (command: string[]) => ({
        code: 0,
        stdout: command[1] === "domain" ? '{"domain":"demo-linear-production.up.railway.app"}' : "",
        stderr: "",
      }));
    }

    it("runs the lockfile preflight, then the railway plan, then registers with the router", async () => {
      const { repoRoot } = await writeFixture();
      const exec = happyExec();
      const fetchImpl = vi.fn().mockResolvedValue(new Response("{}", { status: 200 }));
      const result = await runDemoDeploy(liveArgs, {
        repoRoot,
        exec,
        fetchImpl: fetchImpl as unknown as typeof fetch,
        env,
        write: () => {},
      });
      const commands = exec.mock.calls.map(([command]) => (command as string[]).join(" "));
      // `railway up` archives the working tree, so the lockfile must be
      // synced BEFORE any railway step (untracked scratch apps otherwise
      // break --frozen-lockfile inside the image build). The domain is
      // fetched BEFORE variables so VENDO_BASE_URL can carry it, and up runs
      // last (one deploy, with all variables already in place).
      expect(commands[0]).toBe("pnpm install --lockfile-only");
      expect(commands.slice(1)).toEqual([
        "railway link --project vendo-demos",
        "railway add --service demo-linear --json",
        "railway domain --service demo-linear --json",
        "railway variables --set ANTHROPIC_API_KEY=sk-ant-SECRET --set NODE_ENV=production --set RAILWAY_DOCKERFILE_PATH=apps/demo-linear/Dockerfile --set VENDO_BASE_URL=https://demo-linear-production.up.railway.app --set DEMO_AUTOLOGIN=1 --service demo-linear --skip-deploys",
        "railway up --service demo-linear --detach",
      ]);
      // No second `railway domain` call: the early result is reused for both
      // VENDO_BASE_URL and the registry row.
      expect(commands.filter((command) => command.includes("railway domain"))).toHaveLength(1);
      expect(result.domain).toBe("demo-linear-production.up.railway.app");
      expect(fetchImpl).toHaveBeenCalledWith("https://demos.vendo.run/admin/demos", expect.objectContaining({ method: "POST" }));
      expect(result.registryPayload).toEqual({
        id: "linear",
        url: "https://demo-linear-production.up.railway.app",
        prospect: "Linear",
        expiresAt: "2026-08-01T00:00:00Z",
      });
    });

    it("surfaces a router 409 as an actionable slug-taken error naming the owning prospect", async () => {
      const { repoRoot } = await writeFixture();
      const exec = happyExec();
      const conflictBody = JSON.stringify({
        error: "id taken",
        existing: {
          id: "linear",
          prospect: "Linear Logistics GmbH",
          url: "https://demo-linear-other.up.railway.app/",
          expiresAt: "2026-09-01T00:00:00Z",
        },
      });
      const fetchImpl = vi.fn().mockResolvedValue(new Response(conflictBody, { status: 409 }));
      const error = await runDemoDeploy(liveArgs, {
        repoRoot,
        exec,
        fetchImpl: fetchImpl as unknown as typeof fetch,
        env,
        write: () => {},
      }).catch((caught: unknown) => caught as Error);
      expect(error).toBeInstanceOf(Error);
      const message = (error as Error).message;
      expect(message).toContain('slug "linear" is already taken');
      expect(message).toContain("Linear Logistics GmbH");
      expect(message).toMatch(/variant slug/);
      expect(message).toContain("mercury-bank");
      expect(message).toContain("demo:create");
    });

    it("still surfaces a 409 usably when the body is not the router's JSON shape", async () => {
      const { repoRoot } = await writeFixture();
      const fetchImpl = vi.fn().mockResolvedValue(new Response("nope", { status: 409 }));
      const error = await runDemoDeploy(liveArgs, {
        repoRoot,
        exec: happyExec(),
        fetchImpl: fetchImpl as unknown as typeof fetch,
        env,
        write: () => {},
      }).catch((caught: unknown) => caught as Error);
      expect(error).toBeInstanceOf(Error);
      expect((error as Error).message).toContain('slug "linear" is already taken');
      expect((error as Error).message).toContain("demo:create");
    });

    it("scrubs the anthropic key out of echoed child output on failure", async () => {
      const { repoRoot } = await writeFixture();
      const exec = vi.fn().mockImplementation(async (command: string[]) => {
        if (command[1] === "up") return { code: 1, stdout: "", stderr: "boom: variables were ANTHROPIC_API_KEY=sk-ant-SECRET etc" };
        return {
          code: 0,
          stdout: command[1] === "domain" ? '{"domain":"demo-linear.up.railway.app"}' : "",
          stderr: "",
        };
      });
      const lines: string[] = [];
      const error = await runDemoDeploy(liveArgs, {
        repoRoot,
        exec,
        env,
        write: (line) => lines.push(line),
      }).catch((caught: unknown) => caught as Error);
      expect(error).toBeInstanceOf(Error);
      expect((error as Error).message).toContain("<redacted>");
      expect((error as Error).message).not.toContain("sk-ant-SECRET");
      expect(lines.join("\n")).not.toContain("sk-ant-SECRET");
    });

    it("scrubs tolerated-failure output too (railway add when the service exists)", async () => {
      const { repoRoot } = await writeFixture();
      const exec = vi.fn().mockImplementation(async (command: string[]) => {
        if (command[1] === "add") return { code: 1, stdout: "", stderr: "exists; env has ANTHROPIC_API_KEY=sk-ant-SECRET" };
        return {
          code: 0,
          stdout: command[1] === "domain" ? '{"domain":"demo-linear.up.railway.app"}' : "",
          stderr: "",
        };
      });
      const lines: string[] = [];
      await runDemoDeploy({ ...liveArgs, skipRegistry: true }, { repoRoot, exec, env, write: (line) => lines.push(line) });
      const output = lines.join("\n");
      expect(output).toContain("<redacted>");
      expect(output).not.toContain("sk-ant-SECRET");
    });
  });
});
