import { spawn } from "node:child_process";
import { existsSync } from "node:fs";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import type { DemoConfig } from "demo-template/demo-config";
import { displayAppPath } from "./create.js";

/**
 * `demo:deploy` — ship one generated demo app to Railway and register it with
 * the demos.vendo.run router (tools/demo-router). One Railway service per
 * demo inside the shared project (default `vendo-demos`), deployed from the
 * repo-root working tree via `railway up` so untracked scratch demos deploy
 * without committing them: the generated per-app Dockerfile does the monorepo
 * build (demo-bank's turbo-filter pattern) and RAILWAY_DOCKERFILE_PATH points
 * the builder at it.
 *
 * CLI syntax below was verified against railway CLI 4.36.1 (`--help` probes);
 * the live path is exercised in the bring-up task, so every step fails with a
 * clear message rather than guessing at recovery.
 */

export interface DemoDeployArgs {
  /** App directory, repo-root-relative (the documented `--app apps/demo-<id>` shape). */
  app: string;
  /** Railway project that owns the router + all demo services. */
  project: string;
  /** Router base URL whose /admin/demos API receives the registry row. */
  routerUrl: string;
  /** Skip the router registration step. */
  skipRegistry: boolean;
  /** Print the command plan (secrets redacted) without executing anything. */
  dryRun: boolean;
}

export interface DeployStep {
  /** argv, exec'd without a shell (secret-safe: no quoting layer). */
  command: string[];
  /** Human-safe rendering — secrets are redacted here and ONLY real values live in `command`. */
  display: string;
  /** Non-zero exit is tolerated (e.g. `railway add` when the service already exists). */
  allowFailure?: boolean;
}

export interface ExecResult {
  code: number;
  stdout: string;
  stderr: string;
}

export type ExecFn = (command: string[], options: { cwd: string }) => Promise<ExecResult>;

export interface DemoDeployResult {
  serviceName: string;
  appPath: string;
  dryRun: boolean;
  domain?: string;
  registryPayload?: RegistryPayload;
}

export interface RegistryPayload {
  id: string;
  url: string;
  prospect: string;
  expiresAt: string;
}

/** Marks docker files we generated; a file without it is hand-edited and is never overwritten. */
export const GENERATED_FILE_MARKER = "Generated by `demo:deploy` (bench/src/demo-creator/deploy.ts) — regenerated on every deploy; delete this line to hand-maintain.";

const defaultProject = "vendo-demos";
const defaultRouterUrl = "https://demos.vendo.run";

const valueOptions = new Set(["--app", "--project", "--router-url"]);
const flagOptions = new Set(["--skip-registry", "--dry-run"]);

const localhostNames = new Set(["localhost", "127.0.0.1", "[::1]", "::1"]);

/** Router URLs must be https (the bearer token rides on every request);
 * plain http is allowed only against localhost. Trailing slashes are
 * stripped so `/admin/demos` paths append cleanly. Shared with reap.ts. */
export function normalizeRouterUrl(option: string, value: string): string {
  let parsed: URL | undefined;
  try {
    parsed = new URL(value);
  } catch {
    parsed = undefined;
  }
  const isHttps = parsed?.protocol === "https:";
  const isLocalHttp = parsed?.protocol === "http:" && localhostNames.has(parsed.hostname);
  if (parsed === undefined || (!isHttps && !isLocalHttp)) {
    throw new Error(`${option} must be https (http is allowed only for localhost) — received ${value}`);
  }
  return value.replace(/\/+$/, "");
}

export function parseDemoDeployArgs(argv: string[]): DemoDeployArgs {
  const normalizedArgv = argv[0] === "--" ? argv.slice(1) : argv;
  const options = new Map<string, string>();
  const flags = new Set<string>();
  for (let index = 0; index < normalizedArgv.length; index += 1) {
    const option = normalizedArgv[index];
    if (!option?.startsWith("--")) throw new Error(`Unexpected argument: ${option ?? ""}`);
    if (flagOptions.has(option)) {
      flags.add(option);
      continue;
    }
    if (!valueOptions.has(option)) throw new Error(`Unknown option: ${option}`);
    const value = normalizedArgv[index + 1];
    if (value === undefined || value.startsWith("--")) throw new Error(`${option} requires a value`);
    options.set(option, value);
    index += 1;
  }
  const app = options.get("--app");
  if (app === undefined) throw new Error("--app is required (e.g. --app apps/demo-linear)");
  return {
    app,
    project: options.get("--project") ?? defaultProject,
    routerUrl: normalizeRouterUrl("--router-url", options.get("--router-url") ?? defaultRouterUrl),
    skipRegistry: flags.has("--skip-registry"),
    dryRun: flags.has("--dry-run"),
  };
}

/** demo-bank's Dockerfile, parametrized: repo-root build context, turbo filter = the app's package name. */
export function renderDockerfile(options: { packageName: string; appPath: string }): string {
  return `# ${GENERATED_FILE_MARKER}
FROM node:22-bookworm-slim

WORKDIR /app
RUN npm install --global pnpm@9.12.0

COPY . .
RUN pnpm install --frozen-lockfile
RUN pnpm exec turbo run build --filter=${options.packageName}

ENV NODE_ENV=production
ENV HOSTNAME=0.0.0.0
ENV PORT=3000

EXPOSE 3000
WORKDIR /app/${options.appPath}
CMD ["pnpm", "start"]
`;
}

/** Write only files that are absent or that we generated (marker present) — never clobber hand edits. */
export function shouldWriteGeneratedFile(existing: string | undefined): boolean {
  return existing === undefined || existing.includes(GENERATED_FILE_MARKER);
}

/**
 * Extract the service's public domain from `railway domain --service X --json`
 * output. The exact JSON shape is not documented, so parse liberally: any JSON
 * line with a string `domain` field, else the first *.up.railway.app match.
 */
export function parseRailwayDomain(output: string): string | undefined {
  const normalize = (value: string): string => value.replace(/^https?:\/\//, "").replace(/\/+$/, "");
  for (const candidate of [output, ...output.split("\n")]) {
    try {
      const parsed: unknown = JSON.parse(candidate.trim());
      if (typeof parsed === "object" && parsed !== null) {
        const domain = (parsed as { domain?: unknown }).domain;
        if (typeof domain === "string" && domain.length > 0) return normalize(domain);
      }
    } catch {
      // not JSON — fall through to the regex
    }
  }
  const match = /(?:https?:\/\/)?([a-z0-9][a-z0-9-]*(?:\.[a-z0-9-]+)*\.up\.railway\.app)/i.exec(output);
  return match?.[1];
}

export function buildRegistryPayload(config: Pick<DemoConfig, "id" | "prospect" | "expiresAt">, domain: string): RegistryPayload {
  const bare = domain.replace(/^https?:\/\//, "").replace(/\/+$/, "");
  return {
    id: config.id,
    url: `https://${bare}`,
    prospect: config.prospect,
    expiresAt: config.expiresAt,
  };
}

export interface DeployPlan {
  /** link, add, domain — everything that must run BEFORE the public domain is known. */
  prepare: DeployStep[];
  /**
   * variables + up, parametrized by the service's public base URL (from the
   * prepare phase's `railway domain` output; the dry run passes a placeholder).
   */
  finalize(publicBaseUrl: string): DeployStep[];
}

/**
 * The railway CLI drive, as data. Verified against railway 4.36.1:
 * `add --service <name> --json`, `domain --service <name> --json`,
 * `variables --set K=V ... --service <name> --skip-deploys`, `up --service
 * <name> --detach`. All run from the repo root (the linked directory), which
 * is also `railway up`'s upload context.
 *
 * Two phases because the domain must exist BEFORE variables are set:
 * Railway's TLS proxy hands the app a proxy-internal origin, so the app
 * rewrites its self-call origin from VENDO_BASE_URL (see
 * apps/demo-template/src/vendo/request.ts) — which needs the public domain,
 * and `railway domain` happily mints it pre-deploy. `up` runs last so the
 * one deploy already has every variable in place.
 */
export function buildDeployPlan(options: {
  serviceName: string;
  project: string;
  dockerfilePath: string;
  anthropicApiKey: string;
}): DeployPlan {
  const { serviceName, project, dockerfilePath, anthropicApiKey } = options;
  const asDisplay = (command: string[]): string =>
    command.map((part) => (part.startsWith("ANTHROPIC_API_KEY=") ? "ANTHROPIC_API_KEY=<redacted>" : part)).join(" ");
  const step = (command: string[], allowFailure?: boolean): DeployStep => ({
    command,
    display: asDisplay(command),
    ...(allowFailure === undefined ? {} : { allowFailure }),
  });
  return {
    prepare: [
      step(["railway", "link", "--project", project]),
      // Fails when the service already exists — that is fine, we then deploy onto it.
      step(["railway", "add", "--service", serviceName, "--json"], true),
      step(["railway", "domain", "--service", serviceName, "--json"]),
    ],
    finalize: (publicBaseUrl) => [
      step([
        "railway", "variables",
        "--set", `ANTHROPIC_API_KEY=${anthropicApiKey}`,
        "--set", "NODE_ENV=production",
        "--set", `RAILWAY_DOCKERFILE_PATH=${dockerfilePath}`,
        "--set", `VENDO_BASE_URL=${publicBaseUrl}`,
        "--service", serviceName,
        "--skip-deploys",
      ]),
      step(["railway", "up", "--service", serviceName, "--detach"]),
    ],
  };
}

/** Loaded lazily for the same reason as create.ts: the schema resolves to TS
 * source that node executes via type stripping (Node >= 23.6), while bench's
 * engines floor is >= 20 — only the demo-creator commands pay this cost. */
async function loadDemoConfigModule(): Promise<typeof import("demo-template/demo-config")> {
  try {
    return await import("demo-template/demo-config");
  } catch (error) {
    throw new Error(
      "demo:deploy needs Node >= 23.6 (native TypeScript type stripping) to load the template's own demo.config schema. "
      + `(${error instanceof Error ? error.message : String(error)})`,
    );
  }
}

/** Shared spawn-based exec (argv array, no shell — secrets and ids are never
 * interpolated into a command string). Also used by reap.ts. */
export const defaultExec: ExecFn = (command, options) =>
  new Promise((resolve, reject) => {
    const [file, ...args] = command;
    if (file === undefined) {
      reject(new Error("empty command"));
      return;
    }
    const child = spawn(file, args, { cwd: options.cwd, stdio: ["ignore", "pipe", "pipe"] });
    let stdout = "";
    let stderr = "";
    child.stdout.on("data", (chunk: Buffer) => { stdout += chunk.toString(); });
    child.stderr.on("data", (chunk: Buffer) => { stderr += chunk.toString(); });
    child.on("error", reject);
    child.on("close", (code) => resolve({ code: code ?? 1, stdout, stderr }));
  });

export interface DeployIo {
  repoRoot: string;
  exec?: ExecFn;
  fetchImpl?: typeof fetch;
  env?: NodeJS.ProcessEnv;
  write?: (line: string) => void;
}

async function readIfExists(filePath: string): Promise<string | undefined> {
  return existsSync(filePath) ? await readFile(filePath, "utf8") : undefined;
}

export async function runDemoDeploy(args: DemoDeployArgs, io: DeployIo): Promise<DemoDeployResult> {
  const exec = io.exec ?? defaultExec;
  const fetchImpl = io.fetchImpl ?? fetch;
  const env = io.env ?? process.env;
  const write = io.write ?? ((line: string) => process.stdout.write(`${line}\n`));

  // (1) Locate + validate the app. `railway up` uploads the repo root, so the
  // app must live inside it for the Dockerfile to see it.
  const appDir = path.resolve(io.repoRoot, args.app);
  const appPath = displayAppPath(io.repoRoot, appDir);
  if (path.isAbsolute(appPath)) {
    throw new Error(`--app must point inside the repo root (the railway build context); "${args.app}" resolves outside it`);
  }
  const configPath = path.join(appDir, "demo.config.json");
  if (!existsSync(configPath)) {
    throw new Error(`No demo.config.json in "${appDir}" — is ${args.app} a generated demo app?`);
  }
  const { parseDemoConfig } = await loadDemoConfigModule();
  const config = parseDemoConfig(JSON.parse(await readFile(configPath, "utf8")), `demo config at "${configPath}"`);
  const packageJson = JSON.parse(await readFile(path.join(appDir, "package.json"), "utf8")) as { name?: string };
  const packageName = packageJson.name;
  if (packageName === undefined) throw new Error(`"${appPath}/package.json" has no name — turbo needs it as the build filter`);
  const serviceName = `demo-${config.id}`;

  // (2) Render the Dockerfile (only when absent or previously generated by
  // us). No per-app .dockerignore: the build context is the REPO ROOT, so
  // Docker only honors the root .dockerignore — that (committed) file is the
  // real upload/exclusion mechanism.
  const dockerfilePath = path.join(appDir, "Dockerfile");
  if (shouldWriteGeneratedFile(await readIfExists(dockerfilePath))) {
    await writeFile(dockerfilePath, renderDockerfile({ packageName, appPath }));
    write(`Wrote ${appPath}/Dockerfile`);
  } else {
    write(`Keeping hand-edited ${appPath}/Dockerfile (no generated-file marker)`);
  }

  // (3) Drive the railway CLI.
  const anthropicApiKey = env.ANTHROPIC_API_KEY;
  if (!args.dryRun && (anthropicApiKey === undefined || anthropicApiKey === "")) {
    throw new Error("ANTHROPIC_API_KEY must be set in the environment — the demo service needs it (it is never logged)");
  }
  const plan = buildDeployPlan({
    serviceName,
    project: args.project,
    dockerfilePath: `${appPath}/Dockerfile`,
    anthropicApiKey: anthropicApiKey ?? "<from env at deploy time>",
  });

  if (args.dryRun) {
    write(`Dry run — plan for ${appPath} (service ${serviceName}, project ${args.project}):`);
    const steps = [...plan.prepare, ...plan.finalize("<from railway domain>")];
    for (const step of steps) write(`  ${step.display}${step.allowFailure === true ? "   # tolerated if the service already exists" : ""}`);
    if (args.skipRegistry) {
      write("  (registry registration skipped: --skip-registry)");
    } else {
      const payload = buildRegistryPayload(config, "<railway domain>");
      write(`  POST ${args.routerUrl}/admin/demos   # Bearer $ROUTER_ADMIN_TOKEN, body ${JSON.stringify(payload)}`);
    }
    return { serviceName, appPath, dryRun: true };
  }

  // Child output can echo the environment (railway prints variables on some
  // errors) — scrub the key out of ANYTHING we relay from a child process.
  const scrub = (text: string): string =>
    anthropicApiKey === undefined || anthropicApiKey === "" ? text : text.replaceAll(anthropicApiKey, "<redacted>");

  // (2.5) `railway up` archives the whole working tree, including untracked
  // scratch demo apps, so the uploaded pnpm-lock.yaml must cover every
  // workspace app or the Dockerfile's `pnpm install --frozen-lockfile` fails
  // on an unrelated demo. --lockfile-only syncs the lockfile without touching
  // node_modules.
  write("$ pnpm install --lockfile-only   # sync lockfile with the upload's workspace");
  const lockSync = await exec(["pnpm", "install", "--lockfile-only"], { cwd: io.repoRoot });
  if (lockSync.code !== 0) {
    throw new Error(`"pnpm install --lockfile-only" failed (exit ${lockSync.code}):\n${scrub(lockSync.stderr || lockSync.stdout)}`);
  }

  const runStep = async (step: DeployStep): Promise<ExecResult | undefined> => {
    write(`$ ${step.display}`);
    const result = await exec(step.command, { cwd: io.repoRoot });
    if (result.code !== 0) {
      if (step.allowFailure === true) {
        write(`  (non-fatal, continuing) ${scrub(firstLine(result.stderr) ?? firstLine(result.stdout) ?? `exit ${result.code}`)}`);
        return undefined;
      }
      throw new Error(`"${step.display}" failed (exit ${result.code}):\n${scrub(result.stderr || result.stdout)}`);
    }
    return result;
  };

  // Prepare phase: link, add, domain. The domain step's output is the single
  // source of the public domain — reused for VENDO_BASE_URL AND the registry
  // row (never a second `railway domain` call).
  let domainOutput = "";
  for (const step of plan.prepare) {
    const result = await runStep(step);
    if (result !== undefined && step.command[1] === "domain") domainOutput = `${result.stdout}\n${result.stderr}`;
  }
  const domain = parseRailwayDomain(domainOutput);
  if (domain === undefined) {
    throw new Error(
      `Could not find the service domain in \`railway domain\` output — check \`railway domain --service ${serviceName}\` manually.\nOutput was:\n${scrub(domainOutput)}`,
    );
  }
  write(`Service domain: https://${domain}`);

  // Finalize phase: variables (incl. VENDO_BASE_URL) land BEFORE the one
  // deploy, so the app boots already knowing its public origin.
  for (const step of plan.finalize(`https://${domain}`)) {
    await runStep(step);
  }

  // (4) Register with the router.
  if (args.skipRegistry) {
    write("Skipping router registration (--skip-registry)");
    return { serviceName, appPath, dryRun: false, domain };
  }
  const token = env.ROUTER_ADMIN_TOKEN;
  if (token === undefined || token === "") {
    throw new Error("ROUTER_ADMIN_TOKEN must be set to register the demo (or pass --skip-registry)");
  }
  const registryPayload = buildRegistryPayload(config, domain);
  const response = await fetchImpl(`${args.routerUrl}/admin/demos`, {
    method: "POST",
    headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" },
    body: JSON.stringify(registryPayload),
  });
  if (response.status === 409) {
    throw new Error(formatSlugConflict(config.id, await response.text()));
  }
  if (!response.ok) {
    throw new Error(`Router registration failed: ${response.status} ${await response.text()}`);
  }
  write(`Registered: ${args.routerUrl.replace(/\/+$/, "")}/${config.id} -> ${registryPayload.url} (expires ${registryPayload.expiresAt})`);
  return { serviceName, appPath, dryRun: false, domain, registryPayload };
}

/** Turn the router's 409 body ({ error: "id taken", existing: {...} }) into an
 * actionable operator error: name the prospect holding the slug and point at
 * the fix (a semantic variant slug + a fresh demo:create). Robust to bodies
 * that are not the expected JSON shape. */
export function formatSlugConflict(id: string, responseBody: string): string {
  let holder = "another demo";
  try {
    const parsed = JSON.parse(responseBody) as { existing?: { prospect?: unknown; url?: unknown; expiresAt?: unknown } };
    const existing = parsed.existing;
    if (existing !== undefined && typeof existing.prospect === "string") {
      const detail = [
        typeof existing.url === "string" ? existing.url : undefined,
        typeof existing.expiresAt === "string" ? `expires ${existing.expiresAt}` : undefined,
      ].filter((part) => part !== undefined).join(", ");
      holder = `prospect "${existing.prospect}"${detail.length > 0 ? ` (${detail})` : ""}`;
    }
  } catch {
    // body was not the router's JSON shape — the generic message still names the slug and the fix
  }
  return (
    `Demo slug "${id}" is already taken by ${holder} — the router refused to overwrite it. `
    + `Pick a variant slug (semantic, e.g. "mercury-bank" rather than a numbered suffix) and re-run demo:create with it.`
  );
}

function firstLine(text: string): string | undefined {
  const line = text.split("\n").find((candidate) => candidate.trim().length > 0);
  return line?.trim();
}
