import { existsSync } from "node:fs";
import { mkdir, mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { describe, expect, it, vi } from "vitest";
import {
  buildDeployPlan,
  buildRegistryPayload,
  GENERATED_FILE_MARKER,
  parseDemoDeployArgs,
  parseRailwayDomain,
  renderDockerfile,
  runDemoDeploy,
  shouldWriteGeneratedFile,
} from "./deploy.js";

describe("parseDemoDeployArgs", () => {
  it("parses a fully specified deploy", () => {
    expect(parseDemoDeployArgs([
      "--app", "apps/demo-linear",
      "--project", "other-project",
      "--router-url", "https://router.example",
      "--skip-registry",
      "--dry-run",
    ])).toEqual({
      app: "apps/demo-linear",
      project: "other-project",
      routerUrl: "https://router.example",
      skipRegistry: true,
      dryRun: true,
    });
  });

  it("defaults project, router url, and both flags", () => {
    expect(parseDemoDeployArgs(["--app", "apps/demo-linear"])).toEqual({
      app: "apps/demo-linear",
      project: "vendo-demos",
      routerUrl: "https://demos.vendo.run",
      skipRegistry: false,
      dryRun: false,
    });
  });

  it("accepts the literal separator forwarded by pnpm scripts", () => {
    expect(parseDemoDeployArgs(["--", "--app", "apps/demo-linear"])).toMatchObject({ app: "apps/demo-linear" });
  });

  it("requires --app and rejects unknown options and missing values", () => {
    expect(() => parseDemoDeployArgs([])).toThrow("--app is required");
    expect(() => parseDemoDeployArgs(["--app", "apps/x", "--nope"])).toThrow("Unknown option: --nope");
    expect(() => parseDemoDeployArgs(["--app"])).toThrow("--app requires a value");
    expect(() => parseDemoDeployArgs(["--app", "apps/x", "--router-url", "not a url"]))
      .toThrow("--router-url");
  });

  it("requires an https router URL, except for localhost development", () => {
    expect(() => parseDemoDeployArgs(["--app", "apps/x", "--router-url", "http://router.example"]))
      .toThrow(/--router-url must be https/);
    expect(parseDemoDeployArgs(["--app", "apps/x", "--router-url", "http://localhost:8080"]).routerUrl)
      .toBe("http://localhost:8080");
    expect(parseDemoDeployArgs(["--app", "apps/x", "--router-url", "http://127.0.0.1:8080"]).routerUrl)
      .toBe("http://127.0.0.1:8080");
  });

  it("normalizes a trailing slash off the router URL (admin paths append cleanly)", () => {
    expect(parseDemoDeployArgs(["--app", "apps/x", "--router-url", "https://router.example/"]).routerUrl)
      .toBe("https://router.example");
  });
});

describe("Dockerfile rendering", () => {
  it("parametrizes demo-bank's pattern: turbo filter, app WORKDIR, port 3000, marker", () => {
    const dockerfile = renderDockerfile({ packageName: "demo-linear", appPath: "apps/demo-linear" });
    expect(dockerfile).toContain(GENERATED_FILE_MARKER);
    expect(dockerfile).toContain("FROM node:22-bookworm-slim");
    expect(dockerfile).toContain("pnpm exec turbo run build --filter=demo-linear");
    expect(dockerfile).toContain("WORKDIR /app/apps/demo-linear");
    expect(dockerfile).toContain("EXPOSE 3000");
    expect(dockerfile).toContain('CMD ["pnpm", "start"]');
  });

  it("shouldWriteGeneratedFile: absent or previously generated by us, never a hand-edited file", () => {
    expect(shouldWriteGeneratedFile(undefined)).toBe(true);
    expect(shouldWriteGeneratedFile(`# hello\n${GENERATED_FILE_MARKER}\nFROM x\n`)).toBe(true);
    expect(shouldWriteGeneratedFile("FROM node:22\n# hand-written\n")).toBe(false);
  });
});

describe("parseRailwayDomain", () => {
  // Samples are synthetic (probing `railway domain` live creates domains);
  // the parser is deliberately liberal: JSON first, then a domain regex.
  it("parses a --json object payload", () => {
    expect(parseRailwayDomain('{"domain":"demo-linear-production.up.railway.app"}'))
      .toBe("demo-linear-production.up.railway.app");
  });

  it("parses JSON embedded among log lines", () => {
    const output = 'Creating domain...\n{"domain":"https://demo-x.up.railway.app/"}\nDone\n';
    expect(parseRailwayDomain(output)).toBe("demo-x.up.railway.app");
  });

  it("falls back to finding a railway domain in plain text", () => {
    expect(parseRailwayDomain("Service Domain created:\n🚀 https://demo-linear-production.up.railway.app\n"))
      .toBe("demo-linear-production.up.railway.app");
  });

  it("returns undefined when no domain is present", () => {
    expect(parseRailwayDomain("no domains here")).toBeUndefined();
    expect(parseRailwayDomain("")).toBeUndefined();
  });
});

describe("buildRegistryPayload", () => {
  const config = {
    id: "linear",
    prospect: "Linear",
    ctaUrl: "https://cal.com/yousefhelal",
    beats: [],
    caps: { maxTurns: 20, maxSpendUsd: 5 },
    expiresAt: "2026-08-01T00:00:00Z",
  };

  it("builds the router admin row from the config and the railway domain", () => {
    expect(buildRegistryPayload(config, "demo-linear.up.railway.app")).toEqual({
      id: "linear",
      url: "https://demo-linear.up.railway.app",
      prospect: "Linear",
      expiresAt: "2026-08-01T00:00:00Z",
    });
  });

  it("normalizes a domain that arrives with protocol or trailing slash", () => {
    expect(buildRegistryPayload(config, "https://demo-linear.up.railway.app/").url)
      .toBe("https://demo-linear.up.railway.app");
  });
});

describe("buildDeployPlan", () => {
  const plan = buildDeployPlan({
    serviceName: "demo-linear",
    project: "vendo-demos",
    dockerfilePath: "apps/demo-linear/Dockerfile",
    anthropicApiKey: "sk-ant-SECRET",
  });

  it("drives the verified railway CLI syntax in order: link, add, variables, up, domain", () => {
    expect(plan.map((step) => step.command.slice(0, 2).join(" "))).toEqual([
      "railway link",
      "railway add",
      "railway variables",
      "railway up",
      "railway domain",
    ]);
    const [link, add, variables, up, domain] = plan;
    expect(link?.command).toEqual(["railway", "link", "--project", "vendo-demos"]);
    expect(add?.command).toEqual(["railway", "add", "--service", "demo-linear", "--json"]);
    expect(variables?.command).toEqual([
      "railway", "variables",
      "--set", "ANTHROPIC_API_KEY=sk-ant-SECRET",
      "--set", "NODE_ENV=production",
      "--set", "RAILWAY_DOCKERFILE_PATH=apps/demo-linear/Dockerfile",
      "--service", "demo-linear",
      "--skip-deploys",
    ]);
    expect(up?.command).toEqual(["railway", "up", "--service", "demo-linear", "--detach"]);
    expect(domain?.command).toEqual(["railway", "domain", "--service", "demo-linear", "--json"]);
  });

  it("NEVER exposes the anthropic key in the display rendering", () => {
    for (const step of plan) {
      expect(step.display).not.toContain("sk-ant-SECRET");
    }
    expect(plan[2]?.display).toContain("ANTHROPIC_API_KEY=<redacted>");
  });

  it("tolerates `railway add` failing when the service already exists", () => {
    expect(plan[1]?.allowFailure).toBe(true);
    expect(plan.filter((step) => step.allowFailure !== true)).toHaveLength(4);
  });
});

describe("runDemoDeploy (dry run against a fixture app)", () => {
  const demoConfig = {
    id: "linear",
    prospect: "Linear",
    ctaUrl: "https://cal.com/yousefhelal",
    beats: [{ key: "generate-ui", prompt: "Show me", chip: "Show me" }],
    caps: { maxTurns: 20, maxSpendUsd: 5 },
    expiresAt: "2026-08-01T00:00:00Z",
  };

  async function writeFixture(): Promise<{ repoRoot: string; appDir: string }> {
    const repoRoot = await mkdtemp(path.join(tmpdir(), "vendo-demo-deploy-"));
    const appDir = path.join(repoRoot, "apps", "demo-linear");
    await mkdir(appDir, { recursive: true });
    await writeFile(path.join(appDir, "package.json"), `${JSON.stringify({ name: "demo-linear", private: true }, null, 2)}\n`);
    await writeFile(path.join(appDir, "demo.config.json"), `${JSON.stringify(demoConfig, null, 2)}\n`);
    return { repoRoot, appDir };
  }

  const args = {
    app: "apps/demo-linear",
    project: "vendo-demos",
    routerUrl: "https://demos.vendo.run",
    skipRegistry: false,
    dryRun: true,
  };

  it("validates the config, renders the Dockerfile, and prints the plan without executing", async () => {
    const { repoRoot, appDir } = await writeFixture();
    const exec = vi.fn();
    const fetchImpl = vi.fn();
    const lines: string[] = [];
    const result = await runDemoDeploy(args, {
      repoRoot,
      exec,
      fetchImpl: fetchImpl as unknown as typeof fetch,
      env: {},
      write: (line) => lines.push(line),
    });
    expect(result.dryRun).toBe(true);
    expect(result.serviceName).toBe("demo-linear");
    expect(exec).not.toHaveBeenCalled();
    expect(fetchImpl).not.toHaveBeenCalled();
    const dockerfile = await readFile(path.join(appDir, "Dockerfile"), "utf8");
    expect(dockerfile).toContain(GENERATED_FILE_MARKER);
    expect(dockerfile).toContain("--filter=demo-linear");
    // The upload-exclusion mechanism is the repo-root .dockerignore; a
    // per-app one would be inert (Docker only honors the context root's).
    expect(existsSync(path.join(appDir, ".dockerignore"))).toBe(false);
    const output = lines.join("\n");
    expect(output).toContain("railway up --service demo-linear --detach");
    expect(output).toContain("POST https://demos.vendo.run/admin/demos");
    expect(output).not.toContain("sk-ant");
  });

  it("keeps a hand-edited Dockerfile instead of clobbering it", async () => {
    const { repoRoot, appDir } = await writeFixture();
    await writeFile(path.join(appDir, "Dockerfile"), "FROM scratch\n# hand-tuned\n");
    await runDemoDeploy(args, { repoRoot, env: {}, write: () => {} });
    expect(await readFile(path.join(appDir, "Dockerfile"), "utf8")).toBe("FROM scratch\n# hand-tuned\n");
  });

  it("refuses an app directory outside the repo root (the build context)", async () => {
    const { repoRoot } = await writeFixture();
    await expect(runDemoDeploy({ ...args, app: "../elsewhere" }, { repoRoot, env: {}, write: () => {} }))
      .rejects.toThrow(/inside the repo/);
  });

  it("refuses to run live without ANTHROPIC_API_KEY", async () => {
    const { repoRoot } = await writeFixture();
    await expect(runDemoDeploy({ ...args, dryRun: false }, { repoRoot, env: {}, write: () => {} }))
      .rejects.toThrow(/ANTHROPIC_API_KEY/);
  });

  it("surfaces a broken demo.config.json loudly", async () => {
    const { repoRoot, appDir } = await writeFixture();
    await writeFile(path.join(appDir, "demo.config.json"), JSON.stringify({ ...demoConfig, id: "Not A Slug" }));
    await expect(runDemoDeploy(args, { repoRoot, env: {}, write: () => {} }))
      .rejects.toThrow(/id: must be lowercase alphanumeric with hyphens/);
  });

  describe("live path (mock exec)", () => {
    const env = { ANTHROPIC_API_KEY: "sk-ant-SECRET", ROUTER_ADMIN_TOKEN: "token" };
    const liveArgs = { ...args, dryRun: false };

    function happyExec() {
      return vi.fn().mockImplementation(async (command: string[]) => ({
        code: 0,
        stdout: command[1] === "domain" ? '{"domain":"demo-linear-production.up.railway.app"}' : "",
        stderr: "",
      }));
    }

    it("runs the lockfile preflight, then the railway plan, then registers with the router", async () => {
      const { repoRoot } = await writeFixture();
      const exec = happyExec();
      const fetchImpl = vi.fn().mockResolvedValue(new Response("{}", { status: 200 }));
      const result = await runDemoDeploy(liveArgs, {
        repoRoot,
        exec,
        fetchImpl: fetchImpl as unknown as typeof fetch,
        env,
        write: () => {},
      });
      const commands = exec.mock.calls.map(([command]) => (command as string[]).join(" "));
      // `railway up` archives the working tree, so the lockfile must be
      // synced BEFORE any railway step (untracked scratch apps otherwise
      // break --frozen-lockfile inside the image build).
      expect(commands[0]).toBe("pnpm install --lockfile-only");
      expect(commands.slice(1)).toEqual([
        "railway link --project vendo-demos",
        "railway add --service demo-linear --json",
        "railway variables --set ANTHROPIC_API_KEY=sk-ant-SECRET --set NODE_ENV=production --set RAILWAY_DOCKERFILE_PATH=apps/demo-linear/Dockerfile --service demo-linear --skip-deploys",
        "railway up --service demo-linear --detach",
        "railway domain --service demo-linear --json",
      ]);
      expect(result.domain).toBe("demo-linear-production.up.railway.app");
      expect(fetchImpl).toHaveBeenCalledWith("https://demos.vendo.run/admin/demos", expect.objectContaining({ method: "POST" }));
      expect(result.registryPayload).toEqual({
        id: "linear",
        url: "https://demo-linear-production.up.railway.app",
        prospect: "Linear",
        expiresAt: "2026-08-01T00:00:00Z",
      });
    });

    it("scrubs the anthropic key out of echoed child output on failure", async () => {
      const { repoRoot } = await writeFixture();
      const exec = vi.fn().mockImplementation(async (command: string[]) =>
        command[1] === "up"
          ? { code: 1, stdout: "", stderr: "boom: variables were ANTHROPIC_API_KEY=sk-ant-SECRET etc" }
          : { code: 0, stdout: "", stderr: "" });
      const lines: string[] = [];
      const error = await runDemoDeploy(liveArgs, {
        repoRoot,
        exec,
        env,
        write: (line) => lines.push(line),
      }).catch((caught: unknown) => caught as Error);
      expect(error).toBeInstanceOf(Error);
      expect((error as Error).message).toContain("<redacted>");
      expect((error as Error).message).not.toContain("sk-ant-SECRET");
      expect(lines.join("\n")).not.toContain("sk-ant-SECRET");
    });

    it("scrubs tolerated-failure output too (railway add when the service exists)", async () => {
      const { repoRoot } = await writeFixture();
      const exec = vi.fn().mockImplementation(async (command: string[]) => {
        if (command[1] === "add") return { code: 1, stdout: "", stderr: "exists; env has ANTHROPIC_API_KEY=sk-ant-SECRET" };
        return {
          code: 0,
          stdout: command[1] === "domain" ? '{"domain":"demo-linear.up.railway.app"}' : "",
          stderr: "",
        };
      });
      const lines: string[] = [];
      await runDemoDeploy({ ...liveArgs, skipRegistry: true }, { repoRoot, exec, env, write: (line) => lines.push(line) });
      const output = lines.join("\n");
      expect(output).toContain("<redacted>");
      expect(output).not.toContain("sk-ant-SECRET");
    });
  });
});
