/**
 * The human-readable half of a measurement artifact: distribution tables, the
 * escape-shaped outliers, and (with a `--compare` arm) the before/after table.
 */
import type { AppMeasurement, Summary } from "./metrics";

export interface Arm {
  summary: Summary;
  rows: AppMeasurement[];
}

const pct = (part: number, whole: number): string =>
  whole === 0 ? "—" : `${((part / whole) * 100).toFixed(0)}% (${part}/${whole})`;

const ratio = (value: number): string => value.toFixed(2);

const truncate = (text: string, max = 58): string =>
  text.length <= max ? text : `${text.slice(0, max - 1)}…`;

const distribution = ({ summary }: Arm): string => {
  const { ok } = summary;
  return [
    "| metric | value |",
    "| --- | --- |",
    `| apps generated | ${summary.apps} |`,
    `| failed | ${pct(summary.failed, summary.apps)} |`,
    `| duration p50 / p90 | ${(summary.durationMsP50 / 1000).toFixed(1)}s / ${(summary.durationMsP90 / 1000).toFixed(1)}s |`,
    `| apps with ≥1 island | ${pct(summary.withIslands, ok)} |`,
    `| island-source ratio p50 / p90 | ${ratio(summary.islandRatioP50)} / ${ratio(summary.islandRatioP90)} |`,
    `| ratio > 0.4 | ${pct(summary.islandRatioOver["0.4"], ok)} |`,
    `| ratio > 0.5 | ${pct(summary.islandRatioOver["0.5"], ok)} |`,
    `| **ratio > 0.6** | ${pct(summary.islandRatioOver["0.6"], ok)} |`,
    `| ratio > 0.8 | ${pct(summary.islandRatioOver["0.8"], ok)} |`,
    `| **islands ≥ 1 and queries == 0** | ${pct(summary.zeroQueryIsland, ok)} |`,
    `| ↳ island reads tools but no query (escape) | ${pct(summary.islandReadsWithoutQueries, ok)} |`,
    `| ↳ island uses no tools at all (data-free utility) | ${pct(summary.dataFreeUtility, ok)} |`,
    `| island reaches a MUTATING tool | ${pct(summary.mutatingIslandTools, ok)} |`,
    "",
    "island-ratio histogram (OK apps):",
    "",
    "| bucket | apps |",
    "| --- | --- |",
    ...Object.entries(summary.islandRatioHistogram).map(([bucket, count]) => `| ${bucket} | ${count} |`),
  ].join("\n");
};

const outliers = ({ rows }: Arm): string => {
  const flagged = rows
    .filter((row) => row.status === "ok" && (row.islandRatio > 0.5 || row.zeroQueryIsland))
    .sort((a, b) => b.islandRatio - a.islandRatio);
  if (flagged.length === 0) return "_none_";
  return [
    "| host | prompt | ratio | islands | queries | nodes | island tools |",
    "| --- | --- | --- | --- | --- | --- | --- |",
    ...flagged.map((row) => `| ${row.host} | ${truncate(row.prompt)} | ${ratio(row.islandRatio)} | ${row.islandCount} | ${row.queryCount} | ${row.nodeCount} | ${[...row.islandToolReads, ...row.islandToolWrites.map((tool) => `**${tool}**`)].join(", ") || "—"} |`),
  ].join("\n");
};

const mutating = ({ rows }: Arm): string => {
  const flagged = rows.filter((row) => row.mutatingIslandTools);
  if (flagged.length === 0) return "_none_";
  return [
    "| host | prompt | mutating tools called from island source |",
    "| --- | --- | --- |",
    ...flagged.map((row) => `| ${row.host} | ${truncate(row.prompt, 70)} | ${row.islandToolWrites.join(", ")} |`),
  ].join("\n");
};

const comparison = (after: Arm, before: Arm): string => {
  const a = after.summary;
  const b = before.summary;
  const line = (name: string, beforeText: string, afterText: string) => `| ${name} | ${beforeText} | ${afterText} |`;
  return [
    `| metric | before (${b.label}) | after (${a.label}) |`,
    "| --- | --- | --- |",
    line("apps generated", String(b.apps), String(a.apps)),
    line("failure rate", pct(b.failed, b.apps), pct(a.failed, a.apps)),
    line("duration p50", `${(b.durationMsP50 / 1000).toFixed(1)}s`, `${(a.durationMsP50 / 1000).toFixed(1)}s`),
    line("duration p90", `${(b.durationMsP90 / 1000).toFixed(1)}s`, `${(a.durationMsP90 / 1000).toFixed(1)}s`),
    line("apps with ≥1 island", pct(b.withIslands, b.ok), pct(a.withIslands, a.ok)),
    line("island ratio p50", ratio(b.islandRatioP50), ratio(a.islandRatioP50)),
    line("island ratio p90", ratio(b.islandRatioP90), ratio(a.islandRatioP90)),
    line("ratio > 0.6", pct(b.islandRatioOver["0.6"], b.ok), pct(a.islandRatioOver["0.6"], a.ok)),
    line("islands ≥ 1, queries == 0", pct(b.zeroQueryIsland, b.ok), pct(a.zeroQueryIsland, a.ok)),
    line("↳ escape (island reads tools)", pct(b.islandReadsWithoutQueries, b.ok), pct(a.islandReadsWithoutQueries, a.ok)),
    line("↳ data-free utility (no tools)", pct(b.dataFreeUtility, b.ok), pct(a.dataFreeUtility, a.ok)),
    line("island reaches mutating tool", pct(b.mutatingIslandTools, b.ok), pct(a.mutatingIslandTools, a.ok)),
  ].join("\n");
};

export function renderMarkdown(after: Arm, before?: Arm): string {
  const sections = [
    `# Island-escape measurement — \`${after.summary.label}\``,
    "",
    `Vendo lane only, every committed pack against both hosts, engine default model. Generated by \`measure/cli.ts\` from \`runs/_measure/${after.summary.label}\`; rows live in the sibling .json.`,
    "",
    "## Distribution",
    "",
    distribution(after),
    "",
    "## Escape-shaped apps (ratio > 0.5 or island-with-no-queries)",
    "",
    outliers(after),
    "",
    "## Mutating tools reached from island source — HUMAN READ",
    "",
    "Intent is not automatable: read each row and ask whether the tool's job matches the app's ask (the live defect repurposed a money-transfer tool to fake a Slack message).",
    "",
    mutating(after),
  ];
  if (before !== undefined) {
    sections.push("", "## Before / after", "", comparison(after, before));
  }
  return `${sections.join("\n")}\n`;
}
