/**
 * Generated by `vendo init` — review and edit freely; this file is yours.
 */
import { z } from "zod";
import type { RegisteredComponent, VendoSchema } from "@vendoai/core";

export const badgeSchema = z.object({
  text: z.string().describe("The text content displayed inside the badge."),
  tone: z.string().optional().describe("Visual tone of the badge: 'neutral', 'positive', or 'negative'. Defaults to 'neutral'."),
});

export const badgeDescriptor: RegisteredComponent = {
  name: "Badge",
  description: "A small pill-shaped label used to highlight status or categorical information. Supports neutral, positive, and negative tones for semantic coloring.",
  propsSchema: badgeSchema as VendoSchema<unknown>,
  source: "host",
};
