import path from "node:path";
import { transform } from "sucrase";
import { writeGenerated } from "../fsx.js";
import type { ComponentAnalysis } from "./analyze.js";
import type { ComponentCandidate } from "./scan.js";

/** Names already taken by the prewired library — generated hosts get a Host prefix. */
const PREWIRED_NAMES = new Set([
  "Card", "Table", "Chart", "Form", "Accordion", "Carousel", "Callout", "Tags",
  "Steps", "List", "Image", "ImageGallery", "Markdown", "CodeBlock", "Tabs", "TimeOfDayClock",
]);

export function registryName(analysis: ComponentAnalysis): string {
  return PREWIRED_NAMES.has(analysis.name) ? `Host${analysis.name}` : analysis.name;
}

function camel(name: string): string {
  return name[0]!.toLowerCase() + name.slice(1);
}

export function zodSource(props: ComponentAnalysis["props"]): string {
  const fields = props.map((p) => {
    let expr =
      p.type === "string" ? "z.string()"
      : p.type === "number" ? "z.number()"
      : p.type === "boolean" ? "z.boolean()"
      : p.type === "string[]" ? "z.array(z.string())"
      : p.type === "number[]" ? "z.array(z.number())"
      : `z.enum([${(p.enumValues ?? []).map((v) => JSON.stringify(v)).join(", ")}])`;
    if (p.optional) expr += ".optional()";
    expr += `.describe(${JSON.stringify(p.description)})`;
    return `  ${p.name}: ${expr},`;
  });
  return `z.object({\n${fields.join("\n")}\n})`;
}

export function descriptorSource(analysis: ComponentAnalysis): string {
  const name = registryName(analysis);
  const c = camel(name);
  return `/**
 * Generated by \`flowlet init\` — review and edit freely; this file is yours.
 */
import { z } from "zod";
import type { RegisteredComponent, FlowletSchema } from "@flowlet/core";

export const ${c}Schema = ${zodSource(analysis.props)};

export const ${c}Descriptor: RegisteredComponent = {
  name: ${JSON.stringify(name)},
  description: ${JSON.stringify(analysis.description)},
  propsSchema: ${c}Schema as FlowletSchema<unknown>,
  source: "host",
};
`;
}

export function implSource(analysis: ComponentAnalysis, candidate: ComponentCandidate): string {
  const name = registryName(analysis);
  const c = camel(name);
  // .flowlet/components/<Name>/impl.tsx -> host file, so hop out three levels.
  const importPath = path.posix.join("../../..", candidate.relFile).replace(/\.tsx?$/, "");
  return `/**
 * Generated by \`flowlet init\` — wraps ${candidate.relFile} for the Flowlet sandbox.
 * Review and edit freely; this file is yours.
 */
import { ${analysis.imports.join(", ")} } from "${importPath}";
import { ${c}Schema } from "./descriptor";

export function ${name}(props: Record<string, unknown>) {
  const parsed = ${c}Schema.safeParse(props);
  if (!parsed.success) {
    return <div data-testid="flowlet-invalid-props">Invalid component props</div>;
  }
  const p = parsed.data;
  return ${analysis.jsx};
}
`;
}

export function entrySource(names: string[]): string {
  const imports = names.map((n) => `import { ${n} } from "./${n}/impl";`).join("\n");
  return `/**
 * Generated by \`flowlet init\`. Sandbox host bundle entry: exposes wrapped host
 * components to the Flowlet stage runtime (window.__FLOWLET_HOST__ contract —
 * see packages/flowlet-components/bundle/entry.ts for the reference bundle).
 * NOTE: merging these with the prewired bundle is host wiring (ENG-186/ENG-202).
 */
import React from "react";
import { createRoot } from "react-dom/client";
${imports}

declare global {
  interface Window {
    __React: typeof React;
    __createRoot: typeof createRoot;
    __FLOWLET_HOST__: Record<string, unknown>;
  }
}

window.__React = React;
window.__createRoot = createRoot;
window.__FLOWLET_HOST__ = { ${names.join(", ")} };
`;
}

export function viteConfigSource(): string {
  return `/** Generated by \`flowlet init\`. Builds the host-component sandbox bundle. */
import { flowletHostPreset } from "@flowlet/stage/build";

export default flowletHostPreset({ entry: "entry.ts", version: "0.0.1" });
`;
}

/** Throws with the sucrase error message when the generated TSX does not parse. */
export function assertParses(fileLabel: string, source: string): void {
  try {
    transform(source, { transforms: ["typescript", "jsx"] });
  } catch (err) {
    throw new Error(`generated ${fileLabel} has a syntax error: ${err instanceof Error ? err.message : String(err)}`);
  }
}

export async function writeComponent(
  targetDir: string,
  analysis: ComponentAnalysis,
  candidate: ComponentCandidate,
  opts: { force: boolean },
): Promise<string> {
  if (!/^[A-Z][A-Za-z0-9]*$/.test(analysis.name)) {
    throw new Error(`component name ${JSON.stringify(analysis.name)} is not PascalCase`);
  }
  const name = registryName(analysis);
  const descriptor = descriptorSource(analysis);
  const impl = implSource(analysis, candidate);
  assertParses(`${name}/descriptor.ts`, descriptor);
  assertParses(`${name}/impl.tsx`, impl);
  const base = path.join(targetDir, ".flowlet/components", name);
  await writeGenerated(path.join(base, "descriptor.ts"), descriptor, opts);
  await writeGenerated(path.join(base, "impl.tsx"), impl, opts);
  return name;
}
