/**
 * Generated by `flowlet init` — wraps src/components/ui/button.tsx for the Flowlet sandbox.
 * Review and edit freely; this file is yours.
 */
import { Button } from "../../../src/components/ui/button";
import { buttonSchema } from "./descriptor";

// Named ButtonWrapper (not Button) so it never collides with the host import.
export function ButtonWrapper(props: Record<string, unknown>) {
  const parsed = buttonSchema.safeParse(props);
  if (!parsed.success) {
    return <div data-testid="flowlet-invalid-props">Invalid component props</div>;
  }
  const p = parsed.data;
  return <Button variant={p.variant} size={p.size} disabled={p.disabled}>{p.label}</Button>;
}
