/**
 * Generated by `flowlet init` — wraps src/components/ui/maple-mark.tsx for the Flowlet sandbox.
 * Review and edit freely; this file is yours.
 */
import { MapleMark } from "../../../src/components/ui/maple-mark";
import { mapleMarkSchema } from "./descriptor";

// Named MapleMarkWrapper (not MapleMark) so it never collides with the host import.
export function MapleMarkWrapper(props: Record<string, unknown>) {
  const parsed = mapleMarkSchema.safeParse(props);
  if (!parsed.success) {
    return <div data-testid="flowlet-invalid-props">Invalid component props</div>;
  }
  const p = parsed.data;
  return <MapleMark className={p.className} />;
}
