/**
 * Generated by `vendo init` — wraps src/components/ui/card.tsx for the Vendo sandbox.
 * Review and edit freely; this file is yours. The wrapper body was LLM-authored:
 * it runs inside the egress-jailed sandbox iframe (F3a CSP), but REVIEW IT like
 * any other generated code before committing.
 */
import { CardHeader } from "../../../src/components/ui/card";
import { cardHeaderSchema } from "./descriptor";

// Named CardHeaderWrapper (not CardHeader) so it never collides with the host import.
export function CardHeaderWrapper(props: Record<string, unknown>) {
  const parsed = cardHeaderSchema.safeParse(props);
  if (!parsed.success) {
    return <div data-testid="vendo-invalid-props">Invalid component props</div>;
  }
  const p = parsed.data;
  return <CardHeader title={p.title} className={p.className} />;
}
