/**
 * Generated by `flowlet init` — wraps src/components/ui/card.tsx for the Flowlet sandbox.
 * Review and edit freely; this file is yours.
 */
import { Card, CardHeader, CardTitle, CardContent } from "../../../src/components/ui/card";
import { hostCardSchema } from "./descriptor";

// Named HostCardWrapper (not HostCard) so it never collides with the host import.
export function HostCardWrapper(props: Record<string, unknown>) {
  const parsed = hostCardSchema.safeParse(props);
  if (!parsed.success) {
    return <div data-testid="flowlet-invalid-props">Invalid component props</div>;
  }
  const p = parsed.data;
  return <Card hover={p.hover}><CardHeader><CardTitle>{p.title}</CardTitle></CardHeader><CardContent><span>{p.content}</span></CardContent></Card>;
}
