/**
 * Generated by `flowlet init` — review and edit freely; this file is yours.
 */
import { z } from "zod";
import type { RegisteredComponent, FlowletSchema } from "@flowlet/core";

export const errorStateSchema = z.object({
  title: z.string().optional().describe("Heading text summarizing the error condition."),
  description: z.string().optional().describe("Supporting text explaining the error and suggesting a recovery action."),
  className: z.string().optional().describe("Additional CSS classes to apply to the root element."),
});

export const errorStateDescriptor: RegisteredComponent = {
  name: "ErrorState",
  description: "Displays a compact, non-alarming error message with an alert icon, suitable for use inside cards or panels when data fails to load. Use it to communicate server or fetch errors to the user.",
  propsSchema: errorStateSchema as FlowletSchema<unknown>,
  source: "host",
};
