/**
 * Generated by `flowlet init` — review and edit freely; this file is yours.
 */
import { z } from "zod";
import type { RegisteredComponent, FlowletSchema } from "@flowlet/core";

export const barsSchema = z.object({
  items: z.string().describe("JSON string of BarItem array: [{label, value, color?, max?}]"),
  className: z.string().optional().describe("Additional CSS classes for the container"),
});

export const barsDescriptor: RegisteredComponent = {
  name: "Bars",
  description: "Renders a vertical list of labeled horizontal bars with USD values. Use for visualizing ranked category spend or budget comparisons.",
  propsSchema: barsSchema as FlowletSchema<unknown>,
  source: "host",
};
