/**
 * Generated by `flowlet init` — wraps src/components/charts/bars.tsx for the Flowlet sandbox.
 * Review and edit freely; this file is yours. The wrapper body was LLM-authored:
 * it runs inside the egress-jailed sandbox iframe (F3a CSP), but REVIEW IT like
 * any other generated code before committing.
 */
import { Bars } from "../../../src/components/charts/bars";
import { barsSchema } from "./descriptor";

// Named BarsWrapper (not Bars) so it never collides with the host import.
export function BarsWrapper(props: Record<string, unknown>) {
  const parsed = barsSchema.safeParse(props);
  if (!parsed.success) {
    return <div data-testid="flowlet-invalid-props">Invalid component props</div>;
  }
  const p = parsed.data;
  return <Bars items={JSON.parse(p.items)} />;
}
