/**
 * Generated by `vendo init` — review and edit freely; this file is yours.
 */
import { z } from "zod";
import type { RegisteredComponent, VendoSchema } from "@vendoai/core";

export const avatarSchema = z.object({
  initials: z.string().describe("Short text (typically 1-2 characters) displayed inside the avatar circle."),
  className: z.string().optional().describe("Additional CSS class names to apply to the avatar element."),
});

export const avatarDescriptor: RegisteredComponent = {
  name: "Avatar",
  description: "Displays a small circular avatar with initials text on a dark green background. Use when you need to represent a person or entity with a compact monogram badge.",
  propsSchema: avatarSchema as VendoSchema<unknown>,
  source: "host",
};
