/**
 * Generated by `vendo init` — wraps src/components/ui/badge.tsx for the Vendo sandbox.
 * Review and edit freely; this file is yours. The wrapper body was LLM-authored:
 * it runs inside the egress-jailed sandbox iframe (F3a CSP), but REVIEW IT like
 * any other generated code before committing.
 */
import { Badge } from "../../../src/components/ui/badge";
import { badgeSchema } from "./descriptor";

// Named BadgeWrapper (not Badge) so it never collides with the host import.
export function BadgeWrapper(props: Record<string, unknown>) {
  const parsed = badgeSchema.safeParse(props);
  if (!parsed.success) {
    return <div data-testid="vendo-invalid-props">Invalid component props</div>;
  }
  const p = parsed.data;
  return <Badge tone={p.tone}>{p.text}</Badge>;
}
