import path from "node:path";
import { transform } from "sucrase";
import { writeGenerated } from "../fsx.js";
import type { ComponentAnalysis } from "./analyze.js";
import type { ComponentCandidate } from "./scan.js";

/** Names already taken by the prewired library — generated hosts get a Host prefix. */
const PREWIRED_NAMES = new Set([
  "Card", "Table", "Chart", "Form", "Accordion", "Carousel", "Callout", "Tags",
  "Steps", "List", "Image", "ImageGallery", "Markdown", "CodeBlock", "Tabs", "TimeOfDayClock",
]);

export function registryName(analysis: ComponentAnalysis): string {
  return PREWIRED_NAMES.has(analysis.name) ? `Host${analysis.name}` : analysis.name;
}

function camel(name: string): string {
  return name[0]!.toLowerCase() + name.slice(1);
}

export function zodSource(props: ComponentAnalysis["props"]): string {
  const fields = props.map((p) => {
    let expr =
      p.type === "string" ? "z.string()"
      : p.type === "number" ? "z.number()"
      : p.type === "boolean" ? "z.boolean()"
      : p.type === "string[]" ? "z.array(z.string())"
      : p.type === "number[]" ? "z.array(z.number())"
      : `z.enum([${(p.enumValues ?? []).map((v) => JSON.stringify(v)).join(", ")}])`;
    if (p.optional) expr += ".optional()";
    expr += `.describe(${JSON.stringify(p.description)})`;
    return `  ${p.name}: ${expr},`;
  });
  return `z.object({\n${fields.join("\n")}\n})`;
}

export function descriptorSource(analysis: ComponentAnalysis): string {
  const name = registryName(analysis);
  const c = camel(name);
  return `/**
 * Generated by \`vendo init\` — review and edit freely; this file is yours.
 */
import { z } from "zod";
import type { RegisteredComponent, VendoSchema } from "@vendoai/core";

export const ${c}Schema = ${zodSource(analysis.props)};

export const ${c}Descriptor: RegisteredComponent = {
  name: ${JSON.stringify(name)},
  description: ${JSON.stringify(analysis.description)},
  propsSchema: ${c}Schema as VendoSchema<unknown>,
  source: "host",
};
`;
}

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

/**
 * The model is asked for bare export names but sometimes returns whole import
 * statements or file paths. Normalize each entry to identifiers: keep bare
 * names, unpack `import { A, B } from ...` shapes, drop anything else.
 */
export function normalizeImports(imports: string[]): string[] {
  const names = imports.flatMap((entry) => {
    const trimmed = entry.trim();
    if (IDENTIFIER.test(trimmed)) return [trimmed];
    const braced = trimmed.match(/\{([^}]*)\}/);
    if (braced?.[1]) return braced[1].split(",").map((s) => s.trim());
    return [];
  });
  return [...new Set(names.filter((n) => IDENTIFIER.test(n)))];
}

/**
 * Last-resort import derivation when the model returned no usable names
 * (e.g. file paths): PascalCase JSX tags used in the wrapper body, restricted
 * to symbols the host file verifiably exports — never invents an import.
 */
export function importsFromJsx(jsx: string, exportNames: string[]): string[] {
  const exported = new Set(exportNames);
  const tags = [...jsx.matchAll(/<([A-Z][A-Za-z0-9]*)/g)].map((m) => m[1]!);
  return [...new Set(tags.filter((t) => exported.has(t)))];
}

export function implSource(analysis: ComponentAnalysis, candidate: ComponentCandidate): string {
  const name = registryName(analysis);
  const c = camel(name);
  let imports = normalizeImports(analysis.imports);
  if (imports.length === 0) imports = importsFromJsx(analysis.jsx, candidate.exportNames);
  if (imports.length === 0) {
    throw new Error(`no usable named exports in imports list: ${JSON.stringify(analysis.imports)}`);
  }
  // .vendo/components/<Name>/impl.tsx -> host file, so hop out three levels.
  const importPath = path.posix.join("../../..", candidate.relFile).replace(/\.tsx?$/, "");
  return `/**
 * Generated by \`vendo init\` — wraps ${candidate.relFile} for the Vendo sandbox.
 * Review and edit freely; this file is yours. The wrapper body was LLM-authored:
 * it runs inside the egress-jailed sandbox iframe (F3a CSP), but REVIEW IT like
 * any other generated code before committing.
 */
import { ${imports.join(", ")} } from "${importPath}";
import { ${c}Schema } from "./descriptor";

// Named ${name}Wrapper (not ${name}) so it never collides with the host import.
export function ${name}Wrapper(props: Record<string, unknown>) {
  const parsed = ${c}Schema.safeParse(props);
  if (!parsed.success) {
    return <div data-testid="vendo-invalid-props">Invalid component props</div>;
  }
  const p = parsed.data;
  return ${analysis.jsx};
}
`;
}

export function entrySource(names: string[]): string {
  const imports = names.map((n) => `import { ${n}Wrapper } from "./${n}/impl";`).join("\n");
  return `/**
 * Generated by \`vendo init\`. Sandbox host bundle entry: exposes wrapped host
 * components to the Vendo stage runtime (window.__VENDO_HOST__ contract —
 * see packages/vendo-components/bundle/entry.ts for the reference bundle).
 * NOTE: merging these with the prewired bundle is host wiring (ENG-186/ENG-202).
 */
import React from "react";
import { createRoot } from "react-dom/client";
${imports}

declare global {
  interface Window {
    __React: typeof React;
    __createRoot: typeof createRoot;
    __VENDO_HOST__: Record<string, unknown>;
  }
}

window.__React = React;
window.__createRoot = createRoot;
window.__VENDO_HOST__ = { ${names.map((n) => `${n}: ${n}Wrapper`).join(", ")} };
`;
}

export function viteConfigSource(aliases: Record<string, string> = {}): string {
  const aliasEntries = Object.entries(aliases)
    .map(([k, v]) => `${JSON.stringify(k)}: path.resolve(here, ${JSON.stringify(v)})`)
    .join(", ");
  return `/** Generated by \`vendo init\`. Builds the host-component sandbox bundle. */
import path from "node:path";
import { fileURLToPath } from "node:url";
import { vendoHostPreset } from "@vendoai/stage/build";

const here = path.dirname(fileURLToPath(import.meta.url));
// Absolute entry: the build must work from any cwd (e.g. the host repo root).
const base = vendoHostPreset({ entry: path.resolve(here, "entry.ts"), version: "0.0.1" });

const config = {
  ...base,
  // This build produces only the sandbox bundle — never copy the host's public/.
  publicDir: false,
  // Host tsconfig path aliases, re-rooted relative to this directory.
  resolve: { alias: { ${aliasEntries} } },
};

export default config;
`;
}

/**
 * Turn the host tsconfig `paths` into vite aliases usable from
 * `.vendo/components/` (two levels below the target root). Only simple
 * `"@x/*": ["./dir/*"]` shapes are carried; anything else is skipped.
 */
export function aliasesFromTsconfigPaths(paths: Record<string, string[]>): Record<string, string> {
  const aliases: Record<string, string> = {};
  for (const [key, targets] of Object.entries(paths)) {
    const target = targets[0];
    if (!key.endsWith("/*") || !target?.endsWith("/*")) continue;
    aliases[key.slice(0, -2)] = path.posix.join("../..", target.slice(0, -2));
  }
  return aliases;
}

/** Throws with the sucrase error message when the generated TSX does not parse. */
export function assertParses(fileLabel: string, source: string): void {
  try {
    transform(source, { transforms: ["typescript", "jsx"] });
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    // Surface the offending line so the failure is diagnosable from the report
    // (and so the analyze repair loop gets real context).
    const lineNo = Number(msg.match(/\((\d+):\d+\)/)?.[1] ?? NaN);
    const line = Number.isNaN(lineNo) ? "" : ` — line reads: ${source.split("\n")[lineNo - 1]?.trim() ?? ""}`;
    throw new Error(`generated ${fileLabel} has a syntax error: ${msg}${line}`);
  }
}

export async function writeComponent(
  targetDir: string,
  analysis: ComponentAnalysis,
  candidate: ComponentCandidate,
  opts: { force: boolean },
): Promise<string> {
  if (!/^[A-Z][A-Za-z0-9]*$/.test(analysis.name)) {
    throw new Error(`component name ${JSON.stringify(analysis.name)} is not PascalCase`);
  }
  if (!analysis.description.trim()) throw new Error("included component needs a non-empty description");
  if (!analysis.jsx.trim()) throw new Error("included component needs a non-empty jsx expression");
  const name = registryName(analysis);
  const descriptor = descriptorSource(analysis);
  const impl = implSource(analysis, candidate);
  assertParses(`${name}/descriptor.ts`, descriptor);
  assertParses(`${name}/impl.tsx`, impl);
  const base = path.join(targetDir, ".vendo/components", name);
  await writeGenerated(path.join(base, "descriptor.ts"), descriptor, opts);
  await writeGenerated(path.join(base, "impl.tsx"), impl, opts);
  return name;
}
